### ISSUE TITLE
Small(er) quick start repo example?

### ISSUE THREAD

**Issue by hchiam** [GoogleChrome/lighthouse-ci#106]
# An idea
Do you think it'd be valuable to have a minimal example template repo to help beginners quickly start from scratch? Or does it already exist? (I can't seem to find a beginner-friendly example on GitHub yet.)

Here's my template repo: https://github.com/hchiam/learning-lighthouse-ci

## Possible ideas going forward
1) Link to my repo (likely not, unless I make changes*)
2) Create a separate folder inside [lighthouse-ci](https://github.com/GoogleChrome/lighthouse-ci) (I can make a branch + PR)
3) Create a separate repo and maybe title it something like `lighthouse-ci-minimal-example` (maybe by hitting ["Use this template"](https://github.com/hchiam/learning-lighthouse-ci) or using my repo as inspiration)

## Other ideas
*I could simplify [my repo](https://github.com/hchiam/learning-lighthouse-ci) even further (and maybe make it framework agnostic), but I'm just asking before investing time in pursuing an idea.

**Comment by patrickhulce** [comment]
Hiya @hchiam! Neat idea and great example repo you've got! Would you be interested in linking to your repo from our readme's "related projects" section? :) 

I think our goal within the `lighthouse-ci` repo itself should be writing clear enough documentation and getting started guides to be able to *add* Lighthouse CI to any project very easily but an example repo with create-react-app like yours is perfect for external contributions.

**Comment by hchiam** [comment]
Thanks @patrickhulce! [Done](https://github.com/GoogleChrome/lighthouse-ci/pull/107), pending PR merge. :)
