### ISSUE TITLE
temporary-public-storage broke

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse-ci#1072]
As of 5:17pm today (about an hour ago).

Someone bad ruined a good thing.

It likely won't be back up for a while. Sorry.

**Comment by lynndylanhurley** [comment]
@paulirish does "for a while" mean days, weeks or months?

We were relying on this pretty heavily, trying to gauge whether we should spin up our own server.

**Comment by paulirish** [comment]
The storage has been restored. We should be back in business.  

Apologies everyone for the downtime.
