### ISSUE TITLE
Project page redirects to LHCI Server homepage

### ISSUE THREAD

**Issue by gmougeolle** [GoogleChrome/lighthouse-ci#108]
I installed the LHCI server via the Docker image and run a `lhci collect` & `lhci upload` step in my Gitlab-CI configuration. 
Everything seems to work well, and listing the projects on the LHCI server works, but as soon as I click on a project, I can see the project infos starting to appear for half a second and I'm redirected on the homepage again.
There's no error on the client or on the server side.
If I browse directly to some test results (/app/projects/:slug/compare/:buildId), the data is there and the page displays without problems.

**Comment by patrickhulce** [comment]
Hm strange, do you happen to have the server publicly exposed somewhere I could take a look? Could DM or email it to me if you prefer.

**Comment by mhluska** [comment]
@patrickhulce I'm experiencing this too.

**Comment by patrickhulce** [comment]
Ah no the docker image hasn't been updated with the fix. I'll publish one today. 👍

**Comment by patrickhulce** [comment]
@mhluska 0.3.4 should be available with the fix

**Comment by mhluska** [comment]
Nice, thanks!

**Comment by garza** [comment]
How do I know what version docker is using?  I just used the lhci:latest, and I'm still getting this error.

**Comment by patrickhulce** [comment]
@garza you can hit `http://your-lhci-server.example.com/version`

If it's still happening for you on 0.3.4, do you happen to have the server publicly exposed somewhere I could take a look? Could DM or email it to me if you prefer.

**Comment by garza** [comment]
ah ok, /version is reporting 0.3.1, I must have the container cached
