### ISSUE TITLE
Decide on a charting library

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/lighthouse-ci#11]
Lots of options out there, lots of functionality we need.

At a glance we want...

- Compatible license
- Actively maintained
- Support for line graphs with error bars/confidence ranges/candlestick chart
- Play well with preact/react (wrapper already available)

 ## Options

![image](https://user-images.githubusercontent.com/2301202/61393508-beb30c80-a886-11e9-8ff7-9ba0a463b943.png)

| Library | License | Popularity | Candlestick Difficulty | Preact Difficultly |
| -- | -- | -- | -- | -- |
| d3 (raw) | BSD-3-Clause | 😄😄😄😄 | Difficult-ish | Difficult-ish |
| chart.js | MIT |  😄😄😄| Impossible-ish | Difficult-ish |
| highcharts | [Paid](https://shop.highsoft.com/highcharts) 😢  | 😄😄| Easy | Easy |
| recharts | MIT | 😄😄| Medium-difficult | Easy |
| plot.ly | MIT | 🙂| Easy | Easy| 
| fusioncharts | [Paid](https://www.fusioncharts.com/buy) 😢 | 😑 | [Easy](https://www.fusioncharts.com/charts/error-charts/error-line-2d-chart) | Easy |

**Comment by patrickhulce** [comment]
I'm inclined to go with plot.ly again.

**Comment by connorjclark** [comment]
plot.ly sounds good (only one I have experience with, discounting d3, which I wouldn't recommend for this unless you're just really bored).

should also add a column for "how much experience I have with it" as I'm sure that's a big contributing factor :)

**Comment by patrickhulce** [comment]
> should also add a column for "how much experience I have with it

Heh, then plot.ly wins by default! :)

**Comment by patrickhulce** [comment]
We've gone with plot.ly and a slightly modified preact wrapper, but it's a massive library at ~800KB for some simple plots so we might revisit again in the future.
