### ISSUE TITLE
request: yml support for config file (lighthouserc.json)

### ISSUE THREAD

**Issue by chris-kruining** [GoogleChrome/lighthouse-ci#111]
is this already supported or can support be added?

**Comment by patrickhulce** [comment]
Yaml is not supported at the moment. Our first priority will be `lighthouserc.js`, but I'm not opposed to yaml either.

**Comment by jzabala** [comment]
Hi @patrickhulce, I would like to try this one.

**Comment by patrickhulce** [comment]
Thanks @jzabala!

Basically update 

https://github.com/GoogleChrome/lighthouse-ci/blob/93b674203a39520d40f6c985048d83d2ed46a2b8/packages/utils/src/lighthouserc.js#L44-L54

to use yaml parser if the path ends with `.yml` or `.yaml` and add a few tests to lighthouserc.test.js

**Comment by jzabala** [comment]
Thanks for all the details @patrickhulce.

I'll be working on it 🙂.
