### ISSUE TITLE
GitLab docs suggest --no-sandbox: bad for perf testing?

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse-ci#113]
This feels like it would affect performance in an undesirable manner. Should investigate if just switching the user used in the image (away from root) is possible.

**Comment by patrickhulce** [comment]
Bad in what way? If you don't switch from using the flag to not using the flag, it shouldn't be particularly bad for consistency and if you're running in an environment that can only work with `--no-sandbox` you're already in the very-different-from-your-users environment as it is, so I'm not convinced this will be the straw that breaks the camels back on fidelity.

IMHO, `--no-sandbox` is a reality in many CI environments, isn't really in the top list of concerns for production realism, and would be nice to see disappear but ultra low priority :)

**Comment by connorjclark** [comment]
I initially got this switch confused with process isolation, hence my concern about performance. I agree that this switch probably doesn't affect performance much.

BTW developers.google.com mentions how to avoid this:

https://developers.google.com/web/updates/2017/04/headless-chrome links to
https://github.com/GoogleChromeLabs/lighthousebot/blob/master/builder/Dockerfile#L35-L40

**Comment by patrickhulce** [comment]
Oh neat! I had thought the puppeteer issues basically reestablished its permanence 😆 

we'll add that to docs 👍
