### ISSUE TITLE
Configure paths?

### ISSUE THREAD

**Issue by mhluska** [GoogleChrome/lighthouse-ci#114]
I'm trying to use this in Travis CI with a Vue project like so:

```
after_success:
- npm install -g @lhci/cli@0.3.x
- npm run build
- lhci autorun
```

The problem is this seems to run `index.html` in the `dist` dir with a root path. Our root path is set up to not render anything (in fact it redirects to a different website). Can we tell `lhci` to load something else like `/dashboard`?

The way our production environment is set up is the typical single-page app: all URL paths map to the `index.html` file  and the vue router decides what to render based on that.

**Comment by patrickhulce** [comment]
Yes, all the [options of `collect`](https://github.com/GoogleChrome/lighthouse-ci/blob/master/docs/cli.md#collect) are available to you, so you can use whatever server you like that has the functionality you need.

```bash
lhci autorun \
  --collect.startServerCommand="vue-cli-service serve --mode=production" \
  --collect.url="http://localhost:8080/dashboard"` \
  --collect.url="http://localhost:8080/some/other/page/"`

**Comment by mhluska** [comment]
I see. Without specifying these options, it seems to start a server on a random port before running the tests. What paths does it run against by default? I'm assuming just the root URL.

**Comment by patrickhulce** [comment]
If you don't figure *anything* it will audit all the HTML files found in the build directory, so in this case, `localhost:PORT/index.html`

**Comment by mhluska** [comment]
The only issue with the code sample above is it times out waiting for the server to finish booting:

```
WARNING: Timed out waiting for the server to start listening.
         Ensure the server prints "listening" when it is ready.
```

I suspect I need to build a wrapper around the server that prints that string when ready.
