### ISSUE TITLE
Socket hang up after server requests came through

### ISSUE THREAD

**Issue by aaraar** [GoogleChrome/lighthouse-ci#117]
After I had managed to get an lhci server working on a k8s cluster I wanted to host it on my own server. There is no docker container on this server, just the lhci server node process running. After the lhci autorun is complete, I can see the GET and POST requests coming in and it shows the hashes of previous commits on the lhci server dashboard, however the fetch request fails with the following error at the client

```
FetchError: request to {lhciserver.com}/v1/projects/{token}/builds/{buildHasH}/lifecycle failed, reason: socket hang up
    at ClientRequest.<anonymous> (.../node_modules/@lhci/cli/node_modules/node-fetch/index.js:133:11)
    at ClientRequest.emit (events.js:193:13)
    at TLSSocket.socketOnEnd (_http_client.js:431:9)
    at TLSSocket.emit (events.js:198:15)
    at endReadableNT (_stream_readable.js:1139:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
```

Any idea what might cause this error? When looking it up, it seems to have something to do with a request that takes too long after which the socket is not kept alive

**Comment by connorjclark** [comment]
Can you curl  the lhci server endpoint in your CI, just to confirm you can hit it?

**Comment by patrickhulce** [comment]
@aaraar what are the specs of the server you're running and how many runs are you uploading per build?

The logic on the server is rather simplistic at the moment where it reads all the LHRs into memory for a build to pick the "representative" one when it updates the lifecycle to `sealed` (the route that appears to be failing). If you don't have enough resources to do that, the server will likely crash and lead to a socket hang up error.

**Comment by aaraar** [comment]
I was able to just curl the endpoints that the requests go to, the memory usage is fairly high however.
```
free -m
             total       used       free     shared    buffers     cached
Mem:         11776      11355        421          0       1263       2248
```
Will get back to this myself on Thursday

**Comment by patrickhulce** [comment]
Ah, yeah if you have other stuff running on the machine pushing memory limits that might be your issue. You can also try increasing the heap size of node when you launch the server if you actually have enough space but it doesn't seem to be taking advantage of it (`node --max-old-space-size=4096 server.js`).

LHCI *server* logs should tell us more if you keep running into issues though :)

**Comment by aaraar** [comment]
Okay, I got it to work on another server with a bit more usable capacity.
Seems to have been a resource problem indeed.
Thanks!
