### ISSUE TITLE
Setting env vars for postgres use

### ISSUE THREAD

**Issue by Djiit** [GoogleChrome/lighthouse-ci#121]
I can't find the correct env var to set to tell the lhci server to use postgres for storage. Tried : 
- LHCI_POSTGRES_DB_URL
- LHCI_SQLDIALECT
- LHCI_SERVER__STORAGE__SQLDIALECT

Did I miss something ? Thanks for your help

**Comment by jzabala** [comment]
Hi @Djiit I haven't use that option yet but based on the cli args it looks like you need to set them when you run the command: 

`lhci server --storage.sqlDialect=postgres --storage.sqlConnectionUrl="postgres://user@localhost/lighthouse_ci_db"`

or in the `lighthouserc.json`.

https://github.com/GoogleChrome/lighthouse-ci/blob/master/docs/cli.md#server

**Comment by Djiit** [comment]
Hey, thanks for your answer. I was looking to a env-var only solution to
use the already available image from the docker hub : I need to provide the
pgsql db url at runtime (when the container start, I tell it where its db
is).

I guess I'll go with my own image if I have to.

Thanks again anyway, I appreciate your help !

--
Julien

Le ven. 29 nov. 2019 à 20:33, Johnny Zabala <notifications@github.com> a
écrit :

**Comment by jzabala** [comment]
> Hey, thanks for your answer. I was looking to a env-var only solution to use the already available image from the docker hub : I need to provide the pgsql db url at runtime (when the container start, I tell it where its db is). I guess I'll go with my own image if I have to. Thanks again anyway, I appreciate your help !

Ok, I get it. Sorry that my answer didn't solve your issue. Well if you end up creating your own image please share in case it can help someone else 🙂.

Good luck.

**Comment by patrickhulce** [comment]
There's a 1:1 mapping from env vars to CLI flags that follows [yargs](https://github.com/yargs/yargs/blob/master/docs/api.md#envprefix).

So `LHCI_PROPERTY_NAME__SUBPROPERTY_NAME` is equivalent to `--propertyName.subpropertyName`.


In this case...

```bash
export LHCI_STORAGE__SQL_DIALECT="postgres"
export LHCI_STORAGE__SQL_CONNECTION_URL="postgres://user@localhost/lighthouse_ci_db"
```

should work

**Comment by Djiit** [comment]
It does work !

Thanks!

**Comment by Djiit** [comment]
Just pushed this to add your usefull comment in the docs : https://github.com/GoogleChrome/lighthouse-ci/pull/123

**Comment by lili21** [comment]
no need for username and password of the sql? how does that work?
