### ISSUE TITLE
How to delete project created by wizard command

### ISSUE THREAD

**Issue by diendang271** [GoogleChrome/lighthouse-ci#126]
I run lighthouse CI in Kubernetes, how to delete project created by wizard command? I can edit the lhci.db in Kubernetes persistent volume to delete the project, is there another official ways?

**Comment by patrickhulce** [comment]
> I can edit the lhci.db in Kubernetes persistent volume to delete the project, is there another official ways?

That's the only way right now. UI to manage projects is tracked by #86
