### ISSUE TITLE
how to append the auth info to the url by querystring?

### ISSUE THREAD

**Issue by lili21** [GoogleChrome/lighthouse-ci#129]
how I can achieve this?

**Comment by patrickhulce** [comment]
I'm not sure what you mean. You're in control of what URLs you provide to Lighthouse CI so if you need to add something to the query string you can...

**Comment by lili21** [comment]
but the `something` is dynamic.
I want to get the auth info from the backend API and append it to the query string. 
I guess I can get the auth info via puppeteer script, but I don't know what should I do next.

**Comment by patrickhulce** [comment]
We determine the URLs dynamically in the use of LHCI on our own project :) Basically you want to run a script before `lhci` that determines your URLs.

Example:

https://github.com/GoogleChrome/lighthouse-ci/blob/73e779381f0603e9c9096e23f1796c2c4a60d8c4/scripts/ci-dogfood.sh#L12-L23

https://github.com/GoogleChrome/lighthouse-ci/blob/73e779381f0603e9c9096e23f1796c2c4a60d8c4/scripts/ci-dogfood-get-urls.js#L17-L28

**Comment by lili21** [comment]
Thanks, that's helpful.

**Comment by otwm** [comment]
```
yarn start collect "--url=$url" --additive || exit 1
``` 
```
ex url)
http://test.com?name=${name}&age=${age}
```
When collecting dynamically in the above code, if you use a complex query string, it is not recognized as one page and cannot be compared. Therefore, creating an url without a query string in a test environment and using that url can be an alternative. But it would be nice to have a better way.

**Comment by patrickhulce** [comment]
@otwm there's an [FAQ](https://github.com/GoogleChrome/lighthouse-ci/blob/d391de4096a8a962fff4adc7258c94f6540adaa9/docs/troubleshooting.md#my-urls-change-between-builds-and-lhci-server-cant-link-them) for that situation ;)
