### ISSUE TITLE
puppeteerScript not invoked

### ISSUE THREAD

**Issue by wan54** [GoogleChrome/lighthouse-ci#130]
Configured the script in .lighthouserc.json as below:

```
"collect": {
     "headful": true,
      "puppeteerScript": "./scripts/lhLogin.js"
}
```

lhLogin.js:

```
module.exports = async browser => {
	const page = await browser.newPage();
	await page.goto('https://google.com'); // test to see if this script is invoked
        await page.waitForNavigation(); 
};
```

Installed puppeteer-core@2.0.0

Any ideas?

**Comment by patrickhulce** [comment]
Ah sorry @wan54 I haven't published master yet with the feature so docs are a bit ahead, I'll do that today :)

**Comment by patrickhulce** [comment]
0.3.5 was just published to match the docs now @wan54 you should be good to go :)

(fwiw though, you won't *see* the browser navigation because that step is run with headless chrome)
