### ISSUE TITLE
Expose puppeteer settings

### ISSUE THREAD

**Issue by wan54** [GoogleChrome/lighthouse-ci#132]
Got this error in gitlab ci: `[1202/220116.316246:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.`

.lighthouserc.json

```
"collect": {
      "puppeteerScript": "./scripts/lhLogin.js",
	        "settings": {
				"chromeFlags": "--disable-gpu --no-sandbox --disable-web-security"
		}
}
```

**Comment by patrickhulce** [comment]
Ah, correct the settings are just for Lighthouse which is no longer launching Chrome. Maybe it's best for us to just expose the puppeteer settings directly and separately?

**Comment by wan54** [comment]
If LH is still launching puppeteer and there are no use cases in which chrome flags and puppeteer flags are used differently then `chromeFlags` should be kept and used

**Comment by patrickhulce** [comment]
I think it better to expose puppeteer settings directly, Lighthouse itself is not involved with launching puppeteer and it's only an extension of the collect command in Lighthouse CI. To avoid confusion and allow full control of the puppeteer instance, we'll expose all the puppteer launch options 👍
