### ISSUE TITLE
Write HTML reports to .lighthouseci folder during collect

### ISSUE THREAD

**Issue by alexfornuto** [GoogleChrome/lighthouse-ci#137]
I'm attempting to replace a custom lighthouse test configuration with lhci. I'm not getting HTML output in `.lighthouseci`, only json. I've attempted to define the lighthouse settings in `lighthouserc.json`:

```
{
  "ci": {
    "collect": {
      "settings": {
        "output": ["html"],
        "skipAudits": ["is-cralwable"],
        "useThrottling": "true",
        "onlyCategories": [
            "performance",
            "accessibility",
            "best-practices",
            "seo"
        ]
    },

...

```

And also pointing to the original configuration file:

```
{
  "ci": {
    "collect": {
      "settings": {
        "configPath": "./tests/lighthouse/lighthouse-config.js"
    },

...

```

with `lighthouse-config.js` containing:

```
module.exports = {
    extends: 'lighthouse:default',
    settings: {
        output: ['html'],
        skipAudits: ['is-cralwable'],
        useThrottling: true,
        onlyCategories: [
            'performance',
            'accessibility',
            'best-practices',
            'seo'
        ],
    },
}
```

Does LHCI not allow for HTML result pages, or am I doing something wrong?

**Comment by patrickhulce** [comment]
You can't overwrite the output because Lighthouse CI reads the JSON on stdout for all of its other tasks. Are you intending to just use the output in `.lighthouseci/` folder yourself without any other `lhci` commands?

**Comment by alexfornuto** [comment]
I think the answer to your question is "Yes". I want to link to the report html files in my GitHub comments on the PR.

**Comment by patrickhulce** [comment]
Hm, where are you storing the reports to be able to link to them from the comments then? 

Right now it sounds like you're going about this the way that requires you to manage a crap-ton of JS code, so I'd like to see if `lhci upload` can support your use case out of the box instead :)

**Comment by alexfornuto** [comment]
@patrickhulce The reports are stored as artifacts in CircleCI. You can see an example of the current implementation [here](https://github.com/pantheon-systems/documentation/pull/5372)

**Comment by patrickhulce** [comment]
Gotcha, thanks for sharing! We can just write the HTML reports next to the JSON then if that'd help. Alternative approach I see is a `lhci upload --target=filesystem --filesystem-destination=path/to/folder`, but that seems to provide little value over copying yourself.

**Comment by alexfornuto** [comment]
Is `filesystem` currently a valid target for upload, or are you suggesting that as a solution? The [docs](https://github.com/GoogleChrome/lighthouse-ci/blob/master/docs/cli.md#upload) don't indicate it as an option currently.

I agree that writing HTML reports into `.lighthouseci` is good enough for me. If you wanted to implement filesystem as a target for `upload`, a possible advantage  would be defining a target artifact directory, instead of having to move/point from/to `.lighthouseci` in the CI system config. Up to you if that's worth the effort.

Thanks for your attention to this issue!

**Comment by patrickhulce** [comment]
It was just a proposal, we'll just write the HTML reports to `.lighthouseci` for now unless there becomes more demand for a `filesystem` target.
