### ISSUE TITLE
Add warning when using chrome-flags and puppeteerScript

### ISSUE THREAD

**Issue by mysticPrg** [GoogleChrome/lighthouse-ci#143]
I had confused about chrome flags settings.

In my project, using custom userAgent. So first, I tried these settings.

```json
{
  "ci": {
    "collect": {
      "settings": {
        "chrome-flags": "--user-agent=something"
      }
    }
  }
}
```

It only worked before I add `puppeteerScript` options.
If the user using `puppeteerScript`, lighthouse's chrome flags options will be ignored and the settings should be changed like this.

```json
{
  "ci": {
    "collect": {
      "puppeteerScript": "script.js",
      "puppeteerLaunchOptions": {
        "args": ["--user-agent=something"]
      }
    }
  }
}
```

It confused me.
I suggest these two options.
1. Re-position chrome-flags option like this.
```json
{
  "ci": {
    "collect": {
      "chromeFlags": ["--user-agent=something"],
      "puppeteerScript": "script.js",
    }
  }
}
```

2. Just show warnings when that case.
```shell
lhci collect
[WARN] Your chrome flags options will be ignored because of... blah blah
```

What's your opinion?
Can I handle this issue?

**Comment by patrickhulce** [comment]
Let's add your suggested warning and rely on improving the documentation :) 

I want to avoid the duplication of options that do subtlely different things in different cases, the headful option is already annoying enough to deal with

**Comment by patrickhulce** [comment]
And yes thank you for filing @mysticPrg we'd be happy to have you tackle the warning if you'd like!
