### ISSUE TITLE
Show LHCI server version on UI

### ISSUE THREAD

**Issue by ravick12** [GoogleChrome/lighthouse-ci#145]
@patrickhulce 
     Is there currently a way to find out which version the LHCI server is running?  I guess I can look at the package.json in the docker container to see which version of @lhci/server is running. But it will be good to have some place in UI (e.g footer or in the side menu), that shows the version number.

**Comment by patrickhulce** [comment]
@ravick12 you can hit `/version` URL on the server to find out what version it's running. Adding it to the sidebar UI isn't a bad idea though :)

**Comment by ravick12** [comment]
@patrickhulce thanks for the version link.

**Comment by patrickhulce** [comment]
This was fixed by #150 🎉

**Comment by wodka** [comment]
:/ it always shows up as 0.1.0 -> the package.json version is not up to date

`/version` returns 0.3.12

**Comment by patrickhulce** [comment]
Ah thanks @wodka the build process probably changed since #150 that broke this, we'll use the API version instead 👍
