### ISSUE TITLE
`lhci autorun` in multiple build stages?

### ISSUE THREAD

**Issue by mhluska** [GoogleChrome/lighthouse-ci#146]
How can this be run in both a `test` and `deploy` stage? I get the following error:

```
non-unique build for this hash
```

I tried working around it by adding this to my `.travis.yml`:

```
- export LHCI_BUILD_CONTEXT__CURRENT_HASH="${TRAVIS_BUILD_STAGE_NAME}_${TRAVIS_PULL_REQUEST_SHA}"
```

Which allows it to pass the health check but then it fails with something else:

```
Runtime error encountered: Protocol error (Page.setLifecycleEventsEnabled): 'Page.setLifecycleEventsEnabled' wasn't found
```

Edit:

I added latest chrome with:

```
    addons:
      chrome: stable
```

But now I'm getting the following error: 

```
Error: Unable to determine commit message with `git log --format=%s -n 1`
```

**Comment by patrickhulce** [comment]
Thanks for filing!

> How can this be run in both a test and deploy stage?

In general, things will go poorly right now if you try to use something that isn't a hash for the hash field.

The server is setup to assume one build per hash-branch pair. If you want to upload more than one build per hash, you'll need to fake the *branch* that you're on (`LHCI_BUILD_CONTEXT__CURRENT_BRANCH="$TRAVIS_PULL_REQUEST_BRANCH-$TRAVIS_BUILD_STAGE_NAME"`). On `master` though, you'll want to make sure you upload at least 1 of your builds that is just `master` and not `master-$SOMETHING_ELSE`.

**Comment by patrickhulce** [comment]
Closing as resolved. Please file a new issue if you there any further problems.
