### ISSUE TITLE
Instructions on deleting individual data points?

### ISSUE THREAD

**Issue by mhluska** [GoogleChrome/lighthouse-ci#149]
Is there currently a way to delete individual data points that were uploaded with `lhci upload`? Particularly with the kubernetes server.

**Comment by patrickhulce** [comment]
You'd need to connect directly to your database in kubernetes and delete the `statistic`/`run`/`build` associated with it. Because the server is still unauthenticated, the API doesn't allow any destructive updates.

rough steps:

```bash
# Connect to your pod
kubectl exec -it lhci-pod -- /bin/bash
# Make sure your server isn't running/actively connected to your database and make a backup in case mistakes are made
cp /data/lhci.db /data/lhci.db.bak
# Connect to your sql database, default if using docker image recipe is /data/lhci.db
sqlite3 /data/lhci.db
# Find the build you want to delete
> SELECT id FROM builds WHERE hash = '<whatever hash you want to delete>'
# Delete the rows
> DELETE FROM statistics WHERE buildId = '<buildId>'
> DELETE FROM runs WHERE buildId = '<buildId>'
> DELETE FROM builds WHERE id = '<buildId>'

**Comment by mhluska** [comment]
Thanks. That worked perfectly. I just had to do `apt-get update && apt-get install sqlite3` to get `sqlite3`.

**Comment by patrickhulce** [comment]
Awesome glad to hear it! :)
