### ISSUE TITLE
Manage server projects lifecycle via single-line commands

### ISSUE THREAD

**Issue by thasmo** [GoogleChrome/lighthouse-ci#152]
It would be nice to manage projects using single-line commands; something like:

```sh
lhci project create --server-url http://server.url/ --repository-url https://github.com/thasmo/website --name 'my-project'

lhci project delete --force <TOKEN>
```
or similar.

This way it should be easier to create projects in an automated way. Or is there currently a way to create/delete new projects more easily? Thanks!

**Comment by patrickhulce** [comment]
Thanks for filing @thasmo!

The API is currently unauthenticated (the current append-only tokens are considered public information), so no destructive actions are allowed. Anything that requires deleting data would need to be done by connecting to the database directly at the moment (see #149).

As for automated creation of projects, you can use the `ApiClient` class from node

```js
const ApiClient = require('@lhci/utils/src/api-client.js')
const client = new ApiClient({rootURL: 'http://server.url/'})
await client.createProject({
    name: 'My Project', 
    slug: 'my-project',
    externalUrl: 'https://github.com/project',
})
```

The planned future for project management will be an admin UI (part of #85) at which point the API client would also support those same actions for automation, so I think it's unlikely we'd expand a new CLI wrapper for it.

**Comment by thasmo** [comment]
> The planned future for project management will be an admin UI (part of #85) at which point the API client would also support those same actions for automation, so I think it's unlikely we'd expand a new CLI wrapper for it.

Sounds legit, thanks for answering so quick!

**Comment by patrickhulce** [comment]
Closing as resolved. Please file a new issue if you there any further problems.
