### ISSUE TITLE
Custom auth headers in ApiClient

### ISSUE THREAD

**Issue by Lusitaniae** [GoogleChrome/lighthouse-ci#153]
We currently have all internal tools behind Cloudflare Access.

To use lighthouse right now we have to exclude the subdomain used for the lhci server from the access rules.

Ideally we would be able to add custom headers to the requests made from lhci with the required access tokens.

https://developers.cloudflare.com/access/service-auth/service-token/

> CF-Access-Client-Id:
> CF-Access-Client-Secret:

I imagine changes would be required here https://github.com/GoogleChrome/lighthouse-ci/blob/master/packages/utils/src/api-client.js#L75 but I leave it to someone with more knowledge in node.

**Comment by patrickhulce** [comment]
Thanks for filing @Lusitaniae! Great feature request and something we'd like to support. What would you expect this option to be named in `upload`

`--lhci-extra-headers` maybe?

**Comment by Lusitaniae** [comment]
Sounds great to me

**Comment by Lusitaniae** [comment]
Great turnover, many thanks!
