### ISSUE TITLE
Continuously deploy docker image to Docker Hub

### ISSUE THREAD

**Issue by Lusitaniae** [GoogleChrome/lighthouse-ci#156]
Docker Hub doesn't have the latest release 0.3.5 and  0.3.6

https://hub.docker.com/r/patrickhulce/lhci-server/tags

We could automate publishing new docker images and also make `latest` use the code from master.

I could give this a try later one.

**Comment by patrickhulce** [comment]
Thanks for filing @Lusitaniae! There were no server updates in 0.3.5, just client/CLI updates and 0.3.6 just had the single metrics calibration UI commit, so didn't seem necessary to push, but continuous deployments would be great!

The only wrinkle for an external contrib I see here is the auth piece of this.

**Comment by Zizzamia** [comment]
The Docker image is quite [simple](https://github.com/GoogleChrome/lighthouse-ci/blob/master/docs/recipes/docker-server/Dockerfile)

```
FROM node:10

WORKDIR /usr/src/lhci
COPY package.json .
COPY lighthouserc.json .
RUN npm install

EXPOSE 9001
CMD [ "npm", "start" ]
```

we actually end up just recreate an internal version based on the original one.

**Comment by camelpunch** [comment]
+1. Looks like v0.3.8 does have server changes, but no docker hub tag. It's totally doable to build your own docker image, but it's more infrastructure to set up for each consumer.

**Comment by patrickhulce** [comment]
thanks for the poke @camelpunch just published it, but yes automated deploys are the answer here :)
