### ISSUE TITLE
Add SPA support to fallback server

### ISSUE THREAD

**Issue by lili21** [GoogleChrome/lighthouse-ci#157]
the fallback-server does not support front-end router right now.

**Comment by patrickhulce** [comment]
Thanks for filing @lili21, good idea!

This should be fairly straightforward  if anyone is looking for their first contribution :) 

Basically add 
```js
app.get('*', (_, res) => res.sendFile(path.join(pathToBuildDir, 'index.html')))
```
to
https://github.com/GoogleChrome/lighthouse-ci/blob/3a34a7b0a9f57b78ec1d5c1be5263262408c61fa/packages/cli/src/collect/fallback-server.js#L18-L24

and a test to go along with it

**Comment by Amagon96** [comment]
Working on it! n.n/

**Comment by rdlabo** [comment]
I found this Issue after making pull request👀
https://github.com/GoogleChrome/lighthouse-ci/pull/159

@Amagon96 How is the progress? If you haven't started yet, I'd be happy to get feedback on this code.

Thanks.

**Comment by Amagon96** [comment]
Hi @rdlabo  actually I already done, I'll be requesting the PR soon since I just woke up :p
