### ISSUE TITLE
Enable Running lighthouse for multiple pages/URLS.

### ISSUE THREAD

**Issue by FahdJamy** [GoogleChrome/lighthouse-ci#162]
**Motivation or use case**

- To this day, I can't seem to be able to run lighthouse for multiple pages/URLs.
- I should be able to have the capability of running lighthouse command and provide all URLs to pages that I want to test.

**How is this beneficial to Lighthouse-ci?**

- Avoiding duplication of commands or having to run lighthouse multiple times because I want to test multiple pages/URLs

**Example command suggestion**

- `lighthouse-ci --seo=90 --accessibility=80 <url-1>,<url-2>,<url-3>`

**Comment by jzabala** [comment]
Thanks for filling @FahdJamy.

Actually it is possible to run lighthouseci on multiple pages/urls as you describe. Check this issue https://github.com/GoogleChrome/lighthouse-ci/issues/124 for more info.

**Comment by FahdJamy** [comment]
Thanks @jzabala
