### ISSUE TITLE
value too long for type character varying(256)

### ISSUE THREAD

**Issue by lili21** [GoogleChrome/lighthouse-ci#166]
```bash
Saving CI project test-lhci-7068 (d64e99f0-15fd-466a-88b2-9a07f20ac1b9)
Saving CI build (aa5702e1-30b7-4811-b392-b45cd34a5989)
Error: Unexpected status code 422
  {"message":"value too long for type character varying(256)"}
    at ApiClient._convertFetchResponseToReturnValue (/usr/local/lib/node_modules/@lhci/cli/node_modules/@lhci/utils/src/api-client.js:55:21)
```

**Comment by lili21** [comment]
url length limit.

**Comment by patrickhulce** [comment]
Thanks for filing @lili21! We're going to have to put *some* limit on the URL for performant queries, so the questions are:

- How large should that limit be?
- What to do when the URL exceeds that limit?

Right now the answers are
- 256 characters
- Fail to save the build

Alternatives:
- 512
- 1024
----
- Only save the first X characters of the URL

Any preferences here?

**Comment by lili21** [comment]
Actually, the build had been saved, it's the runs that failed to save.

**Comment by patrickhulce** [comment]
Sorry, yes by "build" I meant the collection of database objects associated with the CI build, not the build Lighthouse CI model. Any thoughts on the above? :)

**Comment by lili21** [comment]
I'd prefer the 3rd alternative - only save the first X characters of the URL.
and mentioned this in the docs.
