### ISSUE TITLE
Suggestion: Change behaviour when url and staticDistDir are provided

### ISSUE THREAD

**Issue by arthurdenner** [GoogleChrome/lighthouse-ci#168]
Hi! 👋 First, thank you for this project, it has been helping me a lot recently.

Currently, the library doesn't support nested folders - but this is planned for `0.4.0` - and it's possible to set URLs with the `staticDistDir` option. However, it's not possible to combine the URLs automatically found by the server with the ones provided in the `url` option because of [this `if` statement](https://github.com/GoogleChrome/lighthouse-ci/blob/3a34a7b0a9f57b78ec1d5c1be5263262408c61fa/packages/cli/src/collect/collect.js#L133).

I was wondering if we could (and should) allow for both features. If that's the case, I can open a PR to remove the statement. I've tested locally and it works as expected, but again, I don't know if that's the best route.

Such change would allow for the following config...

```json
"collect": {
  "numberOfRuns": 1,
  "staticDistDir": "./public",
  "url": ["/privacy"]
}
```

...to run 1 time in the following pages/files:

```
http://localhost:64093/privacy
http://localhost:64093/404.html
http://localhost:64093/index.html
```

Let me know your thoughts, please.

**Comment by patrickhulce** [comment]
Thanks very much for filing @arthurdenner! 

I'm rather against mixing the automatic detection with manual URLs though for a couple reasons:

- It becomes difficult and too magical to figure out what's happening (I manually said to audit these URLs so where are all these others coming from, how do I turn it off, etc?)
- It requires introducing another option to disable the automatic detection for the cases like the above where  automatic detection is picking up the wrong URLs.
- Automatic detection of URLs is just meant as a reasonable default and only helps pick out like 5 URLs max, so at worst you're manually specifying extra 5 strings which doesn't seem like a very big burden to get the benefits above.

We'll be picking up steam now that holidays are behind us so nested detection and 0.4.0 shouldn't be far off :)

**Comment by arthurdenner** [comment]
Thanks for your inputs, @patrickhulce. Seems very reasonable indeed.
