### ISSUE TITLE
How to handle Authentication

### ISSUE THREAD

**Issue by manoj-mass** [GoogleChrome/lighthouse-ci#169]
Hi,
Im quite new to lighthouse-ci and considering to adopt it to assess accessibility of a web application . The application do have an authentication where users required to enter username/ password before navigate to landing page. Is this possible with lighthouse-ci ? If so could anyone point me to the documentation or suggest any workarounds. THanks.

**Comment by patrickhulce** [comment]
Yes, [here's the documentation](https://github.com/GoogleChrome/lighthouse-ci/blob/3a34a7b0a9f57b78ec1d5c1be5263262408c61fa/docs/cli.md#using-puppeteer-scripts).

**Comment by manoj-mass** [comment]
Thanks.
