### ISSUE TITLE
How to define throttling and also calculate resourceSize using lighthouserc.json

### ISSUE THREAD

**Issue by DinakarC-practise** [GoogleChrome/lighthouse-ci#171]
Instead of pointing to config.js or .json, Is there any way to set throttling?
And also to calculate the resource size like images and scripts?. 
Providing sample code will be helpful.
I am expecting this for throttling. 
`{
  "ci": {
    "collect": {
      "settings": {
        "cpuThrottling": 4,
         "networkThrottling" : "slow3G"
      }
    }
  }
}`

**Comment by patrickhulce** [comment]
> Is there any way to set throttling?

Yes, the settings object is just standard Lighthouse configuration passed directly to Lighthouse. You can refer to the [Lighthouse docs](https://github.com/GoogleChrome/lighthouse#cli-options). `settings: {throttling: {cpuSlowdownMultiplier: 4, rttMs: 150, ...}}`

> And also to calculate the resource size like images and scripts?.

I have no idea what this means. Are you referring to [performance budgets](https://github.com/GoogleChrome/lighthouse-ci/blob/74876654df8d06d9df3378d7d098305d58906f5e/docs/assertions.md#budgets)?

**Comment by DinakarC-practise** [comment]
Thanks for helping out in throttling, and Yes, I am referring to Performance budgets.
