### ISSUE TITLE
what's the difference between `preset: lighthouse:no-pwa` and `categories:pwa: off` ?

### ISSUE THREAD

**Issue by lili21** [GoogleChrome/lighthouse-ci#176]
```json
{
  "ci": {
    "assert": {
      "preset": "lighthouse:no-pwa"
    }
  }
}
```
vs

```json
{
  "ci": {
    "assert": {
      "assertions": {
        "categories:pwa": "off"
      }
    }
  }
}
```

**Comment by patrickhulce** [comment]
Seems like you've figured this out already but for others who stumble on this issue, `categories:pwa` assertion is *just* on the *score* of the category and does not do anything with each individual audit. `lighthouse:no-pwa` preset turns off all PWA audit assertions.
