### ISSUE TITLE
js config not supported

### ISSUE THREAD

**Issue by olmer88** [GoogleChrome/lighthouse-ci#180]
In docs stated that lighthouserc.js config supported but it doesn't work, just JSON.

**Comment by patrickhulce** [comment]
That code has been merged but not published to NPM as `stable` yet, it will be in 0.3.8

**Comment by patrickhulce** [comment]
FYI it's been published with mysql support now too :) 🎉

**Comment by sarahLardeau** [comment]
Hi, I got an error when I try to use a JS config while it works perfectly with a JSON config :/

**Comment by patrickhulce** [comment]
@sarahLardeau ah that might be a relative directory issue, does it work if you specify the absolute path? `$(pwd)/config/.lighthouserc.js`?

We should definitely handle that better though :)

**Comment by sarahLardeau** [comment]
Yes it works fine with the absolute path !
Thanks for the fast answer :)
