### ISSUE TITLE
Use of plugins

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse-ci#19]
Is it possible to run `lhci collect` along with a plugin?

Hmmmm is it possible via something like 

```bash
lighthouse-ci collect --numberOfRuns=5 --url=https://example.com --settings="--plugins=foo-plugin"
```

err nope, thats not it.
anyway i guess this is a matter of documentation. :p

**Comment by patrickhulce** [comment]
`--settings.plugins=foo-plugin` should work but I would expect folks to set settings via the rc-file where an object makes much more sense :)
