### ISSUE TITLE
--no-sandbox not work in .lighthouserc.js

### ISSUE THREAD

**Issue by olmer88** [GoogleChrome/lighthouse-ci#190]
I tried to set up --no-sandbox in .lighthouserc.js but it doesn't work. Am I doing something wrong or this option is not supported in config file?

module.exports = {
  ci: {
    collect: {
      settings: { chromeFlags: 'no-sandbox' },
...

This works:
lhci autorun --collect.settings.chromeFlags="--no-sandbox"

**Comment by patrickhulce** [comment]
Did you try `settings: { chromeFlags: '--no-sandbox' }`? The chromeFlags value itself needs to be the same whether it's set on CLI or the config.

**Comment by olmer88** [comment]
Thanks! With "--" works fine.

**Comment by marcellodesales** [comment]
# 💡 Working

```console
lhci autorun --collect.startServerCommand="http-server ./build" \
                     --collect.startServerReadyPattern="Available" \
                     --collect.url=http://localhost:8080/ \
                     --assert.preset=lighthouse:recommended 
                     --collect.settings.chromeFlags="--no-sandbox"
```
