### ISSUE TITLE
Slack Notification with report?

### ISSUE THREAD

**Issue by regijorge** [GoogleChrome/lighthouse-ci#191]
Hi, is there any way to integrate with Slack to send audits reports?

**Comment by patrickhulce** [comment]
There is not. For now, we'd recommend piggy backing on whatever CI provider is running LHCI to surface slack notifications on failure. Or perhaps a companion project would be interested in taking the audit results and posting to slack :)

When #5 is finally tackled we might revisit this feature idea though!

**Comment by bennywong30** [comment]
@patrickhulce – we surfacing this, if we can send a score or report of the results to Slack or some sort of notifications to non-tech people.

**Comment by patrickhulce** [comment]
I'm not sure what you're asking @bennywong30 but we're not going to build support for this into LHCI at this time.

It shouldn't be too hard to roll yourself though after LHCI has run, use the `lhci upload --target=filesystem` and send the links to the [Slack API](https://api.slack.com/methods/chat.postMessage)
