### ISSUE TITLE
Any way to always have an assertion-results.json report?

### ISSUE THREAD

**Issue by stubar** [GoogleChrome/lighthouse-ci#193]
At the moment I am only seeing assertion-results.json when one of my metric errors.  I think this report could be very useful, for example I could use it to send out a slack message of our lighthouse score with every release.  

Is there a way of having it always written?

**Comment by DinakarC-practise** [comment]
I am with you @stubar I want the assertion-results to be printed irrespective of pass or fail, As of now we see only failed results in assertion-results.json. If there is any work done on this please share the details.

**Comment by stubar** [comment]
I'm currently just going to set everything to warn with no settings, this seems to guarantee assertion-results.json is always written.  I will then parse that and decide what error code to exit with myself.

**Comment by DinakarC-practise** [comment]
Hmm this might solve my issue for now. only passing warn

**Comment by patrickhulce** [comment]
We can do this behind a flag 👍

**Comment by DinakarC-practise** [comment]
Thanks @patrickhulce

**Comment by stubar** [comment]
Yes thanks very much for a quick response

**Comment by muhammad-saleh** [comment]
@patrickhulce I'm not sure if I'm doing anything wrong but I can't seem to get `assertion-results.json` to include passed assertions

If I changed the minScore for all the categories to be 1 lhci errors out and stores the result `assertion-results.json`, but other than that it doesn't

Version: 0.72

I run lhci with this command:
```
lhci autorun --collect.settings.chromeFlags="--no-sandbox" --settings=lighthouserc.json --includePassedAssertions
```

And this is my lighthouserc.json
```
{
  "ci": {
    "includePassedAssertions": true,
    "collect": {
      "settings": { "chromeFlags": "--no-sandbox" },
      "staticDistDir": "./out",
      "numberOfRuns": 1,
      "url": ["index.html"]
    },
    "assert": {
      "preset": "lighthouse:no-pwa",
      "assertions": {
        "link-name": "off",
        "tap-targets": "off",
        "legacy-javascript": "off",
        "categories.pwa": "off",
        "categories:performance": ["error", { "minScore": 0.8 }],
        "categories:accessibility": ["error", { "minScore": 0.8 }],
        "categories:seo": ["error", { "minScore": 0.8 }],
        "categories:best-practices": ["error", { "minScore": 0.8 }]
      }
    },
    "upload": {
      "target": "temporary-public-storage"
    }
  }
}
```

**Comment by patrickhulce** [comment]
@muhammad-saleh `includePassedAssertions` is part of the `assert` options. `--assert.includePassedAssertions`

**Comment by muhammad-saleh** [comment]
@patrickhulce Thank you!
