### ISSUE TITLE
Lighthouse CI Server UI blanks after few seconds (Ghostery)

### ISSUE THREAD

**Issue by ZyanKLee** [GoogleChrome/lighthouse-ci#195]
Hello,

I noticed that on Firefox 71 and 72 (at least) the CI server page blanks out a few seconds after it is being loaded. I could not reproduce this issue on Google Chrome and recent Safari browsers but did not test other browsers.

When looking at the developer tools, I can see that all `<div>`'s are suddenly deleted from the DOM, but there are no errors in the console nor any requests within the network listing.

Lighthouse CI Server is run as docker container (using your official docker image) in an AWS ECS cluster. In front of it an AWS Application ELB is doing the TLS offloading and proxying from its subdomain to the container port.

Do you have any idea why that may happen?

**Comment by patrickhulce** [comment]
Hm, I'm not sure why this would happen, and I'm not able to reproduce this behavior in Firefox 69 or 72 for LHCI 0.3.4, 0.3.7, or latest master.

By "blanks out" do you mean that you start to see the UI and *then* all the divs are deleted from the DOM? Is it possible there are any extensions that you are using with Firefox but not Chrome/Safari that could be doing this?

**Comment by ZyanKLee** [comment]
A plug-in might actually be responsible. I'll test that on Monday and
report back.
Thanks for the tip.

**Comment by ZyanKLee** [comment]
Hey @patrickhulce, thanks for the hint. I found the time today to disable and re-enable all my browser addons. The issue came back when I re-enabled Ghostery.

**Comment by patrickhulce** [comment]
Ah glad you found the source! This is an overreaching bug on Ghostery's part then. There are no ads, tracking scripts, or third-party javascript at all in the Lighthouse CI server let alone reason to have the entire DOM removed.
