### ISSUE TITLE
With docker kubernetes

### ISSUE THREAD

**Issue by manoj-mass** [GoogleChrome/lighthouse-ci#198]
Hi,
We are using docker + kubernetes in our devOps system and uses Jenkins to build images and deploy into containers.  Can we use lighthouse in such environment ? Do you have any documentation or examples available ?

**Comment by patrickhulce** [comment]
I'm not really sure how using docker for your deployments relates to your CI process. Have you already read the [getting started guide](https://github.com/GoogleChrome/lighthouse-ci/blob/master/docs/getting-started.md)?

From the docs, you're fine if... 

> Your project either: A) has a command that runs a web server with production-like assets. B) is a static site.

If you run `docker run my-app-server` and have it accessible on a port then you're fine, just specify that as your [--collect.startServerCommand](https://github.com/GoogleChrome/lighthouse-ci/blob/2fe16195dab6a8e84995bdc66397d5efc39a4917/docs/cli.md#starting-a-webserver).
