### ISSUE TITLE
Allow collect representative results on filesystem

### ISSUE THREAD

**Issue by pahan35** [GoogleChrome/lighthouse-ci#199]
My proposal is related to #137 or #142 

At this moment there are only 2 ways to upload results: `temporary-public-storage` and own LHCI server.

We'd like to save it as artifacts in our CI to be able to access them any time we want without our own LHCI server.

For this reason, we need to be able to store median or `representativeLhrs` to disk.

ATM there is no option for it.

Maybe it's time to add such target like `filesystem`?

Looks like we just need to store `urlMap` with paths to .json and .html files for each median report.

The only unclear moments are where to store it.

I like your idea to provide next API for filesystem `lhci upload --target=filesystem --filesystem-destination=path/to/folder`

If it allows saving urlMap file together with median .html report and .json data it'll cover my needs

**Comment by patrickhulce** [comment]
Thanks for filing! Yes, this is exactly what #142 will cover, so let's cover the feature set in that issue.
