### ISSUE TITLE
Budget assertions appear to be using bytes instead of kilobytes

### ISSUE THREAD

**Issue by darrenhebner** [GoogleChrome/lighthouse-ci#202]
👋Hello, I'm working on adding Lighthouse CI to a project. I'm attempting to add a some budget assertions, but I'm a bit confused by the unit that the assertions expect.

`"resource-summary:script:size": ["error", {"maxNumericValue": 7000}]`

^ In this example, the `maxNumbericValue` appears to be in bytes. Other lighthouse budget examples I've found seem to be in KB. Would you be able to clarify in the docs which unit Lighthouse CI expects?

Thanks!

**Comment by patrickhulce** [comment]
Thanks for filing @darrenhebner! If you're using the LHCI audit assertion format, the unit is bytes to be consistent with all other audit assertion `maxNumericValues` that operate on the raw numeric value reported by Lighthouse.

If you're using the [budgets.json format](https://developers.google.com/web/tools/lighthouse/audits/budgets) (`--budgets-file=budgets.json`) then the unit is in KB.

We'll add this to the assertion docs about budgets 👍

**Comment by darrenhebner** [comment]
Great, thanks for confirming!
