### ISSUE TITLE
Unable to run in Docker: Tracing.start wasn't found

### ISSUE THREAD

**Issue by mikemfleming** [GoogleChrome/lighthouse-ci#203]
I'm trying to run Lighthouse in a daily check against our production website but I'm not able to run it in a container due to this error. Here is how to replicate:
```
docker exec -it $(docker run -d -i node:10) /bin/bash

# then in Docker
npm i -g @lhci/cli
apt-get update
apt-get install chromium -y

lhci healthcheck
>>> ✅  .lighthouseci/ directory writable
>>> ✅  Configuration file found
>>> ✅  Chrome installation found

lhci collect --url https://google.com
```

The final command produces the following logs and this error:
```
root@080e77090732:/# lhci collect --url https://google.com
Running Lighthouse 3 time(s) on https://google.com
Run #1...failed!
Error: Lighthouse failed with exit code 1
    at ChildProcess.child.on.code (/usr/local/lib/node_modules/@lhci/cli/src/collect/lighthouse-runner.js:103:21)
    at ChildProcess.emit (events.js:198:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
Fri, 31 Jan 2020 20:37:47 GMT ChromeLauncher Waiting for browser.
Fri, 31 Jan 2020 20:37:47 GMT ChromeLauncher Waiting for browser...
Fri, 31 Jan 2020 20:37:48 GMT ChromeLauncher Waiting for browser.....
Fri, 31 Jan 2020 20:37:48 GMT ChromeLauncher Waiting for browser.....✓
Fri, 31 Jan 2020 20:37:48 GMT config:warn IFrameElements gatherer requested, however no audit requires it.
Fri, 31 Jan 2020 20:37:48 GMT status Connecting to browser
Fri, 31 Jan 2020 20:37:48 GMT status Resetting state with about:blank
Fri, 31 Jan 2020 20:37:48 GMT status Benchmarking machine
Fri, 31 Jan 2020 20:37:49 GMT status Initializing…
Fri, 31 Jan 2020 20:37:49 GMT status Resetting state with about:blank
Fri, 31 Jan 2020 20:37:49 GMT status Setting up network for the pass trace
Fri, 31 Jan 2020 20:37:49 GMT status Cleaning browser cache
Fri, 31 Jan 2020 20:37:49 GMT status Beginning devtoolsLog and trace
Fri, 31 Jan 2020 20:37:49 GMT method <= browser ERR:error Tracing.start
Fri, 31 Jan 2020 20:37:49 GMT status Disconnecting from browser...
Fri, 31 Jan 2020 20:37:49 GMT ChromeLauncher Killing Chrome instance 1940
Runtime error encountered: Protocol error (Tracing.start): 'Tracing.start' wasn't found
Error: Protocol error (Tracing.start): 'Tracing.start' wasn't found
    at Function.fromProtocolMessage (/usr/local/lib/node_modules/@lhci/cli/node_modules/lighthouse/lighthouse-core/lib/lh-error.js:132:19)
    at callback.resolve.Promise.resolve.then._ (/usr/local/lib/node_modules/@lhci/cli/node_modules/lighthouse/lighthouse-core/gather/connections/connection.js:123:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

[I tracked it down to this issue](https://github.com/GoogleChrome/lighthouse/issues/7246) which is frankly a little over my head. It recommends using this command:
```
docker run -itv ~/reports:/home/chrome/reports --cap-add=SYS_ADMIN justinribeiro/lighthouse
```
or even
```
wget https://raw.githubusercontent.com/jfrazelle/dotfiles/master/etc/docker/seccomp/chrome.json -O ~/chrome.json && \
docker run -itv ~/your-local-dir:/home/chrome/reports --security-opt seccomp=$HOME/chrome.json justinribeiro/lighthouse
```
They work on my machine but many CI systems do not allow the security-opt or SYS_ADMIN flags for security reasons so I am still unable to run this in my pipelines. From what I can tell there is no official Docker image and getting the one I linked to above to work requires relaxing some security protocols that my team can't do. 🙃

Where should I go from here?

**Comment by patrickhulce** [comment]
`Tracing.start wasn't found` is unrelated to SYS_ADMIN capabilities and means you're using the debian-compiled version of Chromium that has removed certain developer-specific parts of the codebase that makes it unusable for Lighthouse.

Did you have trouble using [our docker client image from the docs](https://github.com/GoogleChrome/lighthouse-ci/tree/master/docs/recipes/docker-client)?

**Comment by mikemfleming** [comment]
Hey @patrickhulce thanks for the quick response!

Installing google-chrome-stable resolved my issue, here are the commands I'm using for reference:

`docker exec -it $(docker run -d -i node:10) /bin/bash`
```
# set up key
wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
# set up repository
sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'

# install dependencies
apt-get update
apt-get install google-chrome-stable -y
npm i -g @lhci/cli

# validate installation
lhci healthcheck

# collect metrics and assert on them
lhci collect --url $MY_URL
lhci assert
```

To your question, I can't use anything that requires the --security-opt flag or SYS_ADMIN capabilities due to security constraints enforced by our CI system. For reference, we are using Bitbucket Pipelines for this. 

Thanks for pointing me in the right direction!

**Comment by patrickhulce** [comment]
> Installing google-chrome-stable resolved my issue

Great glad to hear it! 😃 

> To your question, I can't use anything that requires the --security-opt flag or SYS_ADMIN capabilities due to security constraints enforced by our CI system.

For others, this is a parallel concern that shouldn't be impacted by using our docker configuration. Our docker image and the reference steps listed above will face identical challenges with SYS_ADMIN capabilities or resorting to `--no-sandbox`. In the worst case that a provider prevents external images from receiving the same permissions that its own images receive (which appears to be the case for @mikemfleming) then the `RUN` commands from 

https://github.com/GoogleChrome/lighthouse-ci/blob/4a6c5eca609b4290852f050570177e9457162d56/docs/recipes/docker-client/Dockerfile#L7-L14

could be copy/pasted to your docker setup.
