### ISSUE TITLE
Audit always failing "Document does not have a valid rel=canonical"

### ISSUE THREAD

**Issue by mauriciabad** [GoogleChrome/lighthouse-ci#211]
The CI always fails the audit: [Document does not have a valid rel=canonical](https://web.dev/canonical). It fails because it points to a different domain.

Maybe the CI should ignore this rule, because the audit is not being tested in production. And adds it to the manual checks part when the url points to a different domain.
Another solution would be to add the site url in the lighthouserc.json file and fake when running lighthouse, instead of using localhost.

What do you think?

**Comment by patrickhulce** [comment]
I'm not sold on disabling this by default. 

If you're dynamically constructing the rel=canonical link then the domain issue won't be a problem and you'll benefit from all the other validation points this audit gives you. 

If you're statically defining the canonical link to your production URL then obviously it will fail so statically turn this assertion off in your lighthouserc at the same time :)

**Comment by mauriciabad** [comment]
OK, I'm fine with using relative paths, but [it's recommended to use absolute paths instead](https://stackoverflow.com/a/8467966/8662476).  

https://support.google.com/webmasters/answer/139066
> Use absolute paths rather than relative paths with the rel="canonical" link element.
> Use this structure:  https://www.example.com/dresses/green/greendresss.html
> Not this structure: /dresses/green/greendress.html

I've made it relative and I don't have the issue anymore, but this may not be the optimal solution.

**Comment by patrickhulce** [comment]
I'm not suggesting to use relative paths but saying that if the rel canonical link were *dynamically* constructed (i.e. via server-side logic or JS client-side) the absolute URL could trivially match the origin.

**Comment by mauriciabad** [comment]
Oh... I see! It makes sense.

Thanks.
