### ISSUE TITLE
Add an option to ignore query string on static resources

### ISSUE THREAD

**Issue by olsh** [GoogleChrome/lighthouse-ci#215]
We update the query string for each build for if the content of a static file was changed.
For instance, if the content of `styles.css?v=1` was updated, we update the query string, like this `styles.css?v=2`.

In this case, the lighthouse server considers these files as entirely different and produces many unnecessary differences on the compare page. Please see the attached.

![image](https://user-images.githubusercontent.com/3613592/74632899-83a4ee80-5171-11ea-82ca-b052735d97bd.png)
![image](https://user-images.githubusercontent.com/3613592/74633007-bd75f500-5171-11ea-9d93-24ecd3ded623.png)

It would be nice to have an option to ignore query strings for such cases.

**Comment by patrickhulce** [comment]
Great request @olsh! That would indeed be annoying if the query string doesn't change things 👍 We're working on bringing more customization to how this is handled too #154

**Comment by patrickhulce** [comment]
query strings will now be ignored in 0.4.0, fixed by #318, ref #119
