### ISSUE TITLE
docker-server docs Windows fix

### ISSUE THREAD

**Issue by wavemotionio** [GoogleChrome/lighthouse-ci#221]
Mentioning this here because it came up in a recent PR. I found that it took a little hacking about to get the example to work on Windows.  I didn't think it was worth a PR but mentioning it here for reference purposes in case anyone is struggling.

https://github.com/GoogleChrome/lighthouse-ci/tree/master/docs/recipes/docker-server. 

Windows Users:
When executing the run command, `--mount='source=lhci-data,target=/data'` to `--mount='source=lhci-data,target=\data'`

Also, not sure this was needed but it didn't seem hurt:
(lighthouserc.json) `"sqlDatabasePath": "/data/lhci.db"` to `"sqlDatabasePath": "lhci.db"`

**Comment by patrickhulce** [comment]
Thanks @wavemotionio this is definitely a better place to discuss :)

hm `"sqlDatabasePath": "lhci.db"` will use the current working directory (/usr/src/lhci) as the path to the database which isn't on the persistent data volume so I would expect the database to disappear. it's working as expected for you though?

those paths are inside the alpine-based docker container so the `/` *should* be working, I don't have much experience with docker on Windows though. this is after going through things [like this](https://rominirani.com/docker-on-windows-mounting-host-directories-d96f3f056a2c)?

**Comment by patrickhulce** [comment]
Just checking in for an update here @wavemotionio. Any chance you've gotten to try out the points above?

**Comment by wavemotionio** [comment]
Sorry not yet -should have sorted out this week.

**Comment by patrickhulce** [comment]
No worries, just feel free to chime back in here whenever you get a chance :)

**Comment by patrickhulce** [comment]
Considering this solved, feel free to reopen if you have a reproducible bug.
