### ISSUE TITLE
lhci client docker image is not up to date

### ISSUE THREAD

**Issue by xyngfei** [GoogleChrome/lighthouse-ci#222]
why the lhci client docker latest image version is 0.3.4?  
https://hub.docker.com/r/patrickhulce/lhci-client

anyone can help to update it to 0.3.8?

**Comment by patrickhulce** [comment]
The latest image is 0.3.7. That's the last time there were any changes made to the lhci client docker image. 

![image](https://user-images.githubusercontent.com/2301202/74952885-89dfd880-53c6-11ea-9755-c014f8c753df.png)

**Comment by patrickhulce** [comment]
#156 tracks automatically pushing the latest even if there were no changes.

**Comment by xyngfei** [comment]
when I tried to run the docker run <docker_name> --version, it shows 0.3.4 on the latest docker package.. 

![image](https://user-images.githubusercontent.com/17619539/74958451-edf4b200-5443-11ea-9d4e-c4739ea7dbe7.png)

**Comment by patrickhulce** [comment]
Ah sorry for the misunderstanding! Yeah we'll fix that ASAP 👍

**Comment by patrickhulce** [comment]
alright 0.3.8 should be pushed with `0.3.8` inside 👍
