### ISSUE TITLE
Ability to track Live URL without a commit

### ISSUE THREAD

**Issue by AaronLayton** [GoogleChrome/lighthouse-ci#225]
I have a use case where I would like to use the same system to periodically track against the Live URL of our websites.

Tracking against commits is great to catch I WE do anything stupid, but our clients have access to dashboards to uploads large GIFs, or to Google Tag Manager to add on multiple tags, or it may be that a currently integrated 3rd party tag publishes an update to their script by adding in an extra 2mb of library JS.

Is there a way I can use this system to capture those use cases?

**Comment by patrickhulce** [comment]
Thanks for filing @AaronLayton! What you're describing is exactly what we're tracking in https://github.com/GoogleChrome/lighthouse-ci/issues/5. 

Currently, it's a bit of work to do this without a repo as you would need to fake the complete build context.

Something like the below

```bash
export LHCI_BUILD_CONTEXT__CURRENT_HASH=$(node -e "new Date().getTime().toString(16).split('').reverse().join('')")
export LHCI_BUILD_CONTEXT__COMMIT_TIME=$(date --iso-8601=seconds)
export LHCI_BUILD_CONTEXT__CURRENT_BRANCH=master
export LHCI_BUILD_CONTEXT__COMMIT_MESSAGE="Periodic run "
export LHCI_BUILD_CONTEXT__AUTHOR="No one <noreply@example.com>"
export LHCI_BUILD_CONTEXT__AVATAR_URL="https://picsum.photos/id/237/200/200"
lhci ...
```

We'll continue tracking the first-class effort for production monitoring over in #5 though :)

**Comment by AaronLayton** [comment]
Awesome thanks @patrickhulce

**Comment by asci** [comment]
Did anyone tested this solution? My uploads still tied to a branch. Can I use this with `autorun`?
```sh
export LHCI_BUILD_CONTEXT__CURRENT_HASH=$(node -e "new Date().getTime().toString(16).split('').reverse().join('')")
```
should this use `-p` flag?

**Comment by patrickhulce** [comment]
Sorry @asci yes that's a typo should be `node -p`, also are you setting `LHCI_BUILD_CONTEXT__CURRENT_BRANCH` too? Just setting the hash won't affect the branch the commit is tied to.
