### ISSUE TITLE
Require puppeteer-core over puppeteer in puppeteer-manager.js

### ISSUE THREAD

**Issue by zecke** [GoogleChrome/lighthouse-ci#226]
The puppeteer package is difficult to manage in corporate networks. The puppeteer-core package was introduced without the chrome download. Please consider requiring puppeteer-core over puppeteer.

**Comment by patrickhulce** [comment]
Thanks for filing @zecke! We'll consider supporting either. In the meantime anyone having trouble with the Chromium download of `puppeteer` should be able to just disable that behavior with `PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1`

**Comment by zecke** [comment]
That's an option but it seems difficult to use in case of `bazelbuild/rules_nodejs`. AFAICT it's difficult to pass environment variables or a npmrc file to `npm_install`/`yarn_install`.

In my case requiring `puppeteer-core` and letting users decide if/how to get a matching version of chrome is the easiest.

**Comment by patrickhulce** [comment]
It doesn't respect `--action_env=PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1`?

And yes we already agree on the premise that supporting either is better.
