### ISSUE TITLE
Lighthouse Status "details" link not pointing to where I expect

### ISSUE THREAD

**Issue by mansona** [GoogleChrome/lighthouse-ci#229]
Hi folks 👋 first of all, thanks for the awesome tool 🎉 it's exactly what I am looking for and has the perfect mix of complexity and simplicity for what I like 😂 

I've just set up the system for the first time on a project (see the PR here: https://github.com/ember-learn/ember-website/pull/607) but when I click the "details" link beside the Lighthouse Status Check I am redirected to https://github.com/GoogleChrome/lighthouse-ci instead of what I expected, the actual build itself 🤔 

Am I missing something because the build doesn't have a "base build" yet because it's the PR that is introducing the system? Or is this working as expected?

**Comment by patrickhulce** [comment]
Thanks for filing @mansona! That's definitely unexpected it should be linking you to the comparison view on your LHCI server. I'll look into it ASAP :)

**Comment by patrickhulce** [comment]
Turns out this was actually a server-side issue with the GitHub App, it's been restarted now and rerunning the build should fix this without any need to update `@lhci/cli` 👍

**Comment by mansona** [comment]
wow thanks @patrickhulce that's a really quick turnaround on this 🎉 you're an absolute star 🌟
