### ISSUE TITLE
@lhci/server mysql runs.lhr column TEXT too small

### ISSUE THREAD

**Issue by jalerg** [GoogleChrome/lighthouse-ci#236]
I am running a fresh new collect + upload on a local mysql setup, new database, first run, first project, and I get this error: 

(removed paths)

```
> lhci upload                                                                                                                                1 ↵  11:16:06
Saving CI project ************* (d1094908-64e4-423a-8058-666cc2ad187a)
Saving CI build (e1165cf2-79e5-4dda-aec4-f381daed9ca0)
Saved LHR to http://localhost:3000 (dd305e5c-8839-4760-9e32-7e2de06e91a7)
Saved LHR to http://localhost:3000 (fa9877e7-a869-4975-a826-da3ea8bafd87)
Saved LHR to http://localhost:3000 (e1fc5bfb-99a2-4ed2-b148-a06681deeaa7)
Error: Unexpected status code 500
  <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>SyntaxError: Unexpected token o in JSON at position 1<br> &nbsp; &nbsp;at JSON.parse (&lt;anonymous&gt;)<br> &nbsp; &nbsp;at *************************************/node_modules/@lhci/server/src/api/storage/storage-method.js:252:60<br> &nbsp; &nbsp;at Array.map (&lt;anonymous&gt;)<br> &nbsp; &nbsp;at Function.createStatistics (*************************************/node_modules/@lhci/server/src/api/storage/storage-method.js:252:38)<br> &nbsp; &nbsp;at async SqlStorageMethod.sealBuild (*************************************/node_modules/@lhci/server/src/api/storage/sql/sql.js:364:36)<br> &nbsp; &nbsp;at async *************************************/node_modules/@lhci/server/src/api/routes/projects.js:180:7</pre>
</body>
</html>

    at ApiClient._convertFetchResponseToReturnValue (****************/.nvm/versions/node/v12.8.1/lib/node_modules/@lhci/cli/node_modules/@lhci/utils/src/api-client.js:55:21)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async runLHCITarget (****************/.nvm/versions/node/v12.8.1/lib/node_modules/@lhci/cli/src/upload/upload.js:354:3)
    at async run (****************/.nvm/versions/node/v12.8.1/lib/node_modules/@lhci/cli/src/cli.js:91:7)%
```

A little investigation shows the runs generate reports too large, the lhr json files are about 315K characters long, while the MYSQL->runs.lhr table is set to TEXT with a max length for this type of 65K characters.

For reference, this is a very old app I am rewriting with a LOT of issues, thus the reports are just immense.

The json payload is getting truncated and the `sealBuild()` method fails trying to parse it here:
https://github.com/GoogleChrome/lighthouse-ci/blob/af9cdddfd7c87ef8d48a706c96193a72b132aefe/packages/server/src/api/storage/storage-method.js#L250

I altered my local mysql table field type to MEDIUMTEXT (max size 16MB) and it uploaded/worked perfectly fine. 

I'll submit a PR with the change, I didn't find any other issue opened

**Comment by jalerg** [comment]
I just noticed this is fixed in the code already for mysql

https://github.com/GoogleChrome/lighthouse-ci/blob/af9cdddfd7c87ef8d48a706c96193a72b132aefe/packages/server/src/api/storage/sql/migrations/20191008-initial.js#L45

and merged to master 4 days ago, but not published to npm just yet
https://github.com/GoogleChrome/lighthouse-ci/pull/233

Closing

**Comment by patrickhulce** [comment]
Thanks for filing @jalerg! Yeah sorry just noticed this the other day. I was hoping it hadn't hit anyone yet since the docker image is by far the most popular way to run the server, but glad you figured it out :)
