### ISSUE TITLE
Circle CI - unable to connect to chrome?

### ISSUE THREAD

**Issue by Tonyhliu** [GoogleChrome/lighthouse-ci#241]
When running `lhci autorun` in Circle CI, it seems to fail saying can't connect to Chrome.

![image](https://user-images.githubusercontent.com/16828863/76479332-a6b96b80-63c8-11ea-969c-b380c43df78b.png)

Has anyone encountered this before?
![image](https://user-images.githubusercontent.com/16828863/76479340-afaa3d00-63c8-11ea-866e-d658923592aa.png)

**Comment by patrickhulce** [comment]
Yep! See https://github.com/GoogleChrome/lighthouse-ci/tree/master/docs/recipes/docker-client#--no-sandbox-issues-explained for a deeper explanation of `--no-sandbox` tradeoffs.

tl;dr - if you're only testing a site that you completely control, just throw `--collect.settings.chromeFlags=--no-sandbox` onto your LHCI options.

**Comment by Tonyhliu** [comment]
Thanks @patrickhulce , that worked!
