### ISSUE TITLE
Feature request to allow overriding assertions in categories

### ISSUE THREAD

**Issue by trevordmiller** [GoogleChrome/lighthouse-ci#242]
For example, if I have the config below with a static site that renders in a server I don't have control over, my `categories:best-practices` fails with a score of `0.93` because the `uses-http2` rule failed, even though I have `"uses-http2"` set to `"off"`). To get around this, I am currently using lowering my `categories:best-practices` to `0.93`.

```diff
{
  "ci": {
    "collect": {
      "staticDistDir": "."
    },
    "assert": {
      "assertions": {
        "categories:performance": ["error", {"minScore": 1.00}],
        "categories:accessibility": ["error", {"minScore": 1.00}],
-       "categories:best-practices": ["error", {"minScore": 0.93}],
+       "categories:best-practices": ["error", {"minScore": 1.00}],
        "categories:seo": ["error", {"minScore": 1.00}],
+       "uses-http2": "off"
      }
    }
  }
}
```

**Comment by patrickhulce** [comment]
Thanks for filing @trevordmiller! I definitely understand this isn't ideal, but we also don't want to over infer to lead the results too far from stock Lighthouse. https://github.com/GoogleChrome/lighthouse-ci/issues/208 is a bit related and covers some of my concerns about inferring collect options based on assert options and vice-versa.

I think the best solution here is to skip the audit in Lighthouse settings

```diff
{
  "ci": {
    "collect": {
      "staticDistDir": ".",
+     "settings": {"skipAudits": ["uses-http2"]}
    },
    "assert": {
      "assertions": {
        "categories:performance": ["error", {"minScore": 1.00}],
        "categories:accessibility": ["error", {"minScore": 1.00}],
        "categories:best-practices": ["error", {"minScore": 1.00}],
        "categories:seo": ["error", {"minScore": 1.00}],
+       "uses-http2": "off"
      }
    }
  }
}
```

The danger of automatically removing audits that are "off" from the category is that several users *only* assert on the categories and if they did that without asserting on the audits the category assertion would become meaningless. Perhaps there's room for an option like `--skipAssertionsOfMissingAudits` or something so you only have to specify the `skipAudits` piece without also doing `"uses-http2": "off"`?

**Comment by trevordmiller** [comment]
@patrickhulce Thanks for the info, `skipAudits` is exactly what I was looking for but didn't see!
