### ISSUE TITLE
"Lighthouse Error" after extending dashboard view to >=100 builds

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse-ci#248]
At least that's what i'm seeing sometimes on the lhci canary instance.

https://lhci-canary.herokuapp.com/app/projects/ffb1f9c0-465f-4dc5-9407-1ed7e06ac7c4/dashboard?runUrl=http%3A%2F%2Flocalhost%3APORT%2Fapp%2Fprojects%2Flighthouse-viewer

What I saw:

1. I tried MAX and got an error
1. I tried 100 and got an error
1. I tried 50 and it worked
1. I tried 100 again and it worked.
1. I tried MAX again and it worked.

Soooooooo it fails intermittently. 🤷‍♂ 

Since it works now I can't get a screenshot. Sorry.

**Comment by patrickhulce** [comment]
Thanks this is a known issue. The first time a build shows up in that report after a version update the statistics will need to be computed for it. When you request ~100-200 at once it takes awhile and the underpowered heroku free tier times out.

For our situation specifically I'm not sure how it can be solved other than just preventing you from rendering with so many new builds at once. The alternative is precomputing the build statistics on version migration but doing that for *all* builds will definitely also hit the free tier timeout of the service starting up, so we're back to on-the-fly computation.

I think the nicest UX would be something along the lines of "we've started computing those results, try again in a minute" or something and just keep you on the lower limit.

If this wasn't on the first load, then there's something different going on I want to investigate :)

**Comment by paulirish** [comment]
> I think the nicest UX would be something along the lines of "we've started computing those results, try again in a minute" or something and just keep you on the lower limit.

yeah i like this. Just changing the message to this is a great UX upgrade. :)

> When you request ~100-200 at once it takes awhile and the underpowered heroku free tier times out.

presumably the nonfreetier would just take a while but definitely succeed?

**Comment by patrickhulce** [comment]
> presumably the nonfreetier would just take a while but definitely succeed?

presumably, yes. a beefy enough server would take a while but eventually succeed depending on your gateway timeout configuration, not sure how beefy it needs to be or how many it could handle at once. but to get through 250 in a typical timeout configuration it'd need to be able to process ~4 builds per second which isn't *too* crazy to ask
