### ISSUE TITLE
New Metric First-Input-Delay 

### ISSUE THREAD

**Issue by DinakarC-practise** [GoogleChrome/lighthouse-ci#256]
Our team came across this metric called FID and google is grading websites based on FCP and FID. We wanted to have this metric in lighthouse too. I cross-checked the default configs for audits to see if this metric is available or not. https://web.dev/fid/ 
Kindly please provide an update on this metric.

**Comment by patrickhulce** [comment]
Thanks for filing @DinakarC-practise ! The lab corollary to this metric (Max Potential First Input Delay) is already in Lighthouse and current Lighthouse CI. 

Unfortunately, it's actually being hidden in Lighthouse 6.0 and will no longer be visible in the upcoming 0.4.0 release of Lighthouse. You can still assert against the value in Lighthouse CI but it just won't be displayed in the server or report UI.
