### ISSUE TITLE
multiple CI configurations make duplicate LHRs per hash

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse-ci#26]
thanks to node 10 and node 12... 
https://travis-ci.org/paulirish/mojibar-web/builds/601044688

we got two LHRs from the same hash
https://lhci-canary.herokuapp.com/app/projects/d819a1f6-2630-4ee8-a451-95e369fec825/builds/59f0de64-68ab-41b4-ae0c-430bb3028f2c

kinda confusing
![image](https://user-images.githubusercontent.com/39191/67254009-91e73600-f42f-11e9-9b72-27aa15eb988b.png)

**Comment by patrickhulce** [comment]
this is addressed in the [getting started guide](https://github.com/GoogleChrome/lighthouse-ci/blob/master/docs/getting-started.md#run-lighthouse-ci-script) AFAIK there's no way for us to know it's being run at the same time

the only fix I see on our side is just reject builds for a hash after the first one, but I'm not sure if that's actually better. the integrity of a build as a related unit prevents us from merging the runs later
