### ISSUE TITLE
Upgrading to Newer Version

### ISSUE THREAD

**Issue by ggennrich** [GoogleChrome/lighthouse-ci#261]
I might be completely misunderstanding something, but I don't see any documentation around how to update the server out on GCP to the latest version of this project. Could you please elaborate or point me to where this is? Thanks and love the work you are doing with this!

**Comment by patrickhulce** [comment]
Are you using the docker server k8s recipe for GCP? Just update the version tag on the image line in your lhci-pod.yml to the version you want to use and restart the pod.

https://github.com/GoogleChrome/lighthouse-ci/blob/39d45ea7a369c88adb11c63f27e78ac3330cde9b/docs/recipes/docker-server/kubernetes/lhci-pod.yml#L10

**Comment by ggennrich** [comment]
Thanks @patrickhulce ! That makes a lot of sense.
