### ISSUE TITLE
Improve server setup documentation

### ISSUE THREAD

**Issue by cjimmy** [GoogleChrome/lighthouse-ci#269]
It took me a lot of fiddling to get the LHCI server running on GKE. I wanted to document some of them here so that we can discuss improvements to the documentation, and to potentially help others struggling to set it up as well. 

### 1. Creating cluster from gcloud cli failed
When I tried to create the cluster with gcloud in the docker-server [documentation](https://github.com/GoogleChrome/lighthouse-ci/blob/master/docs/recipes/docker-server/README.md) I got this error.
```
# Create our Kubernetes cluster for LHCI
gcloud container clusters create lhci-cluster --num-nodes=1
>>>
ERROR: (gcloud.container.clusters.create) ResponseError: code=400, message=Project "$[PROJECT_ID]" has no network named "default".
```
I'm starting off with no other clusters in my GKE. I suspect that the presets in the gcloud tool don't match the web console, and adding a few more flags would fix this, but I don't know GKE well enough. I had to manually create a cluster named `lhci-server` via the console, and edit the `default-pool` to have 1 node instead of 3, and with the smallest acceptable machines.

### 2. Need to connect Shell to Kubernetes
After I got past that, I tried the next line.
```
kubectl apply -f ./kubernetes/lhci-data-claim.yml
>>>
error: unable to recognize "./kubernetes/lhci-data-claim.yml": Get http://localhost:8080/api?timeout=32s: dial tcp [::1]:8080: connect: connection refused
```
There's no Kubernetes in play, and maybe this is a result of the first issue by not creating it via gcloud cli. But to use kubectl, I had to copy/paste the command to Connect to `lhci-server`
```
gcloud container clusters get-credentials lhci-server --zone $COMPUTE_ZONE --project $PROJECT_ID
```

### 3. What to do with the External IP
This is minor, and perhaps obvious if you arrived here via the rest of the documentation, but I think a little redundancy wouldn't hurt. IMO, it's worth bringing the user full circle on what to do with the external IP of the lhci-server you just set up – and that is to plug it into the prompt when running `lhci wizard`. I suggest adding a sentence and linking to the Getting Started [page](https://github.com/GoogleChrome/lighthouse-ci/blob/master/docs/getting-started.md).

### 4. Suggest to users to hide server URL in secret
Many of these repos will be public repos, and since the server URL (without any additional steps taken for auth) will be open to the public, perhaps you could suggest to users to hide the base URL behind a secret (along with everything else).
Github Action example below:
```
...
      - name: run Lighthouse CI
        env:
          LHCI_TOKEN: ${{ secrets.LHCI_SERVER_TOKEN }}
          LHCI_SERVER_URL: ${{ secrets.LHCI_SERVER_URL }}
        run: |
          npm install -g @lhci/cli@0.3.x
          lhci autorun --upload.serverBaseUrl="$LHCI_SERVER_URL" || echo "LHCI failed!"
```

**Comment by patrickhulce** [comment]
Thanks very much for sharing your experience @cjimmy! Responses inline below :)


> I'm starting off with no other clusters in my GKE

Was it in a pre-existing project used for any other gcloud products? All new gcloud projects should be created with a `default` network automatically, so I'm suspecting that the default network was deleted when other non-GKE parts of the project were configured. Perhaps we just add the caveat that if you've configured other products in the project your flags might differ (and list the most common ones to edit?) There also seem to be some anecdotal reports out there that people have deleted the default network without realizing or intending to, so worth adding to a troubleshooting section.

> maybe this is a result of the first issue by not creating it via gcloud cli. But to use kubectl, I had to copy/paste the command to Connect to lhci-server

Ah yeah, probably an interplay between mixing the UI and the CLI. Thanks for this command we'll add it to a "Troubleshooting" part of the doc!

> This is minor, and perhaps obvious if you arrived here via the rest of the documentation, but I think a little redundancy wouldn't hurt

Yep great idea on reminding with a link 👍 

> perhaps you could suggest to users to hide the base URL behind a secret (along with everything else).

I think relying on the obscurity of the URL is a bit dangerous, especially if you want links to results accessible from anywhere useful, but point taken on improved documentation for how to secure the server better! 👍

**Comment by cjimmy** [comment]
Hey Patrick – 
Re: `default` network – That must be it. Another colleague must have deleted/modified the default network. 

Re: Hiding server URL – fair point. With status checks enabled, the reports are still accessible per PR, without having to expose the Dashboard.

Thanks for the quick troubleshooting explanations, and more importantly, for making this! It's a real time saver.

**Comment by patrickhulce** [comment]
Thanks @cjimmy! We can leave this issue open to track adding those improvements :)
