### ISSUE TITLE
main thread work diff doesn't maintain identity

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse-ci#27]
![image](https://user-images.githubusercontent.com/39191/67254055-cc50d300-f42f-11e9-921b-48073eb85567.png)

https://lhci-canary.herokuapp.com/app/projects/d819a1f6-2630-4ee8-a451-95e369fec825/builds/59f0de64-68ab-41b4-ae0c-430bb3028f2c

**Comment by patrickhulce** [comment]
this has been fixed, just haven't redeployed to heroku yet (63303bab2f988712baa851333ef9cad5e01cf665) #9
