### ISSUE TITLE
delta units in milliseconds

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse-ci#28]
looks like sometimes these deltas are in seconds.. othertimes in milliseconds

![image](https://user-images.githubusercontent.com/39191/67254611-c27c9f00-f432-11e9-80e5-e2e2f97a08b0.png)

![image](https://user-images.githubusercontent.com/39191/67254623-d32d1500-f432-11e9-80b1-b7a6c695d0f5.png)

Currently I feel like it should report in milliseconds... always?
`-0.1s` just feels pretty obtuse.  and there's already the % delta threshold filter.

but i don't know for sure.. just an initial impression.

**Comment by patrickhulce** [comment]
intuitively I agreed with you and this is the way it was, but this was changed based on @yuinchien feedback and design for everything to be seconds

anecdotally, the ms starts to take up a lot of real estate on a small bar for the large metrics like TTI, and we do express everything other than FID in seconds so I kinda get it 🤷‍♂

**Comment by patrickhulce** [comment]
We've decided to go with all ms everywhere

**Comment by patrickhulce** [comment]
fixed by 7c1e5ff6969f67cd66a4b00d8b9ce414a7408abb
