### ISSUE TITLE
Default Upload Location

### ISSUE THREAD

**Issue by safwansamla** [GoogleChrome/lighthouse-ci#286]
What's the default location of temporary storage? I ran a test via travis and it passed. How do I view the report?

**Comment by patrickhulce** [comment]
@safwansamla it prints the link out in the logs

![image](https://user-images.githubusercontent.com/2301202/80288833-4a07db00-8700-11ea-8768-aeba483ca1bf.png)


you can also use the [github app](https://github.com/GoogleChrome/lighthouse-ci/blob/master/docs/getting-started.md#github-status-checks) to get the link directly on the PR

![image](https://user-images.githubusercontent.com/2301202/68001177-0b9dd180-fc31-11e9-8091-ada8c6e50a9b.png)

**Comment by safwansamla** [comment]
Thank you!

One follow up. I am getting URL is not defined error, although I have specified it in the configuration file. The issue only happens in travis, it works fine locally. Here are the files.

1. [lhci configuration](https://github.com/safwansamla/Lighthouse-CI-Demo/blob/master/lighthouserc.json)
2. [Travis configuration](https://github.com/safwansamla/Lighthouse-CI-Demo/blob/master/.travis.yml)
3. [Travis error](https://travis-ci.org/github/safwansamla/Lighthouse-CI-Demo/builds/679514427)

**Comment by patrickhulce** [comment]
You're probably using an older node version. I don't see any explicit installation of node and you need at least Node 10 to run lighthouse.

**Comment by safwansamla** [comment]
That worked. Thank you!
