### ISSUE TITLE
"worse" "+0 kb"

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse-ci#29]
lol rounding is hard.

![image](https://user-images.githubusercontent.com/39191/67254838-1e93f300-f434-11e9-8625-807513f23886.png)

https://lhci-canary.herokuapp.com/app/projects/d819a1f6-2630-4ee8-a451-95e369fec825/builds/a204633f-ab48-4c26-930a-813c4e05c8d0

i suppose this is related to https://github.com/GoogleChrome/lighthouse-ci/issues/28

**Comment by patrickhulce** [comment]
I guess we show the bytes when it's 0?
