### ISSUE TITLE
dom-size preset threshold is very aggressive

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse-ci#295]
Its expects a dom-size score of `>= `, but that translates to <= 470  total DOM elements in the body.

480 will FAIL the run, which seems too aggressive. 

1. I think the minScore preset here should be `>= 0.5` for now.
1. It feels like we should recalibrate the scoring for dom-size. The last time it was touched it was made very aggressive. It feels a bit out of whack to me. Srug. https://github.com/GoogleChrome/lighthouse/commit/03c275394e92e57ce4629f07d0579028d4211f2a#diff-01cdf25666df0cb74ac618908fbc78a2

**Comment by paulirish** [comment]
Side note: shouldn't **all** the minScore presets be `>= 0.9` since we consider that to be "passing" ?

**Comment by patrickhulce** [comment]
> 480 will FAIL

Oof, yeah I disabled this assertion completely on my sites. Mostly because I think it's a kinda arbitrary and unhelpful audit that is just nagging without concrete evidence of a real problem.

> I think the minScore preset here should be >= 0.5 for now.

How about removing it from recommended entirely?

> Side note: shouldn't all the minScore presets be >= 0.9 since we consider that to be "passing"

Yeah that's fair, I'll add it to #119 👍

**Comment by paulirish** [comment]
> > I think the minScore preset here should be >= 0.5 for now.
> 
> How about removing it from recommended entirely?
> 

WFM!

**Comment by patrickhulce** [comment]
fixed by #318
