### ISSUE TITLE
Feature request(Server): Plot results per branch, not per branch:url pair

### ISSUE THREAD

**Issue by motiko** [GoogleChrome/lighthouse-ci#299]
Our use case is such that every build gets its own unique URL.  
In this case plotting per URL doesn't make much sense.
Two possible solution:  
- Per project config. Something like: Ignore target URL / Plot per branch only
- Pass `LHCI_BUILD_CONTEXT__TARGET_URL` to override actual target

Any thoughts? Would you be open to accept a PR with proposed changes?

**Comment by patrickhulce** [comment]
This is what [`--urlReplacementPatterns`](https://github.com/GoogleChrome/lighthouse-ci/blob/master/docs/cli.md#upload) is for. By default it only replaces ports and UUID-like parts of a URL, but you could use it to replace the entire URL if you'd like (or just the part that is changing).

Something like the below (but I haven't tested it)
`lhci upload --urlReplacementPatterns=s#.*#http://myfixedurl.com#`

**Comment by motiko** [comment]
Thank you!! It works.
I guess documentation could be improved with an example. 
I was looking at this param but couldn't realise this is what I'm looking for.
