### ISSUE TITLE
Tooltip component

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse-ci#30]
On mac the chrome/system tooltip (that shows `[title]` takes like 1 second to display. (iirc, it's twice as slow as windows/linux for no good reason)

regardless, i think we want a JS tooltip component so that the values behind [title] are a lot more accessible. we hide some good stuff in there.

i found these without looking very hard

- https://react-hint.js.org/ doesn't feel right to me, personally.
- https://ajainvivek.github.io/preact-fluid/#tooltip would be nice without the animation
- https://react-tooltip.netlify.com/ i dig this style. i love the mouse tracking thing (tho i'm not 100% that we want it here.. but maybe?)
- https://codepen.io/fuggfuggfugg/pen/mqdBH what can you say. the man's got taste

**Comment by patrickhulce** [comment]
Linked this issue to #9 now 👍

**Comment by egsweeny** [comment]
Fully bike shedding, but agree that while the mouse tracking thing is cool I'm not sure we want it in the UI. I like the second one (preact-fluid) without animation. :)
