### ISSUE TITLE
How to run without git

### ISSUE THREAD

**Issue by ha-douken** [GoogleChrome/lighthouse-ci#304]
**Documentation**

> Upload
> […]
> Build Context
> When uploading to the Lighthouse CI server, the CLI will attempt to automatically infer the build context such as git hash, […] if you're running without a git repo […] you can control the build context yourself.
> 
> The following environment variables override the inferred build context settings.

**Expectation**
* I can use `upload` without a git repo
* This is done by setting (at least) the LHCI_BUILD_CONTEXT__CURRENT_HASH manually

**Test**
```
LHCI_BUILD_CONTEXT__GIT_REMOTE="git@github.com:GoogleChrome/lighthouse-ci.git"
LHCI_BUILD_CONTEXT__GITHUB_REPO_SLUG="GoogleChrome/lighthouse-ci"
LHCI_BUILD_CONTEXT__CURRENT_HASH="e7f1b0fa3aebb6ef95e44c0d0b820433ffdd2e63"
LHCI_BUILD_CONTEXT__ANCESTOR_HASH="78bafdcaf40e204c0d0b81b90bb76b9aa5834e11"
LHCI_BUILD_CONTEXT__COMMIT_TIME="2019-11-29T16:43:39-05:00"
LHCI_BUILD_CONTEXT__CURRENT_BRANCH="master"
LHCI_BUILD_CONTEXT__COMMIT_MESSAGE="Daily run of Lighthouse"
LHCI_BUILD_CONTEXT__AUTHOR="Patrick Hulce <patrick.hulce@example.com"
LHCI_BUILD_CONTEXT__AVATAR_URL="https://example.com/patrickhulce.jpg"
LHCI_BUILD_CONTEXT__EXTERNAL_BUILD_URL="https://my-jenkins.example.com/jobs/123"
npx lhci autorun
```

**Result**
`Error: Unable to determine current branch with \'git rev-parse --abbrev-ref HEAD\'`

**Comment by patrickhulce** [comment]
You're missing `export` to make the environment variable available to the node subprocess.

```sh
➜ cat > test.sh <<EOF
FOO=bar
node -e "console.log(process.env.FOO)"

export FOO_2=bar
node -e "console.log(process.env.FOO_2)"
EOF
➜ bash test.sh
undefined
bar
```
