### ISSUE TITLE
Geo location config to run audit from different locations

### ISSUE THREAD

**Issue by DinakarC-practise** [GoogleChrome/lighthouse-ci#311]
Hey, folks, I wanted to run audits from different Geo-Locations by adding an agent. Is that config available in lighthouse-ci or we have to run via any other tools??

Please point me to that. 
Thanks.

**Comment by patrickhulce** [comment]
Lighthouse CI runs on whatever machine you install it on. If you'd like to run in other locations, you can spin up machines in those locations.

A library that spins up infrastructure and runs Lighthouse on it, is not in scope for Lighthouse CI.

**Comment by DinakarC-practise** [comment]
Sounds good for me. Thank you very much
