### ISSUE TITLE
lighthouserc typescript config 

### ISSUE THREAD

**Issue by jimbyo** [GoogleChrome/lighthouse-ci#312]
Hi is there a way of using a lighthouserc.ts instead of lighthouserc.js?

**Comment by patrickhulce** [comment]
Nope, we don't really make types available though so I'm curious what you were hoping to leverage with typescript for this config?

**Comment by jimbyo** [comment]
Oh, it's just someone reviewing my code was wondering if it was possible at all. We typically use typescript instead of js. Thank you for answering!

**Comment by connorjclark** [comment]
If you happen to make a `.d.ts` for the config, it'd be great if you could submit it to `@types/` :)
