### ISSUE TITLE
Timeout problem

### ISSUE THREAD

**Issue by jlieb10** [GoogleChrome/lighthouse-ci#313]
Hello, I've been working on integrating lighthouse-ci on the frontend for The Guardian on the following branch/WIP PR: https://github.com/guardian/dotcom-rendering/pull/1427

I've had to debug a number of issues to do with the way PM2 logs and Github Actions interact, but now I am past those bugs. It seems Lighthouse is running but somehow Chrome is inexplicably hanging and the test cannot complete. Please see the partial log here:
```
...
Thu, 14 May 2020 15:49:05 GMT status Gathering: FontSize
Thu, 14 May 2020 15:49:05 GMT status Gathering: EmbeddedContent
Thu, 14 May 2020 15:49:05 GMT status Gathering: RobotsTxt
Thu, 14 May 2020 15:50:05 GMT status Gathering: TapTargets
Thu, 14 May 2020 15:50:05 GMT status Gathering: Accessibility
Thu, 14 May 2020 15:51:06 GMT status Disconnecting from browser...
Thu, 14 May 2020 15:51:06 GMT ChromeLauncher Killing Chrome instance 3350
Runtime error encountered: Waiting for DevTools protocol response has exceeded the allotted time. (Method: Runtime.evaluate)
LHError: PROTOCOL_TIMEOUT
    at Timeout.setTimeout [as _onTimeout] (/opt/hostedtoolcache/node/10.15.3/x64/lib/node_modules/@lhci/cli/node_modules/lighthouse/lighthouse-core/gather/driver.js:409:21)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
LHCI failed!
```

Full log is available here: https://github.com/guardian/dotcom-rendering/runs/675070496?check_suite_focus=true

Can you advise on what is going on and how I might continue to debug?

**Comment by patrickhulce** [comment]
This is https://github.com/GoogleChrome/lighthouse/issues/6512 rearing its head. Unfortunately there's nothing we can really do on the Lighthouse side when Chrome hangs other than retry it (which in Lighthouse CI we're already doing up to 3 times).

If it's always stopping on Accessibility, it's possible there's a bug in axe-core that causes it to hang on your page and as a temporary workaround you could skip the accessibility category.

```json5
{
  "ci": {
    "collect": {
      "settings": {
        // Don't run accessibility category
        "onlyCategories": ["performance", "seo", "best-practices", "pwa"],
      }
    }
  }
}
```

Hope this helps!

**Comment by patrickhulce** [comment]
I'm going to go ahead and close this issue as there's no further action to be taken without Lighthouse CI, but feel free to chime in over on https://github.com/GoogleChrome/lighthouse/issues/6512 with more details.
