### ISSUE TITLE
How can I visit the public URL on Google Cloud

### ISSUE THREAD

**Issue by DarcyXf** [GoogleChrome/lighthouse-ci#316]
The below paragraph from doc: "getting-started.md#configure-lighthouse-ci" caused me a doubt.

> NOTE: As the name implies, this is temporary and public storage. If you're uncomfortable with the idea of your Lighthouse reports being stored on a public URL on Google Cloud, skip to the add assertions or Lighthouse CI server steps. Reports are automatically deleted 7 days after upload.

When I collect lighthouse results by public storage rather not host my own lighthouse CI Server,
Where can I visit the reports?

**Comment by patrickhulce** [comment]
> Where can I visit the reports?

The link is printed in the build logs and you can use the [GitHub integration](https://github.com/GoogleChrome/lighthouse-ci/blob/master/docs/getting-started.md#github-status-checks) to get the link to the report directly posted to every PR.

**Comment by DarcyXf** [comment]
Thanks!

**Comment by DarcyXf** [comment]
> > Where can I visit the reports?
> 
> The link is printed in the build logs and you can use the [GitHub integration](https://github.com/GoogleChrome/lighthouse-ci/blob/master/docs/getting-started.md#github-status-checks) to get the link to the report directly posted to every PR.

Thanks!!
