### ISSUE TITLE
Provide an option to make upload failure an error in autorun

### ISSUE THREAD

**Issue by Hexcles** [GoogleChrome/lighthouse-ci#325]
Currently, if upload fails during autorun, lhci logs a *warning* and exits with 0 (provided that everything else succeeds). This hides a regression in configurations from us. It'd be great to provide an option to make this an error instead of a warning.

**Comment by patrickhulce** [comment]
Thanks for filing @Hexcles! Awesome to see web platform tests using LHCI :)

We do this by default to not be noisy if the server goes down or isn't reachable temporarily, etc, but I definitely see the value 👍
