### ISSUE TITLE
env vars as configuration

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse-ci#34]
while setting up lhci on https://github.com/paulirish/mojibar-web i managed to run into the "you dont have access to secret env vars on PRs from clones" bug like 3 times. partly because i'm dumb, admittedly.

so by default, the `LHCI_TOKEN` and `LHCI_GITHUB_TOKEN` would be expected to be there. but since they're not present on contributor PRs, then both uploading and status checks are disabled. and that sucks quite a bit.

i wonder if we have other options?

**Comment by patrickhulce** [comment]
If you want to get LHCI data on your repo from arbitrary pull requests, you're already exposing the ability for anyone to put arbitrary data into your LHCI server, so you can just treat `LHCI_TOKEN` as public and make it non-secret. The only thing it lets you do is upload data, which is exactly what you're wanting everyone to be able to do.

GitHub is the trickier problem whose solution is much more heavy handed and why I didn't want to commit to GH status checks :) Right now we're on par with solutions like our bundlesize who just can't be used on PRs without write access. The only way around this I'm aware of is to level up to the full GH integration that requires a running service to essentially verify that this status check come from an approved source such that the token doesn't need to live in builds anymore.
