### ISSUE TITLE
Error: Must provide token for LHCI target

### ISSUE THREAD

**Issue by kaihendry** [GoogleChrome/lighthouse-ci#344]
I did see https://github.com/GoogleChrome/lighthouse-ci/issues/144
I'm not using `serverBaseUrl`. So I am a little confused where I am going wrong!

https://travis-ci.org/github/kaihendry/ltabus/jobs/695606273#L282

https://github.com/kaihendry/ltabus/blob/master/.travis.yml#L34-L39
I'm using the lighthouse ci action here: https://github.com/kaihendry/ltabus/blob/master/.github/workflows/main.yml

Many thanks,

**Comment by patrickhulce** [comment]
Thanks for filing @kaihendry!

You have defined Lighthouse CI twice. You don't need to run it both with travis *and* with GitHub actions. If the Github action is working for you, then feel free to use that and delete your travis config.

As for what's wrong. The travis config is using the arguments on the incorrect command.

If you don't want to use autorun, it should be
```
        - npm install -g @lhci/cli@0.3.x
        - lhci collect --start-server-command="PORT=3000 go run ." --url=http://localhost:3000/
        - lhci upload --target=temporary-public-storage
```

PS v0.4.0 with Lighthouse 6.0 has been released if you want to check that out :)

**Comment by kaihendry** [comment]
Thank you Patrick, I've opted to use the treosh/lighthouse-ci-action@v3 but I am running into this issue with showing the results: https://github.com/treosh/lighthouse-ci-action/issues/60
