### ISSUE TITLE
How to get desktop version report?

### ISSUE THREAD

**Issue by phanhongphucit** [GoogleChrome/lighthouse-ci#345]
I always get the report with mobile version result by this command:
lhci autorun --collect.url=https://google.com

How can I get both mobile and desktop result?

Thanks!

**Comment by phanhongphucit** [comment]
I found that add the options to the lighthouse:
  ci: {
    collect: {
        settings: {
            chromeFlags: '--no-sandbox',
            emulatedFormFactor: 'desktop'
        }
    }

**Comment by patrickhulce** [comment]
Yep those settings should get you desktop results @phanhongphucit 👍 

#138 tracks support for running both on the same CI server which is pretty difficult right now.
