### ISSUE TITLE
GitHub status check score description doesn't use median run when target=lhci

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/lighthouse-ci#348]
From https://github.com/GoogleChrome/lighthouse-ci/issues/235#issuecomment-644868456

Currently just the last LHR wins for the summary description

https://github.com/GoogleChrome/lighthouse-ci/blob/5380a234aaf445ae068c1dde8842eea361919916/packages/cli/src/upload/upload.js#L415-L429

**Comment by jflayhart** [comment]
Anything I can do to help with this? Would be awesome if we could release this along with whatever else is in master (not sure what your release strategy is).

**Comment by patrickhulce** [comment]
if you want to try a PR for it, be my guest! :) otherwise I'll get to it next week

**Comment by jflayhart** [comment]
Hmm ok. I just started looking into this a second ago and immediately noticed that my comment at the time was referring to `temporary-public-storage` target, didn't realize it applied to both though.

Looks like we will need to handle for both upload targets!

**Comment by patrickhulce** [comment]
Hm, there must be something else going on then. The only bug I see is that the *link* for the LHCI target is linking to the incorrect report the labels and links for `temporary-public-storage` should be using the representative ones.

https://github.com/GoogleChrome/lighthouse-ci/blob/5380a234aaf445ae068c1dde8842eea361919916/packages/cli/src/upload/upload.js#L271-L284

**Comment by patrickhulce** [comment]
Actually now that you're mentioning it, I don't see any bug at all here. The only place where we don't use the representative run is for LHCI target *link* but that doesn't matter because the links are all identical for all the runs because the median is always surfaced there.

Is it possible that the last one actually was the median of all the *metrics*?

**Comment by jflayhart** [comment]
Even so, then why is it passing with a median perf score of 58 when I set assertions to fail <=60? [My point](https://github.com/GoogleChrome/lighthouse-ci/issues/235#issuecomment-644868456) was that I am seeing Github check/link not adding up to my score assertions. How exactly is it all calculated then?

Are you saying this is expected behavior? That's fine I guess, just want to understand why 🤔

**Comment by jflayhart** [comment]
Here's an example where it fails, but it's not getting the median failed score either:

```
categories.performance failure for minScore assertion
 
        expected: >=0.6
        found: 0.59
 
      all values: 0.46, 0.48, 0.53, 0.54, 0.59
```

again, im operating under the assumption that assertions determine which scores should be weighed by the median score. So maybe i'm wrong, but then it's confusing that a passing score of `58` is shown when I asserted that it must be >=60.

**Comment by patrickhulce** [comment]
It's really hard without the lighthouse reports themselves to answer if this is working as intended. One important thing to note here...

The `median` selection algorithm for assertions is *not* the same as the median report selection algorithm for the GitHub status check and it's definitely possible for them not to match. 

Hypothetical example:

Run 1 - Perf 60, FCP 4000, TTI 6000
Run 2 - Perf 61, FCP 1000, TTI 10000
Run 3 - Perf 62 FCP 3990, TTI 5900

Run 2 will be used for the median performance score in assertions.
Run 1 will be used for the "representative run" (it has the median TTI and is only 10ms away from median FCP).

The disconnect in the LHCI server UI and the github status checks with assertion summary is understood, undesirable, and on the backlog for improvement (related #232 #100)

**Comment by jflayhart** [comment]
Ok thanks, I think your explanation clears up what I'm seeing and that it's not necessarily desired behavior but it is currently expected 👍

**Comment by patrickhulce** [comment]
Thanks @jflayhart! I'll go ahead and close this out since #232 (assertions UI) is largely what blocks syncing all of this up.
