### ISSUE TITLE
Add a configurable display name for URLs

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/lighthouse-ci#349]
split from discussion on https://github.com/GoogleChrome/lighthouse-ci/pull/342#issuecomment-638688638 

It'd be neat to have a project-wide configuration of friendly URL labels like "Homepage (desktop)" or "Checkout" instead of the full ugly query string URL.

**Comment by paulirish** [comment]
is this a dupe of #343 ? 😛

**Comment by patrickhulce** [comment]
Seems like it 👍
