### ISSUE TITLE
lighthouse-ci ran against a live site

### ISSUE THREAD

**Issue by michellbrito** [GoogleChrome/lighthouse-ci#350]
Hey there. Thanks for building this tool.

I’m curious to know if lighthouse-ci can be used run against a live site instead of it running against PRs? 

Thanks

**Comment by patrickhulce** [comment]
Yep! #342 will add better support for this but there's also some discussion in https://github.com/GoogleChrome/lighthouse-ci/issues/5#issuecomment-591578507 on how to get it done today.
