### ISSUE TITLE
make ancestorHash optional

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse-ci#36]
from https://github.com/GoogleChrome/web.dev/pull/1757

![image](https://user-images.githubusercontent.com/39191/67738045-74374500-f9ca-11e9-8316-cb604c11cab6.png)

https://travis-ci.org/GoogleChrome/web.dev/builds/604191888#L634

1. should it only run on the PR build?
1. since this is fatal i wonder if it should check this before starting collect? :/

**Comment by patrickhulce** [comment]
the project has set a git depth of 1 in travis yaml so we won't know what the merge commit is

options I see in decreasing order of attractiveness:

- We make the ancestor hash optional and just lose the fidelity in these situations (it would compare to most recent master build instead)
- We document that you need to support a higher git depth if you want to run on push builds
- We try to fetch and get the commits from origin
- We check all these conditions in collect (I dislike this strongly because it means you can't just use the assert flow with temporary public storage)

**Comment by mathiasbynens** [comment]
https://github.com/GoogleChrome/lighthouse-ci/commit/d422cff3c5c05a220490a570da77e56be39a9ec7 closed this issue by making `ancestorHash` optional, but then https://github.com/GoogleChrome/lighthouse-ci/commit/1769433de41cd0bb73807c709e0d227e4707e112 added the `healthcheck` command which includes [a check for `getAncestorHash().length > 0`](https://github.com/GoogleChrome/lighthouse-ci/blob/0d5544f359ec28935aef521ff8fa79e015553f50/packages/cli/src/healthcheck/healthcheck.js#L44-L48).

I haven’t dug too deeply but I think we might be hitting this check here: https://travis-ci.com/v8/v8.dev/jobs/255422510#L524

**Comment by patrickhulce** [comment]
Somewhat between a rock and a hard place with this one. It is indeed optional if you run collect/assert/upload manually as was the flow at the time but healthcheck was requested and designed to help catch common setup problems like this before you got too far into the process. 

What would be your expectation here?

1. Healthcheck doesn't actually fail anything as part of autorun, just warn.
2. Healthcheck makes the fatal ancestorHash check opt-in but would still fail other misconfigurations.
3. Other?

**Comment by mathiasbynens** [comment]
Note that I am not explicitly running `lhci healthcheck` — I hit the issue when using `lhci autorun` like so: https://github.com/v8/v8.dev/pull/284/files#diff-354f30a63fb0907d4ad57269548329e3 

I have no strong expectation for any of those options in particular — it’s just that I wouldn’t have expected any errors. I was mostly trying to follow the docs to get `lhci` set up, and was surprised by this error.

**Comment by patrickhulce** [comment]
Right, sorry should have clarified.

What would be your expectation when trying to setup LHCI but something in the environment is not configured to allow us to link ancestor builds together?

- Just a warning, let me upload them even if I won't get the correct diffs
- A fatal error, I want to know there's something to be fixed
- Other?

**Comment by patrickhulce** [comment]
Sidenote: it only failed to determine the ancestor hash on the *branch* build in that travis job, but the *PR* build succeeded. I'm suspecting that the branch builds lack the git history of master that would enable an ancestor to be computed. Maybe that's another situation and solution we add to the [troubleshooting guide](https://github.com/GoogleChrome/lighthouse-ci/blob/a6258dc30b946be3c6b97f5c28cc1708746c8408/docs/troubleshooting.md#lhci-server-isnt-finding-the-correct-base-branch-ancestor) on this topic?
