### ISSUE TITLE
Document how an array of urls interacts with the puppeteerScript flag

### ISSUE THREAD

**Issue by jimbyo** [GoogleChrome/lighthouse-ci#361]
Hi!

I've been trying to set up a puppeteer-script to bypass authentication. However, I am having some trouble figuring out how the puppeteerScript flag interacts with the URL list I have.
**lighthouserc.json**

```
      "puppeteerScript": "puppeteer-login-script.js",
      "url": [
        "http://127.0.0.1:8181/",
        "http://127.0.0.1:8181/about",
        "http://127.0.0.1:8181/contact",
        "http://127.0.0.1:8181/donate",
        "http://127.0.0.1:8181/get-started",
        "http://127.0.0.1:8181/community-library",
        "http://127.0.0.1:8181/privacy-policy",
        "http://127.0.0.1:8181/teach",
        "http://127.0.0.1:8181/terms",
        "http://127.0.0.1:8181/thanks"
      ]
    },
```

I can get it to work with one URL, but I think my config currently runs the Puppeteer script before each URL collection and keeps trying to log in even though I am already logged in. Is there a way I make it so that the `lighthouserc` config will only run the script on certain URLs. Or do I need to handle it in the `puppeteer-login-script`

**Comment by patrickhulce** [comment]
Thanks for filing @jimbyo! You'll need to handle this in your script. The script function is invoked with the collection options and current URL it's about to test.

```js
module.exports = (browser, {url, options}) => {
  if (url !== 'http://localhost/page-that-needs-the-login') return;
  // ...
}
```

docs to make this clearer would be welcome! :)

**Comment by jflayhart** [comment]
I agree docs would be good because when this CI tool first came out I spent a good bit of time figuring this out in particular.

@patrickhulce Should we make this a recipe or just a snippet in the docs?

**Comment by jflayhart** [comment]
For example one of my solutions was to get around this fact that the browser session seems to persist cookies and thus once you're logged in once, you're logged in the rest of the runs:

```
// lighthouserc.js
urls: [
  'localhost/login', // have to test this first before cookie auth or else it never gets hit
  'localhost/',
  'localhost/contact',
  'localhost/about',
  ...
]
```

```
// puppeteer script
module.exports = async (browser, context) => {
  const page = await browser.newPage()
  try {
    if (!context.url.includes('/login')) {
       // do login stuff through UI once
    }
  await page.close()
  catch (e) {
    // handle error gracefully
  }
}
```

**Comment by patrickhulce** [comment]
A snippet in the docs near the description of `puppeteerScript` option would be great, or perhaps even a complete configuration example in the "Examples" section? A recipe feels like overkill here.

When using puppeteer, the browser is kept open across all URLs so if you're keeping state in `cookies` then everything should be remembered between URLs. If you're using anything other than cookies though, you might have trouble. There's no real way to support `sessionStorage` because new tabs are created and other storage types are cleared by Lighthouse in between runs so you'll need to use `--collect.settings.disableStorageReset` as well.

Basic flow with puppeteer script.

```
|- puppeteer launches browser
|- LHCI runs the puppeteerScript
|- LHCI runs Lighthouse on URL A, run 1
|- LHCI runs Lighthouse on URL A, run 2
|- LHCI runs Lighthouse on URL A, run n
|- LHCI runs the puppeteerScript
|- LHCI runs Lighthouse on URL B, run 1
|- LHCI runs Lighthouse on URL B, run 2
...

**Comment by jflayhart** [comment]
Ah yes great point, I def use `disableStorageReset: true`

**Comment by jimbyo** [comment]
@patrickhulce Thanks for the answer! I got it working now. 

I think it might be helpful to clarify that a general puppeteer script won't work with the lighthouse config, I thought that a standard puppeteer script could just log into the website, and that the lighthouse config would just use that instance. I didn't know that using the parameters and structure below was necessary.

/**
 * @param {puppeteer.Browser} browser
 * @param {{url: string, options: LHCI.CollectCommand.Options}} context
 */

Luckily there was an issue showing how to write the puppeteer script, so I was fine.  https://github.com/GoogleChrome/lighthouse-ci/issues/321

**Comment by patrickhulce** [comment]
> it might be helpful to clarify that a general puppeteer script won't work with the lighthouse config

This shouldn't be the case. You can definitely use a custom config along with puppeteer. What gave you this impression?

> I thought that a standard puppeteer script could just log into the website, and that the lighthouse config would just use that instance.

This is what happens :)

> I didn't know that using the parameters and structure below was necessary.

Do you have suggestions on how to improve the [documentation for this setting](https://github.com/GoogleChrome/lighthouse-ci/blob/805c417b9c26bb9eea35d65884b4b93f00cb0699/docs/configuration.md#puppeteerscript)? AFAICT, it offers nearly that identical JSDoc of what the parameters and structure are so I'm not sure how to make it any clearer :/
