### ISSUE TITLE
Custom Audits

### ISSUE THREAD

**Issue by TheMcMurder** [GoogleChrome/lighthouse-ci#364]
Does this project support passing down custom audits to lighthouse?

https://github.com/GoogleChrome/lighthouse/tree/master/docs/recipes/custom-audit

shows passing a custom audit as part of the configuration. I was wondering if I could put the necessary configuration in `lighthouserc.js` along with the `ci` options and have those values be used by lighthouse or if they are overridden by `lighthouse-ci`

**Comment by patrickhulce** [comment]
Yep, refer to [the docs example for a custom Lighthouse config](https://github.com/GoogleChrome/lighthouse-ci/blob/805c417b9c26bb9eea35d65884b4b93f00cb0699/docs/configuration.md#custom-lighthouse-config).

Feel free to chime back in here if you run into a specific issue getting it to work as documented.

**Comment by TheMcMurder** [comment]
Thanks for the clarification. The mistake I made was trying to do it like this:

```js
{
  ci: {...},
  assert: {...},
  // custom lighthouse config here
  extends: 'lighthouse:default',
  ...
}
```

When the correct configuration was

```js
// lighthouserc.js
{
  ci: {
    configPath: './pathToCustomConfig.js'
  },
  assert: {...},
}
```
```js
// pathToCustomConfig.js
{
  // custom lighthouse config here
  extends: 'lighthouse:default',
  ...
}
```
Thank you for the rapid response, It is working as documented, sorry I missed the documentation I was looking for.
