### ISSUE TITLE
Add to README how to contribute

### ISSUE THREAD

**Issue by m048tn** [GoogleChrome/lighthouse-ci#379]
Hi!

It might be better to include in the README how to contribute, like in the [lighthouse](https://github.com/GoogleChrome/lighthouse#how-do-i-contribute).

**Comment by patrickhulce** [comment]
Thanks for filing @m048tn! We already have [CONTRIBUTING.md](https://github.com/GoogleChrome/lighthouse-ci/blob/daac2d164e30e31b1ae4992392f41611cfee8929/CONTRIBUTING.md. Do you want to see its content merged in the main README.md or just a link to it?

A link to it would be a good first contribution if anyone is interested :)

**Comment by m048tn** [comment]
What I wanted to tell you this time was that a link to CONTRIBUTING.md!

So I want to challenge this issue!
Would you assign me, please?

**Comment by patrickhulce** [comment]
That'd be great thanks @m048tn! :)
