### ISSUE TITLE
Use the reporting front end with existing lighthouse reports

### ISSUE THREAD

**Issue by zdelagrange** [GoogleChrome/lighthouse-ci#380]
I currently have a lighthouse implementation where I am using selenium (not puppeteer) to handle authentication of my application. I do this by passing off the chrome debugging port to the lighthouse cli and generating a report via the lighthouse cli. 

I really like the lighthouse server reporting for historic runs and want to Impress My Boss with the beautiful front end.

Is there a way to bypass the CI portion of this app and submit already created reports to the server for my viewing pleasure?

Is there a way to run arbitrary scripts to spawn chrome sessions (ie don't use puppetteer but other tools)?

**Comment by patrickhulce** [comment]
> Is there a way to bypass the CI portion of this app and submit already created reports to the server for my viewing pleasure?

Sure, you can "fake" the collection by writing your LHR JSON files to `.lighthouseci` folder in a form of `${Date.now()-lhr.json` and then only run `lhci upload`.

> Is there a way to run arbitrary scripts to spawn chrome sessions (ie don't use puppetteer but other tools)?

I'm not sure what you mean here. You could hypothetically use the `puppeteerScript` to connect selenium to the launched browser instead if that's what you're asking. It's just a function that returns a promise you can do whatever you want.

**Comment by zdelagrange** [comment]
Thanks, that was helpful.

>I'm not sure what you mean here. You could hypothetically use the puppeteerScript to connect selenium to the launched browser instead if that's what you're asking. It's just a function that returns a promise you can do whatever you want.

I think I'm wondering if this is arbitrary execution or if it is a hook into node. ie could I run a python script here or use executable in my path? I have a robust page object framework and test harness written in python that then calls lighthouse for the report. I honestly might be better off writing a simple puppeteer script to handle my auth, but to be completely honest I'm not sold on puppeteer since I believe in the WebDriver w3c specification and this just adds an extra layer of maintenance for my project.

**Comment by patrickhulce** [comment]
It's a hook into node, but you're free to execute whatever you want inside that hook

```bash
lhci collect --puppeteerScript=custom-script.js --url=http://example.com
```

**custom-script.js**
```js
// See https://nodejs.org/api/child_process.html#child_process_asynchronous_process_creation
const spawn = require('child_process').spawn;

/**
 * @param {puppeteer.Browser} browser
 * @param {{url: string, options: LHCI.CollectCommand.Options}} context
 */
module.exports = async (browser, context) => {
  // you only care about these arguments for the port to use for the already open Chrome
  const port = browser.wsEndpoint().match(/:(\d+)/)[1]

  return new Promise(resolve => {
    const customChildProcess = spawn('python', ['--the', '--python', '--arguments', port]);
    customChildProcess.on('exit', resolve);
  });
};
```

**Comment by zdelagrange** [comment]
Thanks for the prompt and detailed response!
