### ISSUE TITLE
Github App privacy policy/terms of service

### ISSUE THREAD

**Issue by nwalters512** [GoogleChrome/lighthouse-ci#386]
My company is working on getting Lighthouse in CI set up - kudos for the awesome tool! We'd like to install the [Lighthouse CI](https://github.com/apps/lighthouse-ci) GitHub app to get status checks on our PRs. However, before doing so, we need to review the terms of service and privacy policy of the app. The app page says the following:

> Lighthouse CI is provided by a third-party and is governed by separate terms of service, privacy policy, and support documentation.

However, we haven't been able to locate any of those documents. Would you be able to provide an explicit terms of service and privacy policy for the app and the data it collects?

**Comment by patrickhulce** [comment]
Good question on the clarity of which specific privacy policy/ToS documents apply, I don't want to steer you wrong so I can get back to you on that. At the very least, Firebase is used as a data processor under GDPR terminology so you could start with...

https://firebase.google.com/terms/
https://cloud.google.com/terms/
https://cloud.google.com/terms/data-processing-terms

In terms of the practical aspects as of today...

The GitHub App itself does not request any permission other than read/write access to statuses and there are no backend processes that actively fetch from the GitHub API. The only data given to the GitHub App API goes through a single endpoint (invoked by `lhci upload`) that receives the following for each commit...

https://github.com/GoogleChrome/lighthouse-ci/blob/ebe3419bd602f94c3e0024f3efc8a69f5331f11e/packages/cli/src/upload/upload.js#L146-L155

That data is essentially proxied directly to the GitHub API and not stored.

If you're curious about non-GitHub app related aspects of Lighthouse CI, the `temporary-public-storage` storage mechanism is a little different and obviously stores some user data (the Lighthouse report itself) in a publicly accessible location. A mapping of the repository slug to the latest lighthouse report URL on the base branch is also saved to support diffing. All data shared with these services will always be auditable in `packages/cli/src/upload/upload.js` as well :)
