### ISSUE TITLE
Feature request: Name/Alias for urls in collection

### ISSUE THREAD

**Issue by vividhsv** [GoogleChrome/lighthouse-ci#387]
Current in collect we can only specify urls like so
```
ci: {
  collect: {
      url: [
        `${AUT_BASE_URL}/alerts/1234`,
        `${AUT_BASE_URL}/alerts/5678`,
        `${AUT_BASE_URL}/alerts/9012`,
      ]
  }
}
```

It would be great if we could name these urls as well.

Example:
```
ci: {
  collect: {
      url: [
        {name: '/alerts/id - high', url:`${AUT_BASE_URL}/alerts/1234`},
        {name: '/alerts/id - medium', url:`${AUT_BASE_URL}/alerts/5678`},
        {name: '/alerts/id - low', url:`${AUT_BASE_URL}/alerts/9012`},
      ]
  }
}
```
Also dashboard should show the names instead of the url. This way we could change the underlying url with different id in collection but still use the same name to compare results in dashboard.

**Comment by patrickhulce** [comment]
Thanks for filing @vividhsv I added your comment to https://github.com/GoogleChrome/lighthouse-ci/issues/343 which already tracks this
