### ISSUE TITLE
NO_FCP error while running lighthouse CI in gitlab

### ISSUE THREAD

**Issue by RitikPatni** [GoogleChrome/lighthouse-ci#398]
Attaching the logs I found from Gitlab. 

> lhci autorun --upload.target=temporary-public-storage --collect.settings.chromeFlags="--no-sandbox" || echo "LHCI failed!"
✅  .lighthouseci/ directory writable
✅  Configuration file found
✅  Chrome installation found
Healthcheck passed!
Automatically determined ./dist as `staticDistDir`.
Set it explicitly in lighthouserc.json if incorrect.
Started a web server on port 35203...
Running Lighthouse 3 time(s) on http://localhost:35203/index.html
Run #1...failed!
Error: Lighthouse failed with exit code 1
    at ChildProcess.child.on.code (/usr/local/lib/node_modules/@lhci/cli/src/collect/node-runner.js:103:21)
    at ChildProcess.emit (events.js:198:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
{
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/77.0.3865.90 Safari/537.36",
  "environment": {
    "networkUserAgent": "",
    "hostUserAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/77.0.3865.90 Safari/537.36",
    "benchmarkIndex": 1074
  },
  "lighthouseVersion": "6.0.0",
  "fetchTime": "2020-08-04T12:27:44.146Z",
  "requestedUrl": "http://localhost:35203/index.html",
  "finalUrl": "http://localhost:35203/index.html",
  "runWarnings": [
    "Something went wrong with recording the trace over your page load. Please run Lighthouse again. (NO_FCP)"
  ],
  "runtimeError": {
    "code": "NO_FCP",
    "message": "Something went wrong with recording the trace over your page load. Please run Lighthouse again. (NO_FCP)"
  },

**Comment by patrickhulce** [comment]
Thanks for filing @RitikPatni!

If LHCI is throwing this error, it means that the page did not contain any content (we already automatically retry 3 times).

Usually this happens when the page is very broken or errors. Check that your page successfully renders content in your test environment in a browser before using LHCI on it (or upload the `./dist` folder so you can try it out locally).

**Comment by RitikPatni** [comment]
@patrickhulce I tried it again locally and then in CI and it started working. It was probably because of some error in bundle. Thanks for the quick response.
