### ISSUE TITLE
Lighthouse-ci results differs from lighthouse itself

### ISSUE THREAD

**Issue by thiagosanches** [GoogleChrome/lighthouse-ci#400]
Hi everyone, it seems that are some issue with lighthouse-ci results in comparison with lighthouse itself. When I ran `lhci autorun` it gives me an error related to `NO_FCP`, but if I use **the same** lighthouse that is installed through lhci (that one stored on `node_modules` folder), it works properly:
![image](https://user-images.githubusercontent.com/5191469/89417143-abc6e080-d704-11ea-981d-afd61a80c13a.png)
![image](https://user-images.githubusercontent.com/5191469/89418077-f432ce00-d705-11ea-845b-086937f7edb5.png)

If I ran using `lhci autorun` it gives me the `NO_FCP` error. I also tried to use the `--no-sandbox` flag but got no luck.
![image](https://user-images.githubusercontent.com/5191469/89417843-a0c08000-d705-11ea-94d6-5fa4d5b1537a.png)

Do you have any idea? Am I missing something?
Thanks.

**Comment by patrickhulce** [comment]
If LHCI is throwing this error, it means that the page did not contain any content when it was loaded.

Usually this happens when the page is very broken or errors and it can be intermittent. It looks like LHCI worked fine on several of your earlier URLs, is there anything specific to this page that might mean it doesn't paint content quickly?

If it just takes too long to render you can try increasing the `--max-wait-for-fcp` option of Lighthouse.

**Comment by thiagosanches** [comment]
Hi @patrickhulce thanks for your reply.
I'm adding as following:

`settings: {
chromeFlags: "--no-sandbox --headless --max-wait-for-fcp=45000",
},`

But it seems that is not reflecting to the current execution, got the same error.

**Comment by patrickhulce** [comment]
@thiagosanches it's not a chrome flag or LHCI flag, so using it would look like

```js
module.exports = {
    ci: {
        collect: {
            url: [],
            settings: {
              maxWaitForFcp: 45000,
              chromeFlags: "--no-sandbox --headless",
            },
      }
}
```

or

`lhci autorun --collect.settings.max-wait-for-fcp=45000`

it's not a silver bullet though, given any thought to?

>  It looks like LHCI worked fine on several of your earlier URLs, is there anything specific to this page that might mean it doesn't paint content?

**Comment by thiagosanches** [comment]
Ops, sorry I didn't know that it was a property inside `settings` object.

> it's not a silver bullet though, given any thought to?
Yes, the site is loading properly and even if I ran against (and only) lighthouse it gives me the result. 
Let's say the website:https://www.coca-colaukraine.com

**Comment by patrickhulce** [comment]
Thanks for sharing the URL!

I can't reproduce that behavior though :/
![image](https://user-images.githubusercontent.com/2301202/89445477-d6bb2f80-d718-11ea-940e-53a33f34c202.png)

**Comment by thiagosanches** [comment]
Hey @patrickhulce it might be something related to my node version, I was using node 12, I switched to node 10 and it's working:
![image](https://user-images.githubusercontent.com/5191469/89534532-776a2780-d7cb-11ea-9528-2b3bcc484286.png)

```
nvm use 10.21.0
Now using node v10.21.0 (npm v6.14.4)
google-chrome --version
Google Chrome 84.0.4147.105 
```

**Comment by thiagosanches** [comment]
Closing this ticket since the node 10 version fixed the issue.
