### ISSUE TITLE
`No differences` CSS is off center

### ISSUE THREAD

**Issue by exterkamp** [GoogleChrome/lighthouse-ci#41]
The no differences page CSS is sad.
![image](https://user-images.githubusercontent.com/6392995/68368360-c2e08f80-00ec-11ea-81ee-6e314f2ea642.png)

![image](https://user-images.githubusercontent.com/6392995/68368341-b5c3a080-00ec-11ea-9973-18a1c2147a2d.png)

**Comment by patrickhulce** [comment]
I'm not able to reproduce this. Link?

![image](https://user-images.githubusercontent.com/2301202/68402471-ffd67180-0140-11ea-986a-e4f2f166398a.png)

**Comment by exterkamp** [comment]
https://lhci-canary.herokuapp.com/app/projects/3e1ad4e7-689b-4340-83f4-409c84308f89/builds/a7d7f911-c792-46a7-9239-8ff6dc00f8fd?baseHash=84bd4f97966ed408146762a1bdb5789014cd4f72

**Comment by patrickhulce** [comment]
perfect thanks! 👍
