### ISSUE TITLE
Is there a way to get build diff url?

### ISSUE THREAD

**Issue by kmcrawford** [GoogleChrome/lighthouse-ci#411]
I would like to post the build diff url to our slack after a build complete, but I either need the build diff url or the build.id to construct the url myself.  Is there a way to get that information?

https://github.com/GoogleChrome/lighthouse-ci/blob/master/packages/cli/src/upload/upload.js#L456

**Comment by patrickhulce** [comment]
Yep! The links to each build diff are written to the `.lighthouseci/links.json` file after every upload.

https://github.com/GoogleChrome/lighthouse-ci/blob/0c5db087c9f9c279dbaa2d86197f2c7948810e22/packages/cli/test/cli.test.js#L240-L248
