### ISSUE TITLE
build diff url

### ISSUE THREAD

**Issue by kmcrawford** [GoogleChrome/lighthouse-ci#412]
I would like to post the build diff url to our slack after a build complete, but I either need the build diff url or the build.id to construct the url myself.  Is there a way to get that information?

https://github.com/GoogleChrome/lighthouse-ci/blob/master/packages/cli/src/upload/upload.js#L456

**Comment by patrickhulce** [comment]
duplicate https://github.com/GoogleChrome/lighthouse-ci/issues/411
