### ISSUE TITLE
Something went wrong with recording the trace over your page load. Please run Lighthouse again. (NO_LCP)

### ISSUE THREAD

**Issue by RitikPatni** [GoogleChrome/lighthouse-ci#413]
I'm constantly getting this error in lighthouse CI running in Headless Chrome in Gitlab CI. The same is working fine when tried locally. Due to this issue the performance number is always 0. Attaching a screenshot for reference

![image](https://user-images.githubusercontent.com/16117262/90103984-13160d80-dd61-11ea-8417-f048260c6c40.png)

**Comment by RitikPatni** [comment]
Here is my Gitlab CI config for reference

```
build stage:
  image: cypress/browsers:node10.16.0-chrome77
  stage: build
  script:
    - npm install -g @vue/cli@latest
    - npm install
    - npm run build
    - npm install -g @lhci/cli@0.4.x
    - lhci autorun --collect.settings.chromeFlags="--no-sandbox" || echo "LHCI failed!"
```

**Comment by patrickhulce** [comment]
Thanks for filing @RitikPatni! We're tracking this over in https://github.com/GoogleChrome/lighthouse/issues/11180

**Comment by brendankenny** [comment]
@RitikPatni from that report and your config, it also looks like you're running Chrome 77, which is too old to support LCP (Lighthouse v6.2 has a more helpful error message to alert about this). You'll need at least Chrome 79 to get an LCP value.

**Comment by RitikPatni** [comment]
@brendankenny Thanks it works with a new image
