### ISSUE TITLE
PSI fails with Unicode/UTF-8 error

### ISSUE THREAD

**Issue by helmecke** [GoogleChrome/lighthouse-ci#419]
PSI Cronjob fails for site containing emoji.

```
2020-08-19T11:20:18.939Z - PSI collection failure for Production: Incorrect string value: '\xF0\x9F\x91\x80"}...' for column 'lhr' at row 1
```

U+1F440 | 👀 | \xf0\x9f\x91\x80 | EYES

```
$ lhci server --version
0.4.4
```

**Comment by patrickhulce** [comment]
Thanks for filing @helmecke! It looks like this error is coming from the database and I would expect this error to apply for all URLs with unicode in them whether it's PSI collected or not.

What storage mechanism are you using?

**Comment by helmecke** [comment]
Hi @patrickhulce, thank you for the fast reply.

I'm using `mysql`, collation and character set are utf8_general_ci	and utf8.

**Comment by patrickhulce** [comment]
Looks like it's a [MySQL limitation](https://stackoverflow.com/questions/10957238/incorrect-string-value-when-trying-to-insert-utf-8-into-mysql-via-jdbc) with 4-byte unicode characters. 

Any of those solutions work for you? 


You *might* also need to add some MySQL settings to your server connection config depending on which path you take to solve it. 

ref https://github.com/sequelize/sequelize/issues/7110

```js
module.exports = {
  ci: {
    server: {
      storage: {
        storageMethod: 'sql',
        sqlDialect: 'mysql',
        sqlDialectOptions: {
          // may need properties here
        },
        sequelizeOptions: {
          define: {charset: 'utf8mb4'} // maybe this is what works? unclear
        }
      },
    },
  },
};
```

Either way whatever configuration you need to get it working, we'd love to add to the docs if you can share :)

**Comment by helmecke** [comment]
Switching database charset to `utf8mb4` and collation to `utf8mb4_unicode_ci` worked.Thank you very much.
