### ISSUE TITLE
Server hang up issue on build seal request

### ISSUE THREAD

**Issue by gauthampughaz** [GoogleChrome/lighthouse-ci#421]
I am facing the same issue as #117. But I am unable to solve it with the resolution provided. Mine is a unique case where I upload 144 LHRs on every build to the LHCI server. I use an ubuntu-based docker container to generate the results and then upload them to the LHCI server running on the RHEL server which also hosts the docker container. I face no problem till the LHRs are uploaded and even the build gets sealed sometimes. But, it throws up the following error

```
FetchError: request to {lhciserver.com}/v1/projects/{token}/builds/{buildHasH}/lifecycle failed, reason: socket hang up
    at ClientRequest.<anonymous> (.../node_modules/@lhci/cli/node_modules/node-fetch/index.js:133:11)
    at ClientRequest.emit (events.js:198:13)
    at Socket.socketOnEnd (_http_client.js:435:9)
    at Socket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

When I inspected the server logs, the final PUT request ended without a status code. 

I use `yarn start:server` command to start the server and it runs  `ENV_VAR=SOME_VAL node --max-old-space-size=4096 ./packages/cli/src/cli.js server --config=../config/lighthouserc.js`. Though I increased the node's heap memory, the error still persists.

Below is the output of `free -m` when the docker container and the server was running.

```
              total        used        free      shared  buff/cache   available
Mem:          15867       12120         172         122        3574        3110
Swap:          4095        1922        2173
```
The docker container's memory usage: 200 - 700 MB (fluctuates) and memory limit: 15.5GiB

Can you please let me know what I am missing or what I should do? Do I need to further increase the memory?

**Comment by patrickhulce** [comment]
Thanks for filing @gauthampughaz! Wow that's a lot of LHRs!

Do you have access to the server to see why it's crashing? OOM is one option, but there could be other reasons as well.

**Comment by gauthampughaz** [comment]
Yes I have access to the server. What do you want me to do to get you more info?

**Comment by patrickhulce** [comment]
Meant to say server *logs*, just want the output of the server logs :) If the server is crashing or rejecting requests, there should be some evidence there.

**Comment by gauthampughaz** [comment]
@patrickhulce I checked the logs, there wasn't any error. It stopped at the final PUT request to seal the build and the request didn't return any status code or the time took by the server. But the request previous to it had them which was a POST request to upload the final LHR.

**Comment by gauthampughaz** [comment]
From the data I sent in my initial comment you can see that there is sufficient memory available for the server. I doubt whether the new heap size is accepted. Anyway to check that or am I doing it right?

**Comment by patrickhulce** [comment]
Do you have a proxy server or anything in front of the node server?

If there are no logs with errors my best guess is that the computation of all the statistics just takes too long and the proxy server aborts the request without a response even though the node server handles it just fine.

I don't see anything obviously wrong with how you're using the old space flags. How's the CPU on this machine? Is it pretty weak? Strong?

**Comment by gauthampughaz** [comment]
@patrickhulce I would like to add something, it worked pretty well for a lesser number of LHRs. Also, the node server has no proxy server before it. It is directly accessed by the docker container. So I have no clue why it is happening.

**Comment by balakumarrv** [comment]
@patrickhulce we did a try in LHCI server itself. not involved with CI system,Still we are seeing this error.  Can you please let us know where we can increase timeout settings in server ?.

**Comment by patrickhulce** [comment]
If you're seeing this error even when hitting the server directly with no intermediary that means you're bumping into node's default 2 minute socket timeout. That's *a lot* of data and probably dangerously approaching the limits of what LHCI server was designed to handle. We can override this to be longer, but know that you're probably entering unsupported territory by trying to store that much for *every* build.

**Comment by balakumarrv** [comment]
@patrickhulce can you please let us know where we can change the socket timeout settings in server ?

**Comment by patrickhulce** [comment]
@balakumarrv it's not something you can do from LHCI userland, https://github.com/GoogleChrome/lighthouse-ci/commit/c353ee8937bc0ca1474905baeb8d53799449ec56 increases it to 20 minutes.

**Comment by balakumarrv** [comment]
@patrickhulce issue is resolved after upgrading LHCI server from 0.4.1 to 0.5.0 version. Upload is much faster to server. We noticed below warning after upgrade.
"LHCI server not API compatible"

**Comment by patrickhulce** [comment]
Glad to hear it! And yes, that's because the client and the server need to be on the same major version.

**Comment by balakumarrv** [comment]
Do we need to run below npm command to upgrade client ? If we run below npm install will cause any issues to existing projects ?
 
npm install -g @lhci/cli@0.5.0

Please suggest us..!

**Comment by balakumarrv** [comment]
@patrickhulce Can you please let me know the above query ?

**Comment by patrickhulce** [comment]
That's not really what issues are for. Refer to the [release notes](https://github.com/GoogleChrome/lighthouse-ci/releases/tag/v0.5.0) and documentation for upgrades.

**Comment by anuraghazra** [comment]
@patrickhulce I'm also getting this error, any ideas? 

config: 
```js
module.exports = {
  ci: {
    collect: {
      settings: {
        chromeFlags: '--no-sandbox',
      },
      url: ['http://localhost:8888/'],
      startServerCommand: 'yarn beta:serve',
    },
    upload: {
      target: 'filesystem',
    },
  },
};
```

```sh
Started a web server with "yarn beta:serve"...
Running Lighthouse 3 time(s) on http://localhost:8888/
Run #1...failed!
Error: Lighthouse failed with exit code 1
    at ChildProcess.<anonymous> (/Users/anurag.hazra/.nvm/versions/node/v16.7.0/lib/node_modules/@lhci/cli/src/collect/node-runner.js:120:21)
    at ChildProcess.emit (node:events:394:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
Fri, 14 Jan 2022 10:53:20 GMT ChromeLauncher Waiting for browser.
Fri, 14 Jan 2022 10:53:20 GMT ChromeLauncher Waiting for browser...
Fri, 14 Jan 2022 10:53:20 GMT ChromeLauncher Waiting for browser...✓
Fri, 14 Jan 2022 10:53:20 GMT config:warn IFrameElements gatherer requested, however no audit requires it.
Fri, 14 Jan 2022 10:53:20 GMT config:warn FormElements gatherer requested, however no audit requires it.
Fri, 14 Jan 2022 10:53:20 GMT status Connecting to browser
Fri, 14 Jan 2022 10:53:20 GMT CriConnection:warn Cannot create new tab; reusing open tab.
Fri, 14 Jan 2022 10:53:20 GMT status Disconnecting from browser...
Fri, 14 Jan 2022 10:53:20 GMT CriConnection:error sendRawMessage() was called without an established connection.
Fri, 14 Jan 2022 10:53:20 GMT GatherRunner disconnect:error sendRawMessage() was called without an established connection.
Fri, 14 Jan 2022 10:53:20 GMT ChromeLauncher Killing Chrome instance 11670
Runtime error encountered: socket hang up
Error: socket hang up
    at connResetException (node:internal/errors:691:14)
    at Socket.socketOnEnd (node:_http_client:471:23)
    at Socket.emit (node:events:406:35)
    at endReadableNT (node:internal/streams/readable:1348:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

> I'm on mac m1.

**Comment by patrickhulce** [comment]
That is unrelated @anuraghazra (socket hang up in *Chrome* not the LHCI server) worth a separate issue detailing your environment. My best guess is an old or broken Chromium version in your environment.
