### ISSUE TITLE
Lighthouse-ci config for dynamic URLS

### ISSUE THREAD

**Issue by jimbyo** [GoogleChrome/lighthouse-ci#427]
Hi, I was wondering if there was a way to collect lighthouse scores from non-static webpages like the exploration_editor page in the example below.
```
    "collect": {
      "numberOfRuns": 1,
      "puppeteerScript": "puppeteer-login-script.js",
      "url": [
        "http://127.0.0.1:8181/admin",
        "http://127.0.0.1:8181/about",
        "http://127.0.0.1:8181/exploration_editor/<exploration_id>",
       ]
    },
```

 I looked https://github.com/GoogleChrome/lighthouse/issues/10150 but it seems it doesn't make use of the lighthouse-ci config.

**Comment by patrickhulce** [comment]
Yep! Just use a javascript-based config and pass the exploration ID through environment variables or a local file or something :)

```js
module.exports = {
  ci: {collect: {url: [`http://localhost:8181/dynamic/records/${process.env.RECORD_ID}`]}}
}
```

```bash
#!/bin/bash

export RECORD_ID=$(./path/to/a/script/that/gets/you/the/id.sh)
lhci autorun
```

You could also pass the URL using the command-line flag for URL instead. This is actually what Lighthouse CI does ourselves.

https://github.com/GoogleChrome/lighthouse-ci/blob/a707dd16a48d9b5680707887f7dced11d31bc856/scripts/ci-dogfood.sh#L16-L18

**Comment by jimbyo** [comment]
@patrickhulce Thanks for the help! I used the environment variables method and it worked well! :)
