### ISSUE TITLE
FetchError: request to http://localhost:9001/v1/projects/lookup failed for Heroku Server

### ISSUE THREAD

**Issue by JohnYuZhang** [GoogleChrome/lighthouse-ci#429]
I've set up a demo lhci project with the default configs as well as a demo heroku lhci server following the example provided in the documents. I'm running into the error:

```FetchError: request to http://localhost:9001/v1/projects/lookup failed, reason: connect ECONNREFUSED 127.0.0.1:9001
    at ClientRequest.<anonymous> (/opt/hostedtoolcache/node/10.22.0/x64/lib/node_modules/@lhci/cli/node_modules/node-fetch/index.js:133:11)
    at ClientRequest.emit (events.js:198:13)
    at Socket.socketErrorListener (_http_client.js:401:9)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)WARNING: upload command failed.
```

My upload config follows the base example provided with:

```   
upload: {
      target: 'lhci',
      serverBaseURL: 'http://lhci_server_location.herokuapp.com/',
      token: 'my_token'
    }
```

**Comment by patrickhulce** [comment]
Thanks for filing @JohnYuZhang! I think we're missing some important pieces of the puzzle here though. The error title you provided says ` request to http://localhost:9001/v1/projects/lookup failed` which means that the CLI was told to upload to an LHCI server located at `http://localhost:9001`.

What is the *exact* command you're using to run LHCI and the location of your config file?

**Comment by JohnYuZhang** [comment]
I'm using a github action to run lHCI. The command is 
```  
          run: |
          npm install -g @lhci/cli@0.4.x
          lhci autorun
```
My file structure is 
![image](https://user-images.githubusercontent.com/12836170/91322473-c7665980-e78d-11ea-84b3-9c3a6e052805.png)

The assertions inside the config file are running correctly and there is an error if I omit the token so I think it is finding the config.

**Comment by patrickhulce** [comment]
Ah, try changing `serverBaseURL` to `serverBaseUrl`

**Comment by JohnYuZhang** [comment]
Ah I had a feeling it was something like that. Thanks for the catch!
