### ISSUE TITLE
Desktop performance score lower in CLI than when testing in the browser

### ISSUE THREAD

**Issue by amannn** [GoogleChrome/lighthouse-ci#430]
I'm using `@lhci/cli` to test the desktop viewport of a web app I'm developing. I'm using the `emulatedFormFactor: 'desktop'` setting.

When running in `lhci`, I get this score:

![Screenshot 2020-08-27 at 11 43 43](https://user-images.githubusercontent.com/4038316/91424890-ad467d00-e85a-11ea-81fc-e6506366ae50.png)

However when I run the test with the same exact URL in Chrome, I get this score:

![Screenshot 2020-08-27 at 11 59 47](https://user-images.githubusercontent.com/4038316/91426445-d49e4980-e85c-11ea-8e21-7b453b913901.png)

I have no idea what is causing this.

Note that the mobile performance score of the same website is 100 in `lhci` – exactly the same as in Google Chrome.

Do you have any pointers? The app is private, therefore I sadly can't share a reproduction at this point. Thank you for your help!

Versions:
- @lhci/cli: 0.4.4 (although I got the same result when trying out 0.5.0)
 - Chrome: Version 84.0.4147.135 (Official Build) (64-bit)
 - OS: macOS 10.15.4 (19E287)
 - Chrome Lighthouse: 6.0.0
 - @lhci/cli Lighthouse: 6.0.0

**Comment by patrickhulce** [comment]
Thanks for filing @amannn! 

When you're running from the CLI (like LHCI does) form factor and throttling are controlled separately unlike Chrome DevTools which handles this behind the scenes for you (see [desktop throttling profile](https://github.com/GoogleChrome/lighthouse/blob/c2b7fcb99cf83fe4088f2ce5d40f6ae5724233d6/lighthouse-core/config/constants.js#L41-L46)).

```js
module.exports = {
  ci: {
    collect: {
      settings: {
        emulatedFormFactor: 'desktop',
        throttling: {rttMs: 40, throughputKbps: 10 * 1024, cpuSlowdownMultiplier: 1},
      }
  }
}
```

We'd welcome adding this example config to the docs if you're up for a PR :)

**Comment by amannn** [comment]
Oh, I see! Thanks for your quick reply – now this works as expected 🙂 .

Would it make sense for `lighthouse-ci` to include an option to set the device like lighthouse does it in the Chrome DevTools?

![Screenshot 2020-08-27 at 17 17 51](https://user-images.githubusercontent.com/4038316/91461494-5e640c00-e889-11ea-8a43-763ea7ae0bb0.png)

The option would control both the form factor and the throttling.

**Comment by patrickhulce** [comment]
> Would it make sense for lighthouse-ci to include an option to set the device like lighthouse does it in the Chrome DevTools?

We don't really want to drift from the official Lighthouse programmatic API. It's being considered over there for 7.0 if you want to chime in https://github.com/GoogleChrome/lighthouse/issues/10910

**Comment by amannn** [comment]
Right, I see. I'll open a PR to add the desktop settings to the docs as you proposed above.

**Comment by patrickhulce** [comment]
That's not really enough information to explain why. If you can share the full reports, we might be able to provide more assistance. (depending on metric values, 20-25 isn't _that_ unexpected [variance](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md))

**Comment by ankityadav4** [comment]
@patrickhulce Please find the attached reports. Do you have any pointers?
[Lighthouse Report.pdf](https://github.com/GoogleChrome/lighthouse-ci/files/11403717/Lighthouse.Report.pdf)
[LighthouseReport-UI.pdf](https://github.com/GoogleChrome/lighthouse-ci/files/11404440/LighthouseReport-UI.pdf)

**Comment by adamraine** [comment]
@ankityadav4 as patrick said the variance you are experiencing is not unexpected. There are a variety of reasons that the performance score of a page could change between runs.

The page content is slightly different between the two reports, this *could* affect your performance score. Please read our [variance docs](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md?rgh-link-date=2023-04-24T20%3A49%3A05Z) for more help.

**Comment by adamraine** [comment]
I'm going to lock this issue as it is very old. If you have a similar issue, please read our [variance docs](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md?rgh-link-date=2023-05-08T17%3A00%3A09Z) before filing a new issue.
