### ISSUE TITLE
Why is needed basic auth when upload to the server?

### ISSUE THREAD

**Issue by danipv** [GoogleChrome/lighthouse-ci#437]
Hello team,

I'm adding basic authentication to the server to limit web access and I have some doubts about how works the upload process. 

I'm wondering why is needed to run autorun or upload commands with `--upload.basicAuth.username` and `--upload.basicAuth.password` when the server is set up with basic auth. I mean, upload process is not already secured by the build token?

Thanks a lot for your help!

**Comment by patrickhulce** [comment]
If you've secured the entire server with basicAuth, then that means the API endpoints are behind basic auth as well, so username and password are necessary in addition to the token.

Maybe it sounds like you're asking for a feature where every server route has its own set of basicAuth params?

**Comment by danipv** [comment]
Thanks Patrick for your response.

Got it. Yeah you're right, basically I separate in my mind between api endpoints and ui endpoints, to me makes more sense to have basicAuth on ui endpoints and admin & build tokens to interact with api endpoints. Does it makes sense to you?

**Comment by patrickhulce** [comment]
> to me makes more sense to have basicAuth on ui endpoints and admin & build tokens to interact with api endpoints. Does it makes sense to you?

It wouldn't be security if basic auth only covered the UI. You would still need an authentication mechanism for the API endpoints that provide read access to the data. That's what basic auth is giving you today. What alternative authentication mechanism are you proposing there?

**Comment by danipv** [comment]
Yep, I didn't notice that api endpoints can be still read without build token. I really don't have any proposal to replace the whole authentication, I just see some redundancy in setting up build token and password in the upload process. If in some moment I have a better solution I will come again to you 😉 Thanks Patrick.
