### ISSUE TITLE
different units on savings scale

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse-ci#44]
![image](https://user-images.githubusercontent.com/4071474/68426386-e17e6f00-015c-11ea-9bc1-b8dce96f69aa.png)

`300` vs `0.8`. Implied ms and s. Confusing since there is no unit.

**Comment by patrickhulce** [comment]
yeah this jumped out in the meeting just now.

what would your expectation be for the labels on each side?

what if the range is 50 ms to 1500 ms?

@paulirish @exterkamp you too
