### ISSUE TITLE
Socket hang up error on Lighthouse CI 

### ISSUE THREAD

**Issue by balakumarrv** [GoogleChrome/lighthouse-ci#442]
i am facing same issue as #421 uploads to server works fine and noticed LHCI server is hanging (no response) for sometime after uploaded all the results to server,once after getting below error . it works fine for lesser LHRs(20). We have increased memory size still issue is persists. We have modified maxWaitForLoad and maxWaitforFcp still there is no difference in results.

Note : We have installed LHCI on windows server.

FetchError: request to {lhciserver.com}/v1/projects/{token}/builds/{buildHasH}/lifecycle failed, reason: socket hang up
    at ClientRequest.<anonymous> (.../node_modules/@lhci/cli/node_modules/node-fetch/index.js:133:11)
    at ClientRequest.emit (events.js:198:13)
    at Socket.socketOnEnd (_http_client.js:435:9)
    at Socket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by patrickhulce** [comment]
Thanks for filing @balakumarrv. Let's just discuss this issue in #421, see https://github.com/GoogleChrome/lighthouse-ci/issues/421#issuecomment-678327464 for the advice. 

> Increase the timeout at whatever layer is aborting the request. Since it's a CI process where a human isn't waiting, this seems like the easiest but it requires figuring out what layer is aborting the connection which I can't really help you with and is dependent on your setup

**Comment by balakumarrv** [comment]
can we reopen the ticket ? @patrickhulce we did a try in LHCI server itself. not involved with CI system,Still we are seeing this error. Can you please let us know where we can increase timeout settings in server ?.
