### ISSUE TITLE
Lighthouse 6.3

### ISSUE THREAD

**Issue by alex-misch** [GoogleChrome/lighthouse-ci#443]
Hi! Google's "PageSpeed Insights" is updated to version 6.3 on the 27th of august. It will be nice to get an update of "lhci" too.

**Comment by patrickhulce** [comment]
Every minor update of Lighthouse that introduces new audits becomes a breaking change in LHCI (see [version policy](https://github.com/GoogleChrome/lighthouse-ci/blob/master/docs/version-policy.md)). LHCI won't be as quick to update to avoid excessive churn, but yes we will eventually update to a new LH version.

**Comment by csabapalfi** [comment]
Do you accept PRs or any help with the lighthouse version bump? 

I can't enable lhci on a project while we're waiting for https://github.com/GoogleChrome/lighthouse/pull/11503 in `6.4.1`.

**Comment by patrickhulce** [comment]
Sure @csabapalfi a PR would be accepted for 6.4.1 but fair warning it's not a trivial amount of work :) 

You can use https://github.com/GoogleChrome/lighthouse-ci/pull/416 as a template.


Roughly...

- Bump the lighthouse version in package.json of both cli and utils
- Checkin two new LHR runs of coursehero to fixtures (just a useful site that has source maps to exercise those audits)
- Add the new fixture LHRs to all of our renderer tests 
- Update all the expectations

**Comment by csabapalfi** [comment]
Thanks for the quick reply! I'll let you know if I can start on this (might be later this week - at the earliest).
