### ISSUE TITLE
`lhci` incorrectly tries to serve (and audit) folder with `.html` extension

### ISSUE THREAD

**Issue by ojizero** [GoogleChrome/lighthouse-ci#444]
We are experiencing an issue where one of our Gatsby generated output, is a folder ending with `.html` in the name, this is prompting `lhci collect` step to try and serve it as if it is an HTML page even though it's just a normal folder.

The server code for reference where the filtering is only done on the file or folder's name only, specifically line 88. https://github.com/GoogleChrome/lighthouse-ci/blob/c353ee8937bc0ca1474905baeb8d53799449ec56/packages/cli/src/collect/fallback-server.js#L85-L89

This is causing failures as Lighthouse tries to serve it and fails to do so since it's a folder and not a page.

Is this an expected behaviour, and if so is there any workaround for it, or can it be considered a buggy behaviour on Lighthouse CI CLI part?

**Comment by patrickhulce** [comment]
Yeah we can consider this a bug. I would've expected a folder ending in `.html` to end up serving some content via an `index.html` *within* that folder, but we probably shouldn't autoselect it either way. It's a pretty easy fix if anyone is interested :) We can use `fs.readdirSync(directory, {withFileTypes: true})` to filter out directories in that line you flagged.

The workaround is to explicitly specify what URLs you want Lighthouse CI to collect.

`lhci collect --url=http://localhost/what/to/audit --url=http://localhost/another/url`

**Comment by ojizero** [comment]
@patrickhulce thanks for the quick response! just opened PR for it #445
