### ISSUE TITLE
Add build context env for author email for deriving gravatar urls

### ISSUE THREAD

**Issue by gpaciga** [GoogleChrome/lighthouse-ci#446]
I'm running in a situation where I need to specify build context variables myself, per https://github.com/GoogleChrome/lighthouse-ci/blob/master/docs/configuration.md#build-context. One I am having trouble with is the avatar URL. LHCI complains that it can't figure out the committer's email:

```
Error: Unable to determine commit author's avatar URL because `git log --format=%aE -n 1` failed to provide author's email. This can be overridden with setting LHCI_BUILD_CONTEXT__AVATAR_URL env.
```

This is expected for me. However, unlike other build context values that LHCI fails to find from git, there's no build context env for email. Using `LHCI_BUILD_CONTEXT__AVATAR_URL` as suggested means I have to implement something to calculate a gravatar url myself, even though LHCI already knows how to do this internally. Unless I wanted to provide an avatar url from somewhere other than gravatar, this doesn't make sense.

It would much more straight forward for me to provide the email through a new build context env var like `LHCI_BUILD_CONTEXT__AUTHOR_EMAIL` and let LHCI derive the gravatar URL from that as normal.

**Comment by patrickhulce** [comment]
Thanks for filing @gpaciga! I'm open to this. It should be fairly straightforward to add and test if anyone is interested in a PR :)

**Comment by gpaciga** [comment]
I had some time to take a stab at this today.

My game plan is to add a `getAuthorEmail` function that mirrors `getAuthor`, and have `getAvatarUrl` use that. 

Should be able to open a PR shortly.
