### ISSUE TITLE
Ambiguous assertion error messages

### ISSUE THREAD

**Issue by suswariadla** [GoogleChrome/lighthouse-ci#448]
Hi,
Are there assertions for cumulative layout shift and largest contentful paint ?
however I gave a try for cumulative-layout-shift  and largest-contentful-paint which did not work. 

Thankyou

**Comment by patrickhulce** [comment]
Yes you can do this with the latest version of LHCI (0.5.0).

**Comment by suswariadla** [comment]
Cool, thanks!!
I checked it out and works fine for lcp while I see multiple results cls. Here is a image of it
<img width="641" alt="Screen Shot 2020-09-17 at 5 07 01 PM" src="https://user-images.githubusercontent.com/47369252/93528623-9ac6dd00-f908-11ea-91cc-449bb23a7dbc.png">

**Comment by patrickhulce** [comment]
Hm, I'm not able to reproduce that result. Could you provide steps, a config, and URL for a bug report?

`auditRan` assertion failure means that the underlying audit errored and didn't produce a result.

**Comment by suswariadla** [comment]
Hi @patrickhulce, Below is the json and here is the report https://storage.googleapis.com/lighthouse-infrastructure.appspot.com/reports/1600697154235-39092.report.html 
{
	"ci": {
		"numberOfRuns" : 1,
		"assert": {
			"preset": "lighthouse:recommended",
			"assertions": {
				"categories.pwa": "off",
				"categories.seo": "off",
				"categories.best-practices": "off",
				"categories.accessibility": "off",
				"first-contentful-paint": ["error", {"maxNumericValue": 2000}],
				"speed-index": ["error", {"maxNumericValue": 4300}],
				"total-blocking-time": ["error", {"maxNumericValue": 300}],
				"interactive": ["error", {"maxNumericValue": 3800}],
				"long-tasks": ["error", {"maxNumericValue": 50}],
				"network-server-latency": ["error", {"maxNumericValue": 600}],
				"largest-contentful-paint": ["error", {"maxNumericValue": 3000}],
				"cumulative-layout-shift ": ["error", {"maxNumericValue":100}],
				"duplicate-id-active": "off",
				"duplicate-id-aria": "off",
				"duplicated-javascript": "off",
				"form-field-multiple-labels": "off",
				"apple-touch-icon": "off",
				"maskable-icon": "off",
				"aria-hidden-body": "off",
				"aria-hidden-focus": "off",
				"aria-input-field-name": "off",
				"aria-toggle-field-name": "off",
				"charset": "off",
				"crawlable-anchors": "off",
				"heading-order": "off",
				"legacy-javascript": "off",
				"non-composited-animations": "off",
				"timing-budget": "off",
				"unused-javascript": "off",
				"unsized-images": "off",
				"no-unload-listeners": "off",
				"image-size-responsive": "off",
				"critical-request-chains": "off",
				"first-meaningful-paint": "off",
				"estimated-input-latency": "off",
				"color-contrast": "off",
				"uses-http2": "off",
				"viewport": "off",
				"video-description": "off",
				"video-caption": "off",
				"valid-lang": "off",
				"uses-webp-images": "off",
				"uses-text-compression": "off",
				"uses-responsive-images": "off",
				"uses-rel-preload": "off",
				"uses-rel-preconnect": "off",
				"uses-passive-event-listeners": "off",
				"uses-optimized-images": "off",
				"unminified-javascript": "off",
				"unminified-css": "off",
				"total-byte-weight": "off",
				"time-to-first-byte": "off",
				"themed-omnibox": "off",
				"th-has-data-cells": "off",
				"td-headers-attr": "off",
				"tap-targets": "off",
				"tabindex": "off",
				"splash-screen": "off",
				"robots-txt": "off",
				"render-blocking-resources": "off",
				"redirects": "off",
				"plugins": "off",
				"password-inputs-can-be-pasted-into": "off",
				"offscreen-images": "off",
				"object-alt": "off",
				"notification-on-start": "off",
				"no-vulnerable-libraries": "off",
				"no-document-write": "off",
				"meta-viewport": "off",
				"meta-refresh": "off",
				"meta-description": "off",
				"mainthread-work-breakdown": "off",
				"load-fast-enough-for-pwa": "off",
				"listitem": "off",
				"list": "off",
				"link-text": "off",
				"link-name": "off",
				"layout-table": "off",
				"label": "off",
				"is-crawlable": "off",
				"installable-manifest": "off",
				"input-image-alt": "off",
				"image-aspect-ratio": "off",
				"image-alt": "off",
				"http-status-code": "off",
				"html-lang-valid": "off",
				"html-has-lang": "off",
				"hreflang": "off",
				"geolocation-on-start": "off",
				"frame-title": "off",
				"font-size": "off",
				"font-display": "off",
				"external-anchors-use-rel-noopener": "off",
				"errors-in-console": "off",
				"efficient-animated-content": "off",
				"duplicate-id": "off",
				"dom-size": "off",
				"document-title": "off",
				"doctype": "off",
				"dlitem": "off",
				"deprecations": "off",
				"definition-list": "off",
				"content-width": "off",
				"canonical": "off",
				"bypass": "off",
				"button-name": "off",
				"bootup-time": "off",
				"audio-caption": "off",
				"aria-valid-attr-value": "off",
				"aria-valid-attr": "off",
				"aria-roles": "off",
				"aria-required-parent": "off",
				"aria-required-children": "off",
				"aria-required-attr": "off",
				"aria-allowed-attr": "off",
				"appcache-manifest": "off",
				"accesskeys": "off",
				"uses-long-cache-ttl": "off",
				"redirects-http": "off",
				"max-potential-fid": "off",
				"is-on-https": "off",
				"first-cpu-idle": "off",
				"works-offline": "off",
				"without-javascript": "off",
				"unused-css-rules": "off",
				"service-worker": "off",
				"offline-start-url": "off"

			},
			"includePassedAssertions": true
		},
		"upload": {
			"target": "temporary-public-storage"
		}
	}
}

**Comment by patrickhulce** [comment]
Thanks for the extra detail @suswariadla! It's part configuration issue, part bug, but we'll definitely work on providing a better error message here for the misconfiguration bits.

For the long-tasks message, the long-tasks audit does not have a `numericValue` at all, so you can't assert a maxNumericValue there.

For the CLS configuration, the max CLS can be is roughly `1` so you'd want to set a maxNumericValue to something more like `0.1` than `100`.

There's a bug on CLS numeric value assertions we need to fix in LHCI when the value is `0`.


Here's the OP's provided report for posterity
[lhci.report.html.zip](https://github.com/GoogleChrome/lighthouse-ci/files/5255895/lhci.report.html.zip)

**Comment by patrickhulce** [comment]
Turns out all of this is misconfiguration afterall @suswariadla and we both missed the typos :)

Would you have been able to figure out what was going on if this were the output?

![image](https://user-images.githubusercontent.com/2301202/93817921-42048680-fc1f-11ea-8aaf-b923739f6efc.png)

**Comment by suswariadla** [comment]
Not really. I took off the long-tasks and for the CLS i changed to `{"maxNumericValue":0.1}` 
I still it though
<img width="499" alt="Screen Shot 2020-09-21 at 4 46 27 PM" src="https://user-images.githubusercontent.com/47369252/93819697-0fac5680-fc2a-11ea-8f28-9c0e54e4528b.png">

**Comment by patrickhulce** [comment]
@suswariadla the problem is the extra space, `cumulative-layout-shift ` is not a valid audit ID `cumulative-layout-shift` is.

**Comment by suswariadla** [comment]
Ah, you got it. That worked, thankyou :-)
