### ISSUE TITLE
Allow customizing asset URL normalization

### ISSUE THREAD

**Issue by squiddy** [GoogleChrome/lighthouse-ci#454]
Similar to `--urlReplacementPatterns` that normalizes URLs under test, I want to be able to do the same for assets, i.e. JS or CSS files, by providing my own patterns.

This allows me to have changes in assets show up correctly, i.e. going from this

```
Removed commons-hashA.js -200kB
Added commons-hashB.js +201kB
```

to this

```
Changed common.js +1kB
```

---

When I set up this project initially, I thought that's what `--urlReplacementPatterns` does. Took a while to figure out it it's not.

https://github.com/GoogleChrome/lighthouse-ci/issues/319 led me to find the `replaceNondeterministicStrings` function, that already seems to apply some normalization, but it's not customizable.

My particular use-case is to allow removing the hash of assets created by webpack, those are 12 characters in length, and currently only lengths of 6 and 8 are removed.

https://github.com/GoogleChrome/lighthouse-ci/blob/master/packages/utils/src/audit-diff-finder.js#L350

Happy to help out here with some code!

**Comment by patrickhulce** [comment]
Thanks for filing @squiddy! Would you mind weighing in on https://github.com/GoogleChrome/lighthouse-ci/issues/154 which captures this? We have a few proposals there already (https://github.com/GoogleChrome/lighthouse-ci/issues/154#issuecomment-594729390).

As for your specific webpack hash issue, let's just extend the built-in normalization to cover that case :)

**Comment by squiddy** [comment]
Oh no, sorry about the duplicate. I looked twice through the issues to avoid that. :)

I'll have a look over there.

**Comment by therealshark** [comment]
@patrickhulce What's the plan for the regex? I have a similar problem with webpack generated hashes, mine are 20 characters long and have a ".min" before the file ending. Example: `app-9251ab7acc292d65ffee.min.js`. I  think finding a magic regex that works for every project might be quite hard ;)

**Comment by patrickhulce** [comment]
@therealshark I agree its impossible thats why #154 exists.
