### ISSUE TITLE
Lighthouse CI run aborting no matter what I do

### ISSUE THREAD

**Issue by albert1355** [GoogleChrome/lighthouse-ci#458]
Running lighthouse on my main site from inside Chrome devtools works just fine by the way.
But for some reason with lighthouse-ci I always get this result:

```
[...]
Fri, 25 Sep 2020 14:43:34 GMT status Auditing: Structured data is valid
Fri, 25 Sep 2020 14:43:34 GMT status Generating results...
Fri, 25 Sep 2020 14:43:34 GMT ChromeLauncher Killing Chrome instance 26168
Runtime error encountered: Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests. (Status code: 500)
```

I even tried running with only a single assertion but no change.

``` lighthouserc.js
module.exports = {
  ci: {
    collect: {
      // collect options here
      numberOfRuns : 1,
      url : "https://localhost/test/3",
	  settings: {
		chromeFlags: ["--ignore-certificate-errors"]
      }
    },
    assert: {
      // assert options here
		assertions: {
                   "first-contentful-paint": "warn",
		}    
	},
    upload: {
      target: 'lhci',
      serverBaseUrl: 'http://localhost:9001',
      token: '897dce7f-5a2b-484b-ab4e-1a752cb2b80a', 
    },
    server: {
      // server options here
    },
    wizard: {
      // wizard options here
    },
  },
};

```

``` package.json
{
  "dependencies": {
    "@lhci/server": "^0.5.0",
    "sqlite3": "^5.0.0"
  },
  "devDependencies": {
    "@lhci/cli": "^0.5.0"
  },
  "scripts": {
    "lhci": "lhci autorun"
  }
}
```

It would be nice to get more of a log here, this 500 error does not make sense to me because like I said: it runs fine in Chrome itself and the site loads in general. I also do not believe that my lighthouse-ci setup is wrong, I successfully run against other localhost or online sites and it uploads results to the dashboard. I just need it to work for my big site...

**Comment by albert1355** [comment]
@patrickhulce thank you for your help, it turns out that lighthouse for some reason was launching the site in mobile mode which automatically redirects my site to a mobile server that wasn't even running properly. Now I run with `emulatedFormFactor: "desktop",` and everything seems to work. I do think that the viewer being an external site is not idea, maybe these reports could be privacy sensitive and it seems that each time I click "view report", it will upload it to "https://googlechrome.github.io/lighthouse/viewer/" for viewing.

**Comment by patrickhulce** [comment]
> maybe these reports could be privacy sensitive and it seems that each time I click "view report", it will upload it to "https://googlechrome.github.io/lighthouse/viewer/" for viewing

FWIW, they aren't uploaded anywhere. It's `postMessage`'d using `window.opener` and everything stays client-side, but noted. 

I'm going to go ahead and close this as it sounds like you've found your issue.
