### ISSUE TITLE
UI: Cannot click into compare or report from dashboard after hovering over data point

### ISSUE THREAD

**Issue by zdelagrange** [GoogleChrome/lighthouse-ci#459]
![2020-09-28 11 42 18](https://user-images.githubusercontent.com/2396074/94454311-bab79580-017f-11eb-8228-60a557ec68e0.gif)

See the attached gif. When hovering over a metric datapoint on the graph, there is a pop up that allows you to click into the report or compare it. It's impossible to click links in that pop up due to the pop up changing when the cursor moves into the next data point area.

**Comment by zdelagrange** [comment]
Actually, I just noticed the "click graph to pin" feature at the bottom. Closing the issue, unless there's a UI improvement to be seen here.

**Comment by patrickhulce** [comment]
Seems like you figured this one out :) We've already made the cursor a pointer to indicate clickability and added the "click graph to pin" notice fairly prominently in the overlay, unless you have other ideas on how to maintain scrubabbility as a feature while making this clickable?

**Comment by zdelagrange** [comment]
the only thing i could think of would be to have small buttons or links at the bottom of each data point, near where the bar gets rendered for each data point.

the graph is really the selling point towards getting the users of the report to investigate more. maybe even choosing some common svg type buttons could work. for example something like magnifying glass for report and 2 documents side by side for compare

maybe something these as an example
https://material.io/resources/icons/?icon=compare_arrows&style=baseline
https://material.io/resources/icons/?icon=pageview&style=baseline

lots of stuff in the material design library that you might like better too. not sure if it would solve the UX "issue" but could be a good discussion launching off point.
