### ISSUE TITLE
Target.setAutoAttach wasn't found error

### ISSUE THREAD

**Issue by sumesh-sukumaran** [GoogleChrome/lighthouse-ci#462]
Running LHCI on an Ubuntu 16.04 machine executor. The base image has chrome installed, but when I tried running LHCI i get this protocol error

> Run #1...failed!
> Error: Lighthouse failed with exit code 1
>     at ChildProcess.<anonymous> (/opt/circleci/.nvm/versions/node/v12.18.3/lib/node_modules/@lhci/cli/src/collect/node-runner.js:103:21)
>     at ChildProcess.emit (events.js:315:20)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
> Tue, 29 Sep 2020 23:14:57 GMT ChromeLauncher Waiting for browser.
> Tue, 29 Sep 2020 23:14:57 GMT ChromeLauncher Waiting for browser...
> Tue, 29 Sep 2020 23:14:58 GMT ChromeLauncher Waiting for browser.....
> Tue, 29 Sep 2020 23:14:58 GMT ChromeLauncher Waiting for browser.......
> Tue, 29 Sep 2020 23:14:58 GMT ChromeLauncher Waiting for browser.......✓
> Tue, 29 Sep 2020 23:14:59 GMT status Connecting to browser
> Tue, 29 Sep 2020 23:14:59 GMT status Resetting state with about:blank
> Tue, 29 Sep 2020 23:14:59 GMT method <= browser ERR:error Target.setAutoAttach 
> Tue, 29 Sep 2020 23:14:59 GMT status Disconnecting from browser...
> Tue, 29 Sep 2020 23:14:59 GMT ChromeLauncher Killing Chrome instance 7452
> Runtime error encountered: Protocol error (Target.setAutoAttach): 'Target.setAutoAttach' wasn't found
> Error: Protocol error (Target.setAutoAttach): 'Target.setAutoAttach' wasn't found
>     at Function.fromProtocolMessage (/opt/circleci/.nvm/versions/node/v12.18.3/lib/node_modules/@lhci/cli/node_modules/lighthouse/lighthouse-core/lib/lh-error.js:140:19)
>     at /opt/circleci/.nvm/versions/node/v12.18.3/lib/node_modules/@lhci/cli/node_modules/lighthouse/lighthouse-core/gather/connections/connection.js:124:25
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)

Has this been reported when executing LHCI on CircleCI?

**Comment by patrickhulce** [comment]
This means your Chrome version is too old. Only stable Chrome is supported. Try `apt-get update && apt-get install google-chrome-stable` step to upgrade it? Or use a newer docker image that already has it updated.
