### ISSUE TITLE
Server should periodically delete old builds

### ISSUE THREAD

**Issue by koh110** [GoogleChrome/lighthouse-ci#463]
I'm running lhci-server in MySQL. I'm having problem with the data usage on my MySQL server.

My data of lhci is growing at a rate of 7GB/month.

I think the base64 encoded screenshot data in `lhr` is the main cause of the amount of data.

[Ref: run-model.js](https://github.com/GoogleChrome/lighthouse-ci/blob/master/packages/server/src/api/storage/sql/run-model.js#L22)

I read the source code and think it would be a good idea to create a feature to periodically erase old recode using deleteBuild. What do you think of this idea?
If it is possible, I would like to create this feature.

[Ref: deleteBuild](https://github.com/GoogleChrome/lighthouse-ci/blob/ab80a434b6812f027d0b7cb549d736c7d8b8925a/packages/server/src/api/storage/sql/sql.js#L459-L482)

Or please tell me how to delete the records correctly.

In my environment, this number of records has already consumed nearly 30GB of data.

```
> select count(*) from builds;
+----------+
| count(*) |
+----------+
|     6142 |
+----------+

> select count(*) from runs;

+----------+
| count*+) |
+----------+
|    36830 |
+----------+
```

**Comment by patrickhulce** [comment]
> I read the source code and think it would be a good idea to create a feature to periodically erase old recode

Sounds good! We can add another cron task to the server that does this similar to

https://github.com/GoogleChrome/lighthouse-ci/blob/5750eba7489a40bf6910dd675ddafb6629e686aa/packages/server/src/cron/psi-collect.js#L8-L12

We'll want to add a query for fetching build IDs past a certain date.

**Comment by patrickhulce** [comment]
Note: if you need to free up space immediately, you can feel free to delete all records from the `runs` table that aren't *representative* because the server doesn't use them in the UI at the moment.

`SELECT COUNT(*) FROM runs WHERE representative = false` (make sure it looks OK and isn't overreaching)
`DELETE FROM runs WHERE representative = false` (then actually delete)

**Comment by koh110** [comment]
Thanks your comment.

I'll try to do this first.
> SELECT COUNT(*) FROM runs WHERE representative = false (make sure it looks OK and isn't overreaching)
> DELETE FROM runs WHERE representative = false (then actually delete)

And I'll check cron task. It may take some time, but I'll try to add features.
