### ISSUE TITLE
CLS is reported with ms unit

### ISSUE THREAD

**Issue by safwansamla** [GoogleChrome/lighthouse-ci#465]
Lighthouseci 0.5 reports changes in CLS with ms unit, which is not the right unit for CLS. Check out the sample report for reference.

https://googlechrome.github.io/lighthouse-ci/viewer/?baseReport=https%3A%2F%2Fstorage.googleapis.com%2Flighthouse-infrastructure.appspot.com%2Freports%2F1601907185378-33020.report.html&compareReport=https%3A%2F%2Fstorage.googleapis.com%2Flighthouse-infrastructure.appspot.com%2Freports%2F1601907759190-41643.report.html

**Comment by patrickhulce** [comment]
Thanks for filing @safwansamla! Interested in a PR at all? :)
