### ISSUE TITLE
css nit: overlap on metrics bar

### ISSUE THREAD

**Issue by exterkamp** [GoogleChrome/lighthouse-ci#47]
Same as the cyan bar being too low and overlapping, the red overlaps the other way...
![image](https://user-images.githubusercontent.com/6392995/68507493-dd1b8a00-0220-11ea-9fdf-1f9cad082638.png)

**Comment by patrickhulce** [comment]
This is on canary, link? Those bars are really short and look like the older version before this was fixed...

**Comment by exterkamp** [comment]
Was from treo's CI server. Not gonna share their link. If I see it on ours I'll reopen.
