### ISSUE TITLE
Lighthouse CI failling because of rel canonical

### ISSUE THREAD

**Issue by tairosonloa** [GoogleChrome/lighthouse-ci#472]
I have this on my `.lighthouserc.json`:
```
{
  "ci": {
    "assert": {
      "assertions": {
        "categories:seo": ["error", { "minScore": 1 }],
      }
    }
  }
}

```
However, the SEO audit always gets 0.92 score because:
>  Document does not have a valid rel=canonicalPoints to a different domain (https://my-domain/)

I'm running lighthouse CI in GitHub actions, not in my domain, so this audit always fail. However, the canonical `https://my-domain/` is correct. Is there a way to mock this or whatever?

Thanks in advance

**Comment by patrickhulce** [comment]
Thanks for filing @tairosonloa! There is not a way to mock this. You have roughly three options.

- Lower your minscore category score to account for this failure.
- Assert against the SEO audits individually instead.
- Dynamically generate the rel=canonical so it matches localhost in CI.

**Comment by tairosonloa** [comment]
Thank you very much @patrickhulce for your quick and detailed response.

So as I'm running this as a separate CI job, and I'm getting my domain from an ENV var, I just hard-coded the ENV var to fit `localhost` on that job `.yml` file. It was enough to get 100% SEO audit score.

Have a good day!
