### ISSUE TITLE
Automate into Application workflows

### ISSUE THREAD

**Issue by kaihendry** [GoogleChrome/lighthouse-ci#473]
https://s.natalian.org/2020-10-17/results.png is unusable DX when integrating Lighthouse to Github workflows. A score needs to be printed.

Could:
* https://github.com/treosh/lighthouse-ci-action/issues/60
* https://github.com/treosh/lighthouse-ci-action/issues/41

Be prioritesd by Google Engineers?

**Comment by patrickhulce** [comment]
No. That project is not worked on by Google engineers. The official solution for surfacing the scores on the PR is the [Lighthouse CI GitHub App](https://github.com/apps/lighthouse-ci).

A friendly tip when you do approach the nice engineers behind the repo you linked: if you'd like folks maintaining an open source project to consider your suggestion, starting off by calling what they've generously built for the community "unusable" generally doesn't start off on the right foot ;)

**Comment by kaihendry** [comment]
Sorry to offend, though the results are not actionable.

**Comment by paulirish** [comment]
@kaihendry sorry but your bug report is unusable and ineffective. learn some open source manners.
