### ISSUE TITLE
Too much variance in results of chrome's lighthouse and lighthouse-ci results

### ISSUE THREAD

**Issue by nishantdongare** [GoogleChrome/lighthouse-ci#475]
I am trying to integrate in our TravisCI. I am following the configuration below 
```
{
  "ci": {
    "upload": {
      "target": "temporary-public-storage"
    },
    "collect": {
      "additive": false,
      "isSinglePageApplication": true,
      "numberOfRuns": 2,
      "url": [
        "*******private url********"
      ],
      "headful": true,
      "settings": {
        "disableStorageReset": true,
        "emulatedFormFactor": "mobile"
      },
      "maxWaitForLoad": 90000,
      "puppeteerScript": "puppeteer-script/login.js"
    }
  }
}
```
**Lighthouse CI score for mobile(No throttling applied)**
<img width="953" alt="Screenshot 2020-10-22 at 5 30 03 AM" src="https://user-images.githubusercontent.com/9926475/96803136-05e46180-1429-11eb-90e7-f8605a726400.png">
**Brower CI score for mobile(Simulated throttling applied)**
<img width="900" alt="Screenshot 2020-10-22 at 5 31 32 AM" src="https://user-images.githubusercontent.com/9926475/96803142-0b41ac00-1429-11eb-84dc-784283dd118f.png">

Puppeteer script consists of login related automation. When I am comparing results from Chrome’s lighthouse and LighthouseCI there is a huge difference between both of them. 
I have also tried different throttling method but no luck.

**Comment by patrickhulce** [comment]
Thanks for filing @nishantdongare! 

Please refer to the [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) documentation in Lighthouse for expectations around environment differences. In general, it will be incredibly difficult to match low quality, variable hardware in cloud CI environments to numbers from your local machine. Instead, consider CI changes relative to the CI's baseline (sidenote, reducing the number of runs to just 2 certainly isn't going to help, if you're really going to rely on metric and performance data I would use *at least* 5 if not 9 or more, especially on Travis).

**Comment by nishantdongare** [comment]
@patrickhulce Thanks for the reply. Will run `lhci autorun` on local env instead of TravisCI with `numberOfRuns` to 5 and check that results

**Comment by nishantdongare** [comment]
<img width="1669" alt="Screenshot 2020-10-26 at 6 16 15 AM" src="https://user-images.githubusercontent.com/9926475/97123673-e9ab3200-1752-11eb-8c40-ef35bbf2a70e.png">
@patrickhulce Changes `"numberOfRuns": 10` and got above result. 
Applied throttling suggested in this config file as [link](https://github.com/GoogleChrome/lighthouse/blob/8f500e00243e07ef0a80b39334bedcc8ddc8d3d0/lighthouse-core/config/constants.js#L19-L26) but no luck. Still, the performance score is coming as 91
Following is the full config
```
{
  "ci": {
    "upload": {
      "target": "lhci",
      "serverBaseUrl": "http://localhost:9001",
      "token": "f830cccf-ad4b-4ec9-8e79-6dc3af12b5a9"
    },
    "collect": {
      "additive": false,
      "isSinglePageApplication": true,
      "numberOfRuns": 10,
      "url": [
        "https://msd-int-11-stag.d11dev.com/290f93a31b940063e544db32efa0a67f/fantasy/teamList?gameId=2"
      ],
      "headful": false,
      "settings": {
        "disableStorageReset": true,
        "emulatedFormFactor": "mobile"
      },
      "maxWaitForLoad": 90000,
      "puppeteerScript": "puppeteer-script/login.js",
      "setting": {
        "throttlingMethod": "simulate",
        "throttling": {
          "rttMs": 150,
          "requestLatencyMs": 562,
          "uploadThroughputKbps": 675,
          "downloadThroughputKbps": 1474,
          "cpuSlowdownMultiplier": 4
        }
      }
    }
  }
}
```

**Comment by patrickhulce** [comment]
I'm not sure I understand the problem with your screenshot. You're actually trying to measure the warm load performance here and doing the same settings in DevTools right? That's what `disableStorageReset` does if you're visiting the page with a puppeteer script before hand.

**Comment by nishantdongare** [comment]
Let me try to give the full context. My application needs login to get the pages for which I want to measure performance. So `puppeteer-script/login.js` do that for me. Since the Application is storing the login-related information in `localStorage` I don't want it to be cleared before starting the performance audit. 
Now let me come to the issue. The problem here is when i use lighthouse in chrome the average performance score for mobile is around 50-60 but when I tried with `lighthouse-ci` it with the above config it is a score between 90-95(which is incorrect I guess).

puppeteer-script/login.js for reference 

```
module.exports = async (browser, context) => {
  // launch browser for LHCI

  const page = await browser.newPage()

 
  await page.setCacheEnabled(false)
  await page.goto(
    `******Login URL********`
  )
 
  await page.waitForSelector('input[name=username]')
  await page.click('input[name=username]')
  await page.type('input[name=username]', 'myusername')
  await page.click('input[name=password]')
  await page.type('input[name=password]', 'mypassword')
  await page.click('[type="submit"]')
  await page.waitForNavigation()
  // // close session for next run
  await page.close()
}
```

**Comment by patrickhulce** [comment]
> The problem here is when I use lighthouse in chrome the average performance score for mobile is around 50-60

And you're not clearing storage in Chrome, correct?

**Comment by nishantdongare** [comment]
Yes. Otherwise it will clear the score and the user will be thrown to the login page.

**Comment by patrickhulce** [comment]
Hm, I can't immediately think of any other obvious settings differences that would lead to this then. You've already checked the screenshots, final URL, and runtime settings (at the bottom of the report) make sure the puppeteer script is working and the same page is being measured with the exact same settings I assume?

As a temporary measure you can set `headful: true` to actually watch Lighthouse CI load the page and make sure it looks the same.

**Comment by nishantdongare** [comment]
> As a temporary measure you can set headful: true to actually watch Lighthouse CI load the page and make sure it looks the same.

It tried it. The page is loading properly and the puppeteer script is also working fine. To tried one more thing I have given the throttling value for  `"emulatedFormFactor": "mobile"` as follows
```
"throttling": {
  "rttMs": 600,
  "requestLatencyMs": 1200,
  "uploadThroughputKbps": 500,
  "downloadThroughputKbps": 500,
  "cpuSlowdownMultiplier": 5
}
```
Then the score is coming around 50-60. But I think these are very slow when compare to standard values provided in the default lighthouse config

**Comment by patrickhulce** [comment]
> runtime settings (at the bottom of the report)

And this one? :)

One more other obvious thing I forgot about is DevTools is severely affected by Chrome extensions, anti-virus meddling, or anything that modifies the browser (we've even seen print drivers inject crap into Chrome DevTools). The 50-60 score is in a completely clean Chrome profile without any of the above?

**Comment by patrickhulce** [comment]
Appreciate the filing of this @nishantdongare but we don't have the capacity to be able to help debug this sort of issue further. I've added [this shortcut FAQ](https://github.com/GoogleChrome/lighthouse-ci/blob/master/docs/troubleshooting.md#the-results-im-seeing-dont-match-the-results-i-see-in-another-environment) to our docs, but that's about the extent of what we can do right now.

I hope you figure out the discrepancy and please share if you do so others may be aware of it who stumble on this issue in the future! :)
