### ISSUE TITLE
Environment variables don't work for autorun

### ISSUE THREAD

**Issue by dangreen** [GoogleChrome/lighthouse-ci#480]
I have config only with "collect" section, and I want to pass serverBaseUrl via environment variables:
- `yarn lhci autorun --upload.serverBaseUrl=...` works as expected
- `LHCI_UPLOAD__SERVER_BASE_URL=... yarn lhci autorun` doesn't work as expected
- `LHCI_SERVER_BASE_URL=... yarn lhci autorun` causes assertions (but shouldn't)

Which environment variable name I should use to pass serverBaseUrl?

**Comment by dangreen** [comment]
I found the problem: 

https://github.com/GoogleChrome/lighthouse-ci/blob/master/packages/cli/src/upload/upload.js#L106

Due to the default value set here, we have options like that:

```js
{
  _: [ 'upload' ],
  ...
  upload: {
    serverBaseUrl: 'http://lighthouse.lighthouse-server-lighthouse:9001'
  },
  ...
  serverBaseUrl: 'http://localhost:9001/',
  'server-base-url': 'http://localhost:9001/',
  ...
}
```

So we should set both variables LHCI_UPLOAD__SERVER_BASE_URL and LHCI_SERVER_BASE_URL - I think it is wrong approach.

**Comment by patrickhulce** [comment]
Thanks for filing @dangreen! This is an unfortunate wrinkle with the child process approach used by `autorun`. I think the "right" solution that's the most flexible is to have each command collect/assert/upload merge all the options set in its named property. Then you'd be able to only set `LHCI_UPLOAD__SERVER_BASE_URL` here.

An alternative approach would be to have autorun strip the prefixes from environment variables as they're passed along.
