### ISSUE TITLE
Helm chart support

### ISSUE THREAD

**Issue by emmekappa** [GoogleChrome/lighthouse-ci#483]
It would be great to have an helm chart in order to install lighthouse-ci on a kubernetes cluster.

**Comment by patrickhulce** [comment]
Thanks for filing @emmekappa! I don't think we'll maintain this, but if any external contributor would like to get a `contrib/` folder going with an example of this, that'd be great :)

**Comment by sebastien-prudhomme** [comment]
I will soon add one in my Helm repository. The first version should have SQLite database and basic auth.

**Comment by sebastien-prudhomme** [comment]
@emmekappa  If you can provide some feedback, got a first version there: https://github.com/sebastien-prudhomme/cowboysysop-charts/tree/lighthouse-ci/charts/lighthouse-ci

Not yet in my repository, so don't use `helm install cowboysysop/lighthouse-ci` command.

**Comment by sebastien-prudhomme** [comment]
@emmekappa you can now use the helm repo: https://artifacthub.io/packages/helm/cowboysysop/lighthouse-ci

**Comment by emmekappa** [comment]
@sebastien-prudhomme just give it a test and it works correctly I didn't push too far the chart configuration I'm just using `limits` and `ingress` configuration.

**Comment by emmekappa** [comment]
@sebastien-prudhomme just found a bug: when using basic auth the healthchecks gets broken.

**Comment by sebastien-prudhomme** [comment]
@emmekappa I have no problem with such a config.

Perhaps a special character that is not well converted in the Authorization HTTP header?

Can you share the user/password you used and perhaps open an issue on the GitHub project https://github.com/cowboysysop/charts

**Comment by patrickhulce** [comment]
Thanks for sharing your chart with the community @sebastien-prudhomme! 🎉 

Feel free to open a PR to add it to the related projects of our README if you'd like, but agreed further discussion should happen over there :)
