### ISSUE TITLE
is getAncestorHash in healthcheck relevent as implemented yet ?

### ISSUE THREAD

**Issue by jfmou** [GoogleChrome/lighthouse-ci#485]
I'm having little trouble understanding the point of [this check](https://github.com/GoogleChrome/lighthouse-ci/blob/008b081caa7fda4e21da54a34d4c5293f3636929/packages/cli/src/healthcheck/healthcheck.js#L85) which fails on my pipeline most of the time. 
We do "merge with commit" our feature branches into develop then develop into master.
The base branch for our repo in our lhci server is develop.

When auditing our feature branches or freshly merged develop with lhci the check systematicaly fails since [`baseBranch` isn't set](https://github.com/GoogleChrome/lighthouse-ci/blob/8951394faa4a2ffaeba145548ab8fb4a279c886e/packages/utils/src/build-context.js#L328), resulting in  [`getAncestorHashForBranch` using master as default branch](https://github.com/GoogleChrome/lighthouse-ci/blob/8951394faa4a2ffaeba145548ab8fb4a279c886e/packages/utils/src/build-context.js#L302) which is not present as an ancestor of develop (nor the feature branches).

Uploads never failed that said, since the implementation seems more robust, requesting server data for baseBranch : https://github.com/GoogleChrome/lighthouse-ci/blob/0c5db087c9f9c279dbaa2d86197f2c7948810e22/packages/cli/src/upload/upload.js#L399-L409

It doesn't fail the job and is only a warning, but it triggers me on the check itself and what to expect about it, since it always assume master is an ancestor.
I guess It would never failed if we did used fast forward merge strategy right ? Making master and develop always an ancestor of the feature branch.

I may be missing something here, but when i audit our master it succeeds, making me think I have a good lead. 
Any ideas ?

**Comment by patrickhulce** [comment]
Thanks for filing @jfmou! You're right we should be threading through the baseBranch into the getAncestorHash function instead of hardcoding `master` there :)

https://github.com/GoogleChrome/lighthouse-ci/blob/0449e6e0d16d3a54118ee1d603dac744e601dafc/packages/utils/src/build-context.js#L319-L329

We'll need to make the same project API request to fetch the `baseBranch`

**Comment by jfmou** [comment]
Well glad to help ! Thanks for your feedback. Love this product 🥇
