### ISSUE TITLE
Enhancement: Make authentication mechanism extensible

### ISSUE THREAD

**Issue by LukeLeber** [GoogleChrome/lighthouse-ci#494]
I have a use-case where I would be required to protect the web application with Single Sign On to meet enterprise security requirements.

It seems that the only available mechanism is currently basic-auth.  Is there a way to expand this to be more flexible and allow more secure mechanisms to be utilized?  https://github.com/jaredhanson/passport immediately comes to mind and ships with a variety of authentication strategies.

Thanks for your consideration!

**Comment by patrickhulce** [comment]
Thanks for filing @LukeLeber! 

We do export the server creation as a node module, so you could add whatever middleware you like (such as passport with an SSO strategy). The key problem has always been enabling the CLI to still submit the data it needs to and keeping *its* interactions authenticated. If you'd like to add anything about your use case to https://github.com/GoogleChrome/lighthouse-ci/issues/391#issuecomment-723672281 that might help shape potential future extensibility of auth mechanisms, it'd be much appreciated 👍 

As-is though I think we consider this partially solved by exposing the server in node + the extra headers option from CLI or a duplicate of #391 depending on the specific ask.
