### ISSUE TITLE
Issue where lhci collect fails after the first run

### ISSUE THREAD

**Issue by delrey1** [GoogleChrome/lighthouse-ci#495]
Hi,

This has left me a bit stumped in understand what the problem is. The error I'm receiving is as follows: (Runs first time, fails second)
```
Running Lighthouse 3 time(s) on https://x.x.x.x/?site=company
lh_agent_1  | Run #1...done.
lh_agent_1  | Run #2...failed!
lh_agent_1  | Error: Lighthouse failed with exit code 1
lh_agent_1  |     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/@lhci/cli/src/collect/node-runner.js:119:21)
lh_agent_1  |     at ChildProcess.emit (events.js:315:20)
lh_agent_1  |     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
lh_agent_1  | {
lh_agent_1  |   "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/86.0.4240.111 Safari/537.36",
lh_agent_1  |   "environment": {
lh_agent_1  |     "networkUserAgent": "",
lh_agent_1  |     "hostUserAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/86.0.4240.111 Safari/537.36",
lh_agent_1  |     "benchmarkIndex": 1157.5,
lh_agent_1  |     "credits": {}
lh_agent_1  |   },
lh_agent_1  |   "lighthouseVersion": "6.4.1",
lh_agent_1  |   "fetchTime": "2020-11-17T18:36:22.001Z",
lh_agent_1  |   "requestedUrl": "https://x.x.x.x/?site=company",
lh_agent_1  |   "finalUrl": "https://x.x.x.x/?site=company",
lh_agent_1  |   "runWarnings": [
lh_agent_1  |     "Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests. (Details: net::ERR_CERT_AUTHORITY_INVALID)"
lh_agent_1  |   ],
lh_agent_1  |   "runtimeError": {
lh_agent_1  |     "code": "FAILED_DOCUMENT_REQUEST",
lh_agent_1  |     "message": "Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests. (Details: net::ERR_CERT_AUTHORITY_INVALID)"
lh_agent_1  |   },
...
```

Now you would assume it's a simple issue with the cert, however I'm running this with NODE_TLS_REJECT_UNAUTHORIZED = 0 to reach the self-signed lhci server as well as using puppeteer with the following in my lighthouse config

```
{
  "ci": {
    "collect":{
      "url": ["https://x.x.x.x/?site=company"],
      "puppeteerScript": "puppeteer/home-page-script.js",
      "puppeteerLaunchOptions": {"ignoreHTTPSErrors":true, "defaultViewport": null, "args":["--disable-gpu --window-size=1920,1080", "--no-sandbox"], "headless": true}
    },
    "upload": {
      "target": "lhci",
      "serverBaseUrl": "https://...:9003",
      "token":"..."
    }
  }
}
```

In addition to the first request round working...!

This issue also happens on my local (+ running without docker). When it fails, it seems to hang, but I can't seem to get puppeteer to run non-headlessly so I can visibly see what on earth is going on

Puppeteer script is beyond basic
```
module.exports = async (browser, {url}) => {
    console.log(1);
    const page = await browser.newPage();
    await page.setViewport({ width: 1920, height: 1080 });
    await page.goto(url);
    await page.close();
};
```

I'm unsure on what I can do to debug this further, I can't seem to run this in a verbose mode, it works "intermittently" one of three times. The website itself is reachable without any issues (Sometimes the first page hangs if it hasn't been reached in a while). I've been told there's nothing inbetween the node running lhci and the web app itself with regards to throttling etc

Also can't get puppeteer to run non-headlessly, removing headless option or setting to false keeps it running as headless with no error (Running on Windows, and this machine has run puppeteer in non headless mode in the past but not in combination with lhci)

Would be grateful for any ideas!
Thanks!

**Comment by delrey1** [comment]
Realised the headless issue, need to use `collect --headful` (My mistake!)

Saw a potential problem, will look into into it and add an update

**Comment by delrey1** [comment]
Looks like it's an issue with how I'm running with puppeteer, thought I had tried this beforehand.

Will close for now, but in short what I did (besides using github as a rubber duck)

`collect --headful` to run with the UI
Showed that I needed `--ignore-certificate-errors` on the chrome flags (I also removed puppeteer usage - Will need to revisit this anyway)

Very odd?

**Comment by patrickhulce** [comment]
Glad you figured it out :)

Yes you also need `--ignore-certificate-errors` and not just `NODE_TLS_REJECT_UNAUTHORIZED`.

`NODE_TLS_REJECT_UNAUTHORIZED` covers *LHCI* connecting to an unauthorized server, but doesn't cover *Chrome* connecting to an unauthorized server.

`--ignore-certificate-errors` covers *Chrome* connecting to an unauthorized server, but doesn't cover LHCI :)
