### ISSUE TITLE
Lighthouse doesn't open up the page in desktop mode

### ISSUE THREAD

**Issue by sashikamw** [GoogleChrome/lighthouse-ci#496]
I have configured lighthouserc.js with the below configurations, when I execute the lighthouse execution with 'lhci autorun' command in headful mode, I can see the given url (in this case facebook) loading in mobile device mode (https://m.facebook.com) rather than in desktop mode. 

 ci: {
      collect: {
        "headful": true,
        "url": ['https://www.facebook.com'],
        "disableStorageReset": true,
        "disableNetworkThrottling": true,
        "emulatedFormFactor": "desktop",
        "internalDisableDeviceScreenEmulation": true,
      },

May I know how can I configure lighthouse to execute the audit in desktop mode of my web application?

**Comment by patrickhulce** [comment]
Please see https://github.com/GoogleChrome/lighthouse-ci/blob/master/docs/configuration.md#desktop-emulation
