### ISSUE TITLE
Upload target filesystem not working 

### ISSUE THREAD

**Issue by ashishkshrivastava** [GoogleChrome/lighthouse-ci#498]
Hi 
I am not sure whether this is an issue or I am doing the wrong configuration. Requesting you to guide me. I am trying to save the report in my GitLab repository folder (**reports**) to do further some comparison with the newly generated report.
Below is what script I added.

**.gitlab-ci.yml**
image: cypress/browsers:node10.16.0-chrome77
run_lighthouse:
  variables:
    LIGHTHOUSE_TEST_URL: https://www.example.com
  stage: deploy
  environment: Test
  only:
    - master
  script:
    - npm install -g @lhci/cli@0.3.x
    - lhci autorun --upload.target=filesystem --collect.settings.chromeFlags="--no-sandbox" --collect.numberOfRuns=1 || echo "LHCI failed!" --output-dir= ./reports --report-filename-pattern="%%HOSTNAME%%-%%PATHNAME%%-%%DATETIME%%.report.%%EXTENSION%%"
      
  artifacts:
    paths:
      - .lighthouseci/
    expire_in: 1 week

And in **lighthouserc.js**

module.exports = {
  ci: {
    collect: {
      url: ["https://www.example.com"],
      settings: { chromeFlags: "--no-sandbox" },
      emulatedFormFactor: "desktop",
    },
    upload: {
      target: "filesystem",
      outputDir: "./reports",
      reportFilenamePattern: "%%HOSTNAME%%-%%PATHNAME%%-%%DATETIME%%.report.%%EXTENSION%%"
    },
  },
};
  When I am running the pipeline ,I am getting below error.
**Invalid values:
  Argument: target, Given: "filesystem", Choices: "lhci", "temporary-public-storage"**

**Comment by patrickhulce** [comment]
Thanks for filing!

> npm install -g @lhci/cli@0.3.x

This is a very old version of LHCI. Use the latest `@0.6.x` :)
