### ISSUE TITLE
Docs guardrails for what not to assert against

### ISSUE THREAD

**Issue by exterkamp** [GoogleChrome/lighthouse-ci#50]
Minimal repro:
```json
{
  "ci": {
    "assert": {
      "preset": "lighthouse:recommended",
      "assertions": {
        "critical-request-chains": ["warn", {"minScore": 1}]
      }
    }
}
```

This leads to:
```txt
  ⚠️  critical-request-chains warning for minScore assertion
     Minimize Critical Requests Depth
     Documentation: https://web.dev/critical-request-chains

        expected: >=1
           found: 0
      all values: 0, 0, 0
```

**Comment by patrickhulce** [comment]
I'm not sure what the bug report is @exterkamp :)

You specified that you wanted to warn when the `critical-request-chains` audit did not score a 1 and that's what we did. It's definitely not very useful to warn on the critical request chains audits, that's why they're `off` in the recommended preset.

**Comment by paulirish** [comment]
oh i think this is actually about informative/notApplicable audits as their score is `null`

and minScore doesn't really match up with `null`, so it's confusing

i guess you should get a warning that seeing minscore on informative audits doesnt make sense?
and minScore applied on notApplicable is just kinda ignored?  i dunno

**Comment by patrickhulce** [comment]
Well with diagnostic audits I took the approach that we do for display in the report. If it's `informative` it's "failing" and a 0 for score purposes. If it's `notApplicable` it's "passing" and a 1 for score purposes. Basically...

`notApplicable` === `score: 1`
`informative` === `score: 0`

That feels pretty consistent to the attitude taken within the audits themselves that notApplicable is passing and anything else is failure. If we didn't take this approach, what would be the proposal for how to assert against diagnostic audits?

**Comment by exterkamp** [comment]
Hm...I'm unconvinced. I definitely think that this should be handled as a error of some sort like you said. But I think it should be more obvious that this is a terminal error. Since writing this config is always wrong (e.g. writing this is always a mistake):
```json
"critical-request-chains": ["warn | error", {"minScore": 1}]
```

So I would want this to fail with an error more like this:
```
  ⚠️  critical-request-chains warning for minScore assertion
     Minimize Critical Requests Depth
     Documentation: https://web.dev/critical-request-chains

        expected: >=1
           found: 0
      all values: 0, 0, 0
 ❌  ERROR: Asserting a `minScore` against an `informative` audit will never pass. Check you lighthouserc.
```

This should tell the user that they messed up the config, not just that the audit isn't passing, because if the user _is_ writing this, then they probably can't debug it to find out why it's erroring.

This could maybe fail a `healthcheck` since this is never an assertion that is valid.

**Comment by patrickhulce** [comment]
> ERROR: Asserting a `minScore` against an `informative` audit will never pass. Check you lighthouserc.

This isn't true though. An informative audit will be marked `notApplicable` when it passes and your `minScore` assertion will pass as well.

**Comment by patrickhulce** [comment]
We decided in person that we'll just add some recipes for how to extend the presets
