### ISSUE TITLE
Flags file cleanup failure

### ISSUE THREAD

**Issue by PJHRobles** [GoogleChrome/lighthouse-ci#500]
We have integrated lighthouse in our CI pipeline and run them on a number of URLs. In order to reduce the time for the workflow, we decided to do concurrent runs. We're aware that it might introduce variability and we're fine with that (the instances we run lighthouse on are good enough that we don't observe a lot of variability). The concurrent runs reduced the time by half. However, we're currently encountering the error below:
```
internal/fs/utils.js:454
    throw err;
    ^

Error: ENOENT: no such file or directory, unlink '/root/gaf/webapp/.lighthouseci/flags-2516.json'
    at Object.unlinkSync (fs.js:991:3)
    at cleanupFn (/root/gaf/webapp/node_modules/@lhci/cli/src/collect/node-runner.js:55:28)
    at ChildProcess.<anonymous> (/root/gaf/webapp/node_modules/@lhci/cli/src/collect/node-runner.js:87:7)
    at ChildProcess.emit (events.js:196:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:257:12)
```

I am guessing that it might be because of how the filenames are generated. Since the random string generation is simple, it is possible that two processes could watch the same file. When the file gets cleaned up by the first process, the second process will fail. I have not confirmed the issue and this is just a guess so feel free to correct me if I'm wrong. This doesn't happen often but any help is appreciated. Thanks!

https://github.com/GoogleChrome/lighthouse-ci/blob/v0.6.1/packages/cli/src/collect/node-runner.js#L64 
```
      const flagsFilename = `flags-${Math.round(Math.random() * 10000)}.json`;
      const flagsFilePath = path.join(getSavedReportsDirectory(), flagsFilename);
      lhArgs.push('--cli-flags-path', flagsFilePath);

      fs.writeFileSync(flagsFilePath, JSON.stringify(settings));
      cleanupFn = () => fs.unlinkSync(flagsFilePath);
```

**Comment by patrickhulce** [comment]
Thanks for filing @PJHRobles! 

I believe you're right in diagnosing the issue. We didn't really want to support parallel runs to be honest :/

I understand if you have more capable infra though why you would want to do this (or for anyone not actually using the performance metric scores). We'd be open to a PR that fixes this random flags issue (with a unique `tmp` directory for each run perhaps?), though I imagine there might be other demons lurking about in the future :)
