### ISSUE TITLE
Upgrading from 0.4.0 -> 0.6.1 throws 503 on customer server

### ISSUE THREAD

**Issue by jflayhart** [GoogleChrome/lighthouse-ci#507]
**Describe the bug**
After upgrading @lhci/server from 0.4.0 -> 0.6.1, I get 503s when trying to go to project build comparison pages:

```
Lighthouse CI Server Error

Navigated to .../app/projects/next-staging/compare/ce13738ba1a0
api-client.js:119 GET .../v1/projects/ed88b4cf/builds/ce13738b/runs?representative=true 503
_get @ api-client.js:119
getRuns @ api-client.js:305
(anonymous) @ use-api-data.jsx:93
(anonymous) @ use-api-data.jsx:85
F @ index.js:267
q @ index.js:254
(anonymous) @ index.js:217
h @ index.js:214
setTimeout (async)
t @ index.js:232
setTimeout (async)
(anonymous) @ index.js:234
x @ index.js:235
a @ index.js:112
l @ use-api-data.jsx:81
j @ use-api-data.jsx:233
v @ build-view.jsx:216
L @ index.js:337
U @ index.js:119
x @ component.js:116
Promise.then (async)
g @ component.js:174
y.setState @ component.js:41
r.__c.r.v @ index.js:90
(anonymous) @ use-api-data.jsx:96
async function (async)
(anonymous) @ use-api-data.jsx:93
(anonymous) @ use-api-data.jsx:85
F @ index.js:267
q @ index.js:254
(anonymous) @ index.js:217
h @ index.js:214
setTimeout (async)
t @ index.js:232
requestAnimationFrame (async)
(anonymous) @ index.js:235
x @ index.js:235
a @ index.js:112
l @ use-api-data.jsx:81
x @ use-api-data.jsx:176
v @ build-view.jsx:214
L @ index.js:337
U @ index.js:119
x @ component.js:116
Promise.then (async)
g @ component.js:174
y.setState @ component.js:41
r.__c.r.v @ index.js:90
(anonymous) @ use-api-data.jsx:96
async function (async)
(anonymous) @ use-api-data.jsx:93
(anonymous) @ use-api-data.jsx:85
F @ index.js:267
q @ index.js:254
(anonymous) @ index.js:217
h @ index.js:214
setTimeout (async)
t @ index.js:232
requestAnimationFrame (async)
(anonymous) @ index.js:235
x @ index.js:235
a @ index.js:112
l @ use-api-data.jsx:81
p @ use-api-data.jsx:141
v @ build-view.jsx:212
L @ index.js:337
U @ index.js:119
```

**To Reproduce**
This is using a custom LHCI server running PG DB.

1. Run LHCI server using @lhci/server 0.4.0 with postgres DB, project is created and has data
2. Upgrade @lhci/server to 0.6.1
3. Go to Dashboard (works fine), then try to click on a point to get CI Diff:
<img width="542" alt="Screen Shot 2020-12-12 at 1 04 47 PM" src="https://user-images.githubusercontent.com/6808172/101992654-9e090500-3c7a-11eb-9a7e-01a652653232.png">

4. See error after clicking on "CI Diff"
<img width="612" alt="Screen Shot 2020-12-12 at 1 08 41 PM" src="https://user-images.githubusercontent.com/6808172/101992766-2a1b2c80-3c7b-11eb-8707-03d24de159c5.png">

**Expected behavior**
I should see the build diff view normally, since 0.4.0 worked.

**Environment (please complete the following information):**
 - OS: Mac Catalina
 - Browser Chrome
 - Version 86

Also here are the server logs after successfully running server:
```
Server listening on port 9001
2020-12-12T18:44:55.425Z - socket timed out
12:44:55.436 lighthouse-server-webserver 2020-12-12T18:44:55.436Z - socket timed out
12:44:55.443 lighthouse-server-webserver 2020-12-12T18:44:55.443Z - socket timed out
12:44:55.677 lighthouse-server-webserver 2020-12-12T18:44:55.677Z - socket timed out
12:44:56.014 lighthouse-server-webserver 2020-12-12T18:44:56.014Z - socket timed out
```

**Comment by jflayhart** [comment]
I also can't upload to the LHCI server now :( same error:

```
Error: Unexpected status code 503
  upstream connect error or disconnect/reset before headers. reset reason: connection termination
    at ApiClient._convertFetchResponseToReturnValue (/home/circleci/project/node_modules/@****/utils/src/api-client.js:78:21)
WARNING: upload command failed.
```

**Comment by jflayhart** [comment]
Welp. Turns out something started requiring more memory and CPU, so I upped my server resources and all is well. 👍🏻

**Comment by patrickhulce** [comment]
Thanks for filing @jflayhart! Glad you found a solution. The 503 is likely coming from the service provider directly, I'm guessing that either the new database indexes or if you're using any of the new cron job functionality could have triggered the need for more resources.

If you figure out more details, definitely share :)
