### ISSUE TITLE
How do I run "lhci wizard" in the Docker container?

### ISSUE THREAD

**Issue by ptmkenny** [GoogleChrome/lighthouse-ci#508]
I am attempting to set up the Docker server as [described in the documentation](https://github.com/GoogleChrome/lighthouse-ci/blob/master/docs/server.md#docker) but I don't understand how I am supposed to run `lhci wizard`.

I added the container to my machine according to the documentation and visited `http://localhost:9001/app`, which instructed me to run `lhci wizard`.

So I ran `docker ps` to get the container ID, then `docker exec -it CONTAINER_ID /bin/bash` to get a shell inside the container, and then ran `lhci wizard`, but this gave me the error:

`bash: lhci: command not found`

What's the correct way to run this command from within Docker?

**Comment by patrickhulce** [comment]
Thanks for filing @ptmkenny! You might find the [getting started docs](https://github.com/GoogleChrome/lighthouse-ci/blob/master/docs/getting-started.md#project-creation) helpful which explain the flow here.

> What's the correct way to run this command from within Docker?

You don't need to to run it within docker for project creation. You can run `lhci wizard` to create a new project from anywhere you have access to the server, i.e. outside of the container and on your local machine `http://localhost:9001`

**Comment by ptmkenny** [comment]
Ok, thanks! I had read the getting started docs, but I didn't realize I needed to run the command from the cli instead of the server.

**Comment by kdalkafoukis** [comment]
> I am attempting to set up the Docker server as [described in the documentation](https://github.com/GoogleChrome/lighthouse-ci/blob/master/docs/server.md#docker) but I don't understand how I am supposed to run `lhci wizard`.
> 
> I added the container to my machine according to the documentation and visited `http://localhost:9001/app`, which instructed me to run `lhci wizard`.
> 
> So I ran `docker ps` to get the container ID, then `docker exec -it CONTAINER_ID /bin/bash` to get a shell inside the container, and then ran `lhci wizard`, but this gave me the error:
> 
> `bash: lhci: command not found`
> 
> What's the correct way to run this command from within Docker?

you can run `npx lhci wizard`
