### ISSUE TITLE
Lighthouse v7.0.0

### ISSUE THREAD

**Issue by Seirdy** [GoogleChrome/lighthouse-ci#517]
Lighthouse [v7.0.0](https://github.com/GoogleChrome/lighthouse/releases/tag/v7.0.0) was released a week ago. It made it into Chromium [yesterday](https://chromium.googlesource.com/chromium/src/+/568936b0fd000d3dae8e9cf03d18b7f20086e477).

The release notes include a feature that could be quite useful for a CI program running in an environment with unpredictable performance:

> Lighthouse runs a small benchmark at startup, and will now include a warning if the [test machine appears underpowered](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md#cpu-throttling) and may be affecting the accuracy of the Lighthouse metrics ([#11350](https://github.com/GoogleChrome/lighthouse/pull/11350))

This is a major release with quite a few breaking changes.

**Comment by patrickhulce** [comment]
Thanks for filing @Seirdy! We'll be updating LHCI for v7 pretty soon :)
