### ISSUE TITLE
Why is upload after assert?

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse-ci#52]
If I'm doing TPS (temp public storage) I kinda want to see that report more than I want assertions. 

I feel like upload should precede assert in autorun, but I see the docs specifically say to upload _after_ assert..... why? :)

**Comment by patrickhulce** [comment]
Because the status checks need the results of the assertions. 

I'm confused how it matters to the user if autorun chooses to run assert first though :) You'll still get the report uploaded either way and the assert command only takes like a few seconds to run tops.

**Comment by paulirish** [comment]
status checks! right yes.

to autorun it doesnt matter a lot.. just that i didnt know why at the time? but the statuschecks bit totally justifies that.

the aspect of calling it out in the docs is a little more awkward but this makes sense to me, yup.
