### ISSUE TITLE
Heroku server responding with LHCI server not API-compatible (Improve debug logging)

### ISSUE THREAD

**Issue by GreedyA1** [GoogleChrome/lighthouse-ci#522]
So I have been stuck on this issue for weeks now. I can't get heroku + circleCI work. I am getting the same error every time.

```
#!/bin/bash -eo pipefail
lhci autorun
✅  .lighthouseci/ directory writable
✅  Configuration file found
✅  Chrome installation found
✅  GitHub token set
⚠️   Ancestor hash not determinable
✅  LHCI server reachable
⚠️   LHCI server not API-compatible
⚠️   LHCI server token invalid
✅  LHCI server unique build for this hash
Healthcheck passed!

Running Lighthouse 3 time(s) on https://dges.app/
Run #1...done.
Run #2...done.
Run #3...done.
Done running Lighthouse!

Error: Could not find active project with provided token
    at runLHCITarget (/usr/local/share/.config/yarn/global/node_modules/@lhci/cli/src/upload/upload.js:401:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.runCommand (/usr/local/share/.config/yarn/global/node_modules/@lhci/cli/src/upload/upload.js:592:16)
    at async run (/usr/local/share/.config/yarn/global/node_modules/@lhci/cli/src/cli.js:109:7)
WARNING: upload command failed.
Done running autorun.
```

My heroku server url is https://limitless-lowlands-77781.herokuapp.com/app/projects .
I have checked the limited logs on heroku and I see heroku is returning  404-s to POST /v1/projects/lookup calls.

this is how my .lighthouserc.js looks like. 

```
module.exports = {
  ci: {
    collect: {
      numberOfRuns: 3,
      url: ['https://dges.app/'],
      // staticDistDir: './dist/apps/dges-front/',
    },
    upload: {
      target: 'lhci',
      serverBaseUrl: 'https://limitless-lowlands-77781.herokuapp.com',
      token: 'cd36d33e-f72a-46db-ab2c-3bce75b07741', // could also use LHCI_TOKEN variable instead
    },
  },
};
```

I have experimented with using environment variables and I also ended up hardcoding the token. but none help. 
https://github.com/GreedyA1/dges is the github project I am working on. Please help out. can't pass this issue for weeks now.

**Comment by patrickhulce** [comment]
Thanks for filing @GreedyA1!

You're getting this error because the version of the client and the version of the server you are using are not compatible.

You're installing v0.6.x in Circle but trying to save the results to a server running v0.4.x (see https://limitless-lowlands-77781.herokuapp.com/version). Either upgrade the server to 0.6.x or downgrade the client to 0.4.x.

**Comment by GreedyA1** [comment]
Thanks for the response. That solved the issue partially.

⚠️   Ancestor hash not determinable
⚠️   LHCI server token invalid

errors are still up. **⚠️   LHCI server token invalid** is most concerning for me. I created 2nd app called dgess instead of dges, to make sure I didn't get the tokens wrong. but they should both be correct.

**Comment by patrickhulce** [comment]
@GreedyA1 the token that is currently hard-coded on the develop branch of the repo does not appear to be valid (`curl -X POST -H 'Content-Type: application/json' -d '{"token": "f683817f-3fa7-49d1-88ce-e8fe6679c8a8"}' https://limitless-lowlands-77781.herokuapp.com/v1/projects/lookup` returns nothing), but the one you have in a comment here should be working. Is that what you're seeing?

Note that you can also manually get the database URL out from heroku and run `lhci wizard` in your local setup to reset the build token if something has gone wrong with a copy/paste along the way.

**Comment by GreedyA1** [comment]
@patrickhulce I did change the token back to the original. sorry was experimenting and changed the token to ID, just in case. but none work. I reinstalled the LHCI server on heroku and that didn't help either. at the end I ran lhci autorun from local and that works perfectly fine. 

```
 lhci autorun
✅  .lighthouseci/ directory writable
✅  Configuration file found
✅  Chrome installation found
⚠️   GitHub token not set
✅  Ancestor hash determinable
✅  LHCI server reachable
✅  LHCI server API-compatible
✅  LHCI server token valid
✅  LHCI server unique build for this hash
Healthcheck passed!

Running Lighthouse 3 time(s) on https://dges.app/
Run #1...done.
Run #2...done.
Run #3...done.
Done running Lighthouse!

Saving CI project dges (a68f15f3-8da9-4178-a0d0-9a88c1119fe5)
Saving CI build (09f83e72-192b-4fa6-8018-d4af6303d531)
Saved LHR to https://morning-ravine-50826.herokuapp.com/ (efba20e6-28d7-4cec-b30a-a91bb1c3a756)
Saved LHR to https://morning-ravine-50826.herokuapp.com/ (36e42ad3-21dd-4505-9982-6454b996ea5e)
Saved LHR to https://morning-ravine-50826.herokuapp.com/ (e5c71ee9-3e32-4b4a-8425-c51e55b3cd01)
Done saving build results to Lighthouse CI
View build diff at https://morning-ravine-50826.herokuapp.com/app/projects/dges/compare/09f83e72-192b-4fa6-8018-d4af6303d531
No GitHub token set, skipping GitHub status check.
```

I realized the issue is in CircleCI. any Ideas why that might be an issue? the same build is failing with errors above in circleCI and the ⚠️   **LHCI server not API-compatible** errors is back even though they are the same versions.

**Comment by patrickhulce** [comment]
@GreedyA1 it looks like you've set environment variables for these LHCI properties in addition to setting in a `lighthouserc.js`. 

![image](https://user-images.githubusercontent.com/2301202/103788522-87996380-5004-11eb-9f3f-aa4f6d84da9f.png)


My best guess is that these are conflicting (and with switching tokens + heroku projects are likely mismatched). Just pick one method and print out the values you  think you should be using in the logs, this is a great feature request for more debug logging in LHCI to make this easier for you to debug :)

**Comment by GreedyA1** [comment]
You were absolutely right. The environment variables were conflicting. Thanks for help. great work! 
I do agree on improving logging for debugs. It was confusing finding out what was wrong.
![image](https://user-images.githubusercontent.com/18186211/103929906-62594200-5137-11eb-955d-ffccc7092980.png)
