### ISSUE TITLE
HTTPS audit fails with 'Audits.enable' protocol error

### ISSUE THREAD

**Issue by rbardini** [GoogleChrome/lighthouse-ci#528]
**Describe the bug**
When running LHCI on a set of (internal) HTTPS pages, all of them report a strange HTTPS error, even though they are securely served with no mixed content.

**To Reproduce**
1. Run `lhci autorun` on HTTPS page
2. Open report from LHCI server
3. Scroll down to _Best Practices_ section
5. See _Uses HTTPS_ error

**Expected behavior**
No HTTPS error.

**Logs/Screenshots**

Logs:
![](https://user-images.githubusercontent.com/874370/104316885-6b526680-54dd-11eb-8cc9-face8857a1b3.png)

Error on report:
![](https://user-images.githubusercontent.com/874370/104316676-1dd5f980-54dd-11eb-9037-2bdf705eb386.png)

**Environment (please complete the following information):**
 - OS: Alpine v3.11 ([Dockerfile](https://github.com/Travix-International/docker-npm-browser-agent/blob/erbium-alpine/Dockerfile))
 - Browser: Chromium 81.0.4044.113-r0
 - Dependencies: @lhci/cli@0.6.1, puppeteer-core@5.5.0

**Additional context**
Different approaches have been tried (e.g. use Chrome binary from `puppeteer`; install dependencies globally, locally), but the result is always the same. Puppeteer launched with `--no-sandbox` and a script to skip a cookie dialog.

Other audits look fine, including HTTPS redirects:

![](https://user-images.githubusercontent.com/874370/104333437-83cc7c00-54f1-11eb-9b52-f3599fc32a3c.png)

**Comment by patrickhulce** [comment]
Thanks for filing @rbardini! 

This error means the chromium version LHCI used is too old (`Audits.enable not found` means that Chrome didn't recognize the command Lighthouse was giving it). You're welcome to take a look at [the official LHCI client dockerfile](https://github.com/GoogleChrome/lighthouse-ci/blob/master/docs/recipes/docker-client/Dockerfile) for examples but further debugging support is beyond the scope of GitHub issues. Feel free to open a *discussion* if you have trouble matching the official docker image behavior :)

**Comment by rbardini** [comment]
Thanks @patrickhulce! Moving from Alpine v3.11 to v3.12 (with Chromium 86) fixed it 👍
