### ISSUE TITLE
How to handle error while running lighthouse for multiple URLs

### ISSUE THREAD

**Issue by sansunsunsan** [GoogleChrome/lighthouse-ci#529]
I am running lighthouse on multiple URLs, out of that couple of URLs fails due to some error like timeout error or 500 status code, 403 ..etc
So lighthouse exits with code 0 and uploading fails.

Is there any way we can upload partial success reports to LHCI server?

Below is the error we get while running lighthouse
```
18:00:00  Running Lighthouse 1 time(s) on https://somedomain.com/1
18:01:30  Run #1...done.
18:01:43  Running Lighthouse 1 time(s) on https://somedomain.com/2
18:02:26  Run #1...done.
18:02:49  Running Lighthouse 1 time(s) on https://somedomain.com/3
18:03:28  Run #1...failed!
18:03:28  Error: Lighthouse failed with exit code 1
18:03:28      at ChildProcess.<anonymous> (/node_modules/@lhci/cli/src/collect/lighthouse-runner.js:103:21)
18:03:28      at ChildProcess.emit (events.js:314:20)
18:03:28      at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
18:03:28  {
18:03:28    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36",
18:03:28    "environment": {
18:03:28      "networkUserAgent": "",
18:03:28      "hostUserAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36",
18:03:28      "benchmarkIndex": 16
18:03:28    },
18:03:28    "lighthouseVersion": "5.5.0",
18:03:28    "fetchTime": "2021-01-12T12:33:12.727Z",
18:03:28    "requestedUrl": "https://somedomain.com/3",
18:03:28    "finalUrl": "https://somedomain.com/3",
18:03:28    "runWarnings": [
18:03:28      "Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests. (Status code: 500)"
18:03:28    ],
18:03:28    "runtimeError": {
18:03:28      "code": "ERRORED_DOCUMENT_REQUEST",
18:03:28      "message": "Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests. (Status code: 500)"
18:03:28    },

```

**Comment by patrickhulce** [comment]
> Is there any way we can upload partial success reports to LHCI server?

Instead of running all of it in one shot you could instead invoke `lhci collect --additive` repeatedly and then `lhci upload` after the first failure (or whatever condition you like). The behavior to fail loudly when the server can't be reached is intentional and unlikely to change, so piecing together your own custom flow with individual commands would be my recommendation :)

**Comment by sansunsunsan** [comment]
> > Is there any way we can upload partial success reports to LHCI server?
> 
> Instead of running all of it in one shot you could instead invoke `lhci collect --additive` repeatedly and then `lhci upload` after the first failure (or whatever condition you like). The behavior to fail loudly when the server can't be reached is intentional and unlikely to change, so piecing together your own custom flow with individual commands would be my recommendation :)

All my configuration is in "**.lighhouse.rc**" file, is there any way that  i can inject any kind of middleware and handle error  scenarios there? If yes, can u give me any example for that ? if No, how can i achieve the above mentioned solution from the configuration file(**.lighhouse.rc**)

**Comment by patrickhulce** [comment]
You can't achieve the specific behavior you want *just* from the configuration file. `autorun` is meant for the majority of common use cases but when you'd like any custom logic like what you're talking about here, that's what the individual commands for each step are there for :)

**Comment by sansunsunsan** [comment]
Understood your point.
But can't we have any future scope of adding some script within the configuration file that can handle these kind of scenarios?
Does it make sense ? 

Similar to puppeteer script, that we inject inside configuration , which executes before lighthouse run.

**Comment by patrickhulce** [comment]
We have [many proposed hooks](https://github.com/GoogleChrome/lighthouse-ci/issues/438) along the lines of what I think you're asking for, but none I can foresee that would handle arbitrary catching of fatal errors such as this one in a way that allows LHCI to continue as normal. 

If you have a proposal for a specific hook into LHCI you'd like to see and how it would work, please feel free to add details in #438 :)

(FWIW, this situation alone wouldn't be enough to justify it. As I currently understand it, what you want to do is already easily accomplished with ~3 lines of a bash script whereas the compelling examples in #438 are currently impossible)
