### ISSUE TITLE
Incorrect documentation around desktop emulation

### ISSUE THREAD

**Issue by domharrington** [GoogleChrome/lighthouse-ci#537]
**Describe the bug**
The docs [here](https://github.com/GoogleChrome/lighthouse-ci/blob/44c4e7dd15877d32073c15f7f4084918eb14e9b5/docs/configuration.md#desktop-emulation) say you can do the following to emulate a desktop machine:

```json
{
  "ci": {
    "collect": {
      "settings": {
        "preset": "desktop"
      }
    }
  }
}
```

But when I do this I get the following error:

```sh
Run #1...failed!
Error: Lighthouse failed with exit code 1
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/@lhci/cli/src/collect/node-runner.js:119:21)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
Invalid values:
  Argument: preset, Given: "desktop", Choices: "perf", "experimental"

Specify --help for available options
```

Is that error referring to the documentation here? https://github.com/GoogleChrome/lighthouse-ci/blob/44c4e7dd15877d32073c15f7f4084918eb14e9b5/docs/configuration.md#preset 

Is there a way to use the presets in this module to emulate a desktop environment? Or do I have to do this:

```json
{
  "ci": {
    "collect": {
      "settings": {
        "emulatedFormFactor": "desktop"
      }
    }
  }
}
```

**To Reproduce**
1. Follow instructions for desktop emulation https://github.com/GoogleChrome/lighthouse-ci/blob/44c4e7dd15877d32073c15f7f4084918eb14e9b5/docs/configuration.md#desktop-emulation
2. Run a build (`lhci autorun`)
3. See error from above ^^

**Expected behavior**
Build should work and run lighthouse using desktop machine.

**Logs/Screenshots**
n/a

**Environment (please complete the following information):**
 - OS: macOS
 - Browser: chrome lighthouse
 - Version: latest?

**Additional context**
n/a

**Comment by patrickhulce** [comment]
Thanks for filing @domharrington! Are you looking at the docs on main branch? Those are for Lighthouse v7 / LHCI 0.7.0 which has yet to be published, but will be published soon (this week).

**Comment by domharrington** [comment]
Thanks for the quick response! I dont remember how I got to them specifically, but it also advises the same on master too: https://github.com/GoogleChrome/lighthouse-ci/blob/master/docs/configuration.md#desktop-emulation - is this correct?

I love this project by the way, thanks for your work on it. The docs for setting up on heroku and configuring everything else have been perfect 👌

**Comment by domharrington** [comment]
I'm on 0.6.1 if that helps:

```
$ lhci --version
0.6.1
```

**Comment by patrickhulce** [comment]
Glad to hear it! Yeah I'm saying that the version on master hasn't been published to npm yet :) if you're using 0.6.1 you can take a look at [the 0.6.1 docs](https://github.com/GoogleChrome/lighthouse-ci/blob/v0.6.1/docs/configuration.md#desktop-emulation)

**Comment by domharrington** [comment]
Got it! I tried to search for a v0.6 branch but I should've gone to view the docs from that tag. Ended up doing this and it worked as intended:

```
{
  "ci": {
    "collect": {
      "settings": {
        "emulatedFormFactor": "desktop",
        "disableDeviceEmulation": true,
        "disableCpuThrottling": true,
        "disableNetworkThrottling": true,
        "throttlingMethod": "provided"
      }
    }
  }
}
```

Thank you! Looking forward to v7's release to hopefully simplify this. Will this configuration continue to work in v7?

**Comment by patrickhulce** [comment]
> Will this configuration continue to work in v7?

No the emulation flags here were changed around in Lighthouse 7, so they will need to be updated. The new desktop preset was meant to help ease that transition though :)
