### ISSUE TITLE
Puppeteer auth script not working

### ISSUE THREAD

**Issue by citypaul** [GoogleChrome/lighthouse-ci#540]
**Describe the bug**

I have a puppeteer script that logs in to my site, so I can run lighthouse against authenticated pages.

When I run this in headed mode, I see Chrome login as expected.

However, when I check the test output, all the screenshots clearly show the login page, so it's as if lighthouse has ignored the puppeteer script entirely.

**To Reproduce**

```js
const puppeteer = require("puppeteer");

const user = process.env.USER;
const password = process.env.PASSWORD;
const siteOrigin = process.env.SITE_ORIGIN;

module.exports = async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto(`${siteOrigin}/sign_in`);

  await page.type("input#user_email", user);
  await page.type("input#user_password", password);
  await page.click('input[type="submit"]');

  await page.waitForNavigation();
  await page.close();
};
```

```json
module.exports = {
  ci: {
    collect: {
      settings: {
        disableStorageReset: true,
      },
      upload: {
        target: "temporary-public-storage",
      },
      isSinglePageApplication: true,
      puppeteerScript: "./src/event.js",
      url: [
        "https://mywebsite.com/account",
      ],
    },
  },
};
```

**Expected behavior**
I would expect the lighthouse test  to test against the logged in page.

**Environment (please complete the following information):**
 - OS: Mac OS
 - Browser Chrome
 - Version 88.0.4324.96

**Additional context**
It's worth mentioning I've tried this with and without the `page.close()` step.

**Comment by patrickhulce** [comment]
Thanks for filing @citypaul! 

Please see the [example in the documentation](https://github.com/GoogleChrome/lighthouse-ci/blob/master/docs/configuration.md#puppeteerscript). You need to use the browser argument that is passed to your script. Launching your own browser means it will be using its own profile so all storage is not kept when Lighthouse runs in the browser that was passed to you. On the off chance this application is using `sessionStorage` that's the one type of storage that isn't supported by Lighthouse. (Don't forget `--settings.disableStorageReset`!)

**Comment by citypaul** [comment]
Hey @patrickhulce, thanks for your message. You responded quickly there! I had just updated my original post to include:

```
settings: {
        disableStorageReset: true,
}
```

Unfortunately, this didn't seem to work for me. I'm very new to the project I'm working on, so will check to see whether it is using session storage. Thanks.

**Comment by citypaul** [comment]
Yeah, so I just checked, and the site is using cookies to store the user token...

**Comment by patrickhulce** [comment]
> Please see the example in the documentation. You need to use the browser argument that is passed to your script. Launching your own browser means it will be using its own profile so all storage is not kept when Lighthouse runs in the browser that was passed to you. 

Did you already address this? This was the headline of my comment and *the* reason the script you provided will never work. The storage reset comment was just an extra aside.

**Comment by citypaul** [comment]
Hey @patrickhulce, thank you for your help with this!

For the record, the reason this happened was because I first created a script in puppeteer just to see that working, then copied that over to the setup I had in the ci package.

The reason I say this is it might be that other people may do the same thing, so it might be worth mentioning this in the docs - totally user error of course, but other people may go through the same thought process and potentially make the same mistake.

Thank you very much for your help - fix my issue and I can move on now, thanks! :-)

**Comment by citypaul** [comment]
So for the benefit of anyone else who stumbles up on this, here's the finished code that does now work:

```js
const puppeteer = require("puppeteer");

const user = process.env.USER;
const password = process.env.PASSWORD;
const siteOrigin = process.env.SITE_ORIGIN;

module.exports = async (browser) => {
  const page = await browser.newPage();
  await page.goto(`${siteOrigin}/sign_in`);

  await page.type("input#user_email", user);
  await page.type("input#user_password", password);
  await page.click('input[type="submit"]');

  await page.waitForNavigation();
  await page.close();
};
```

As you can see, I just needed to use the provider `browser` instance, just as @patrickhulce suggested.

Thanks! 🎉

**Comment by citypaul** [comment]
Closing, as this is working now. Thank you!
