### ISSUE TITLE
CentOS7.4) Runtime error encountered: The environment variable CHROME_PATH must be set to executable of a build of Chromium version 54.0 or later.

### ISSUE THREAD

**Issue by student513** [GoogleChrome/lighthouse-ci#547]
Hi, I got an error and investigated it, but couldn't solve it.
I try to analyze lhci periodically using `agenda` scheduler and `child_process`.
The command executed is as follows.

```lhci collect --url=${url.url} --numberOfRuns=5 --settings.formFactor=${url.deviceType} ${screenEmulation} --settings.locale=ko-KR && lhci upload --target=temporary-public-storage && lhci upload --target=filesystem --reportFilenamePattern=%%DATETIME%%-${url._id}.%%EXTENSION%% --outputDir=./reports && rm -rf ./.lighthouseci/lhr-*```

However, when the command is executed, the following error is output.

```Runtime error encountered: The environment variable CHROME_PATH must be set to executable of a build of Chromium version 54.0 or later.```

I referred to the following link to solve this error.
https://github.com/GoogleChrome/lighthouse/issues/5424#issuecomment-394519301

Attempt to install chromium and set up 'CHROME_PATH=/usr/bin/chromium' but chromium does not exist in '/usr/bin' and command failed.
(also I excuted with `--settings.chromeFlags=--headless`)
I need `@lhci/cli` solution not `lighthouse`

thank u

## version
node: 12.16.1
OS: linux CentOS 7.4
lhci/cli: 7.0

**Comment by student513** [comment]
I solve this error installing chrome not chromium

**Comment by anandv06** [comment]
Can you provide the complete setup you used for the same ?

**Comment by student513** [comment]
> Can you provide the complete setup you used for the same ?


I solved my problem by installing `Chrome` instead of installing `Chromium`
Try these commands.

`wget https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm`
`yum -y install google-chrome*.rpm`
