### ISSUE TITLE
Is it possible to see only the errors in the console without add the rules in config file to off?

### ISSUE THREAD

**Issue by patriciamarchand** [GoogleChrome/lighthouse-ci#549]
I did not find in the documentation if it is possible to see only the errors in the console without add the rules in config file to off? I'm auditing my app by autodiscover le urls and it make le log in the console very difficut to read....

**Comment by patrickhulce** [comment]
Thanks for filing @patriciamarchand! I'm not sure I understand what you're looking for here.

You want to see errors in the console (which errors are you talking about? assertions with level "error" that aren't passing?), but you don't want to add rules to the config file?

The way I'm interpreting this right now sounds like you just shouldn't specify *any* assertions or presets in the config, but then I don't know what errors you'd be looking at.

**Comment by patriciamarchand** [comment]
This is my config file

```
assert: {
     preset: 'lighthouse:no-pwa',
      assertions: {
        'categories:accessibility': ['error', { aggregationMethod: 'optimistic', minScore: 0.99 }],
      },
},
```

And this is the result in the console.   
![image](https://user-images.githubusercontent.com/6225238/107669368-a91ee800-6c5f-11eb-9364-94fb896b5012.png)

I would like to hide the warning in the console whitout add specific assertions to off and see only the error.

**Comment by patrickhulce** [comment]
I see. No there is no shortcut for this. That's effectively a new preset that drops all of the warnings, which you're free to create if you'd like!

You can copy/paste the list from source here 
https://github.com/GoogleChrome/lighthouse-ci/blob/0f5c2ddbc7faedaaf32b5dc8c83678776636460e/packages/utils/src/presets/recommended.js#L14-L48
