### ISSUE TITLE
Browser Connect Options on Collect

### ISSUE THREAD

**Issue by metalix2** [GoogleChrome/lighthouse-ci#559]
Hey Chrome team,

Great work so far with well everything. 😅 

I have come across a scenario which is probably worth a discussion. My Team and I were looking to use LighthouseCI alongside the [Cypress testing framework](https://github.com/cypress-io/cypress). When using Cypress this allows us to mock requests fairly simply and manages all our visual, e2e and performance testing under one framework. We were originally using Lighthouse in Cypress until we wanted to start using LighthouseCI server and we felt it was best to try using the LighthouseCI client for a convenience. 

**Problem**
After playing around with the puppeteerLaunchOptions and debugging it became clear that LHCI will always create a browser when running tests. Since Cypress will create a browser we were wanting to point the lighthouseCI tests to this browser to benefit from the mocking etc. 

From what I can tell there are no puppeteer connect options or code throughout the LighthouseCI project and I was wondering whether this feature could be considered? I'm not 100% of the test impact of connecting to a 3rd party managing a chrome browser. I have managed to get it run on my mac and the performance results don't seem to change. Something worth thinking about though.

**Possible Solution**
An ideal solution would look something like this:
```
{
  ci: {
    collect: {
      url: 'http://localhost:5000',
      puppeteerConnectOptions: {      
        browserWSEndpoint: 'ws://127.0.0.1:39749/devtools/browser/09a33306-8c38-421a-9077-74864b845141'
      },
    },
}
```

If this is not possible would you happen to have and docs or guidance for uploading lighthouse reports generated outside of lighthouseCI to LighthouseCI server? I think this would be our only other alternative.

**Additional context**
Debugging Learnings:
When having `dumpio` set we can see that when setting the same debugging port as the one in use by cypress causes a bind issue but fails silently(?) on my host machine and lighthouseCI is then able to connect to the existing cypress browser. This doesn't happen in headless mode.. And isn't properly supported hence this feature request.
See the attached video for more info (The "Random" user list is mocked). You can see LHCI will open a browser after Cypress does but this closes shortly after once the bind fails.

https://user-images.githubusercontent.com/2506718/108979726-db2e4200-7682-11eb-836e-d68335e51708.mp4

**Comment by metalix2** [comment]
Thanks for the quick reply @patrickhulce 

The new tab is fine for our need at the moment. It still handles mocks the same way. But This is amazing news! Honestly made my week!

So simple yet I missed it 🤦  - Actually on having a look through the docs it doesn't actually mention the port option in settings. Perhaps a small update to the doc for manual connections might be in order for the next poor bastard trying to figure it out. 😄 

Just found in the code here - https://github.com/GoogleChrome/lighthouse/blob/575e29b8b6634bfb280bc820efea6795f3dd9017/types/externs.d.ts#L194

Any way feel free to mark this as closed! Your suggestion works perfectly 👍

**Comment by patrickhulce** [comment]
Glad you got it working @metalix2! We'd happily accept another entry added to the configuration examples if you wanted to jot down a sentence or two with it working with Cypress :)

**Comment by joshuawootonn** [comment]
Really glad I found this, running into the same issue!

Not sure what you mean by `<whatever the cypress-controlled browser port was>`?

Whenever I specify the port and run cypress (`cypress:open --port 9999`) I get 
![image](https://user-images.githubusercontent.com/20950876/115484530-994ff100-a218-11eb-985a-547785af7096.png)

@metalix2 could you give more context on what your setup looks like?

I have also tried 

```
browser.on('targetcreated', async (target) => {
    if (target.type() !== 'page') return;
    const page = await target.page();
    await page.setRequestInterception(true);
    page.on('request', async request => {
        // logic for mocking a request with request.respond
    }
})
```

but even if I just `request.continue()` it seems to loop infinitely on the same url.

@patrickhulce have you ever seen someone do something similar to this or is there a restriction I am just lacking context for?

**Comment by patrickhulce** [comment]
> @patrickhulce have you ever seen someone do something similar to this or is there a restriction I am just lacking context for?

I'm not sure what the "this" is in your sentence. Are you referring to request interception for mocking server responses during a Lighthouse run?

You're going to run into issues with that because Lighthouse uses request interception itself to handle a few of its checks. It might work after https://github.com/GoogleChrome/lighthouse/issues/11313 work is finished, and you might be able to get it to work for a specific request that you need, but it isn't officially supported yet so you're sort of on your own there.

**Comment by joshuawootonn** [comment]
Yup that is what the this was referring to. Makes sense that there are conflicts between the interceptors. Thanks for the update!
