### ISSUE TITLE
Ugrade migration-guide documentation

### ISSUE THREAD

**Issue by WillsB3** [GoogleChrome/lighthouse-ci#567]
Hi!

The [existing migration guide](https://github.com/GoogleChrome/lighthouse-ci/blob/main/docs/migration-guide.md) documentation only appears to cover migrating from `0.3.0` to `0.4.0`. I had a look through the [releases](https://github.com/GoogleChrome/lighthouse-ci/releases) to try and work out if (for example) upgrading directly from `0.4.1` to `0.7.0` would be safe but didn't find a definitive answer. 

I know the migration guide explains that the CLI of version `n` will always be compatible with the server of version `n - 1`, but it's not clear to me if the changes listed as breaking changes between `0.4.x` and `0.7.x` require an incremental upgrade approach. I also tried to see if I could find the code for any database migrations as the migration docs say "If any SQL migrations are needed for new features, the server will automatically execute them on startup." but I couldn't see any 👀 .

Perhaps we could update the migration documentation to give a bit more detail?

**Comment by patrickhulce** [comment]
Thanks for filing @WillsB3! Yes good catch. We'll try to backfill some of those.
