### ISSUE TITLE
CLI upload  reports the /builds/ URL

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse-ci#57]
also I think the /build/ command is also posted by the github status

But we (thanks to me) changed the url to /compare/  and so it 404s and the router falls back to the homepage.

Handling the redirect would be cool, but mostly we should just fix the original links.

example: https://lhci-canary.herokuapp.com/app/projects/d1e4b15c-e644-4552-b136-e975f486a2ce/builds/0a732a7a-1702-4aec-afff-8a4b7a735876

**Comment by patrickhulce** [comment]
thanks paul! fixed 6f1d63d8ff8f295469aa3ec3d28ccfb76ed73ef7
