### ISSUE TITLE
Add support for `fail fast` option

### ISSUE THREAD

**Issue by xavierfoucrier** [GoogleChrome/lighthouse-ci#578]
Hi GoogleChrome team!

I was wondering if a **fail fast** option, same as we see in testing library like `jest` , could be implemented on Lighthouse CI?

My use case is pretty simple: I want to run lighthouse twice on all my HTML pages, but when the same assertion fail on each pages, the CI result is quite overloaded... making it difficult to read and fix with ease.

Having such an option could prevent lighthouse from running further on pages that will encounter similar assertion issue.

Thanks a lot for your feedback :wink:

**Comment by xavierfoucrier** [comment]
@patrickhulce any update on this? Big thanks :sunglasses:

**Comment by patrickhulce** [comment]
You can accomplish this yourself today by running `lhci collect --numberOfRuns=1`, running your assertions with `lhci assert`, and then running `lhci collect --numberOfRuns=N-1 --additive` before uploading. 

It's potentially feasible to introduce such a mode via a flag to `autorun` but we're currently focused on features for LHCI that enable solutions to *unsolved* problems.

**Comment by xavierfoucrier** [comment]
Hi @patrickhulce!

Thanks for the fast reply :sunglasses: 
I will have a look at the `--additive` flag and see if it's compliant with my needs.

> We can keep this issue opened as soon as it is implemented with a dedicated flag.

**Comment by xavierfoucrier** [comment]
Hi @patrickhulce,

Finally got time to check.
Unfortunately, the `--additive` flag doesn't help a lot in my situation.

I am running **lighthouse-ci** with this `collect` configuration:

```json
"collect": {
  "staticDistDir": "dist",
  "numberOfRuns": 1,
  "maxAutodiscoverUrls": 2
}
```

This will run lighthouse once on first discovered URL, then it will run once again on the second discovered URL, meaning that in the console output it will display all errors, for each pages.

What would be cool, is to be able to tell lighthouse to "fail fast" in order to only display errors for the first URL. This could be really helpful when running `lighthouse-ci` inside a **development workflow**, like on **Github Actions**, where the log could be drastically long when running against a bunch of ~10/20 pages.

Let me know. :wink: 

> Note that I am not uploading lighthouse results on a dedicated server as of today.

**Comment by patrickhulce** [comment]
For multiple URLs you're right you'd need to run collect and assert in a loop for each of them instead. It's definitely annoying to do yourself, but it's still possible.

Processing every run as it happens would require an overhaul or completely new mode of operation (as well as invalidate quite a few of the assertion concepts relying on aggregation). To be honest, I think it's unlikely we implement something like this in the near future given the level of effort and the fact that its only feature is reducing the level of effort to receive results sooner.

**Comment by xavierfoucrier** [comment]
Hi @patrickhulce,

Thanks again for your answer.
Sounds like a great argument and I completely understand your position.

I am closing the issue, feel free to reopen if more people ask for this feature to be implemented.

Have a nice day! :sunglasses: :robot:
