### ISSUE TITLE
Ability to set cookies

### ISSUE THREAD

**Issue by Friss** [GoogleChrome/lighthouse-ci#58]
Having the ability to specify / pass cookies would be really helpful for testing pages that are behind auth or interact with authed endpoints.

**Comment by patrickhulce** [comment]
Thanks for filing @Friss! This is awaiting work on Lighthouse core (https://github.com/GoogleChrome/lighthouse/pull/9170), once it's available it will be available here too :)

**Comment by patrickhulce** [comment]
Also FWIW, if you don't need any cookie merging or other functionality available in #9170, you can get this working today with a `lighthouserc.json` like...


```json
{
  "ci": {
    "collect": {
      "settings": {
        "extraHeaders": {"Cookie": "session_id=whatever-session-id"}
      }
    }
  }
}
```

**Comment by patrickhulce** [comment]
Also https://github.com/GoogleChrome/lighthouse/blob/master/docs/authenticated-pages.md is a great resource for running Lighthouse on authenticated pages :)

**Comment by Friss** [comment]
Thanks for the recommendations @patrickhulce. I was unable to make the `extraHeaders` way work. I couldn't really debug why since the page would be redirected and the browser would close before I had a chance to look any further. So the upstream PR may help.  

I was able to create a puppeteer script that worked for our auth flow (via `page.setCookie`'s). And then I passed a `port` option and the underlying lighthouse cli was able to connect to it. 

Here's a gist of what I got to work for me. (I dynamically create the config file from my testing with extraHeader so that part isn't exactly necessary anymore) 
https://gist.github.com/Friss/6c20241725e36f2abc8d8c6d7cb5ad16

Couple things of note:

1) I had to pass the config as `--rcFile` instead of `--config` that the docs mention.
2) `extraHeaders` needs to be a JSON string or a file path. [extraHeaders code](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-cli/bin.js#L110-L123)

**Comment by patrickhulce** [comment]
> I had to pass the config as --rcFile instead of --config that the docs mention.

This was a late breaking change in the API, 0.3.0-alpha.0 was `rcFile` but 0.3.0 (published late today) and newer follow the docs, sorry about that! :)

> extraHeaders needs to be a JSON string or a file path. extraHeaders code

Ah, drat this is indeed a bug with the CLI form of Lighthouse. Will file an issue upstream 👍

**Comment by Draichi** [comment]
Not working for me

I've tried both ways:

```
"settings": {
        "extraHeaders": "{\"Cookie\": \"PHPSESSID=1234\"}"
      }
```

```
"settings": {
        "extraHeaders": {"Cookie": "session_id=whatever-session-id"}
      }
```

Not working

**Comment by patrickhulce** [comment]
> Not working

Can you provide more detail on what you mean by "Not working"? Do you get an error message? Only the first version of what you posted should have an effect (assuming you're nesting this under `ci.collect`) and that latter should throw a fatal error until the PR adding support to Lighthouse is fixed.

**Comment by patrickhulce** [comment]
Also worth noting for this thread that [puppeteer scripts](https://github.com/GoogleChrome/lighthouse-ci/blob/dfd879195e665c30ca508d553885741ddee9d79a/docs/cli.md#using-puppeteer-scripts) came out after this issue was filed and are a far superior and flexible method of handling auth at this point.

**Comment by patrickhulce** [comment]
We're considering this solved by the `puppeteerScript` option https://github.com/GoogleChrome/lighthouse-ci/blob/03eb7aa06ba6373bb6c6cd9804d3fa0154f40938/docs/configuration.md#puppeteerscript
