### ISSUE TITLE
Lighthouse v7.3.0

### ISSUE THREAD

**Issue by pyymenta** [GoogleChrome/lighthouse-ci#580]
Hello guys,

Lighthouse [v7.3.0](https://github.com/GoogleChrome/lighthouse/releases/tag/v7.3.0) was released a 12 days ago.

The release notes includes the `jsonld` update to [its latest version](https://github.com/GoogleChrome/lighthouse/pull/12257)

It fixes this vulnerability described below:

https://npmjs.com/advisories/1650 

![image](https://user-images.githubusercontent.com/13206817/113053732-007d0700-917f-11eb-866e-afa85189820d.png)

**Comment by mattdell** [comment]
+1 to this

Have been through the dependency tree and everything has been fixed. `@lhci/cli` needs to use `"lighthouse": "7.3.0"` to close this vulnerability.
