### ISSUE TITLE
Feature to set a label in reports and assertion-results.json for identifying results.

### ISSUE THREAD

**Issue by metalix2** [GoogleChrome/lighthouse-ci#586]
**Is your feature request related to a problem? Please describe.**
When running multiple collects the only way to uniquely identify a run in the assertion-results.json is using the url.
But what If we had the same url rendering a slightly different page based on a configuration header for example. We wouldn't be able to distinguish these two different test reports in the assertion-results.json. 

**Describe the solution you'd like**
I'd like to propose the option to label a collect/assert run where the label would be set inside the report and assertion-results.json for each of the asserted fields. This way we could look-up/organise runs to manage data for further processing. 

**Describe alternatives you've considered**
I've tried setting up a post run directory organisation. Which would move tests out of the base .lighthouseci directory to a labelled directory .e.g. /lighthouse-reports/homepage and then moving the tests back to the .lighthouseci folder for the upload stage. This just feels a bit messy we'd like our scripts to just process the single file to get all the information we need.

**Additional context**
I'd be more than happy to raise a PR to handle this kind of mechanism. 👍

**Comment by patrickhulce** [comment]
Thanks for filing @metalix2!

> But what If we had the same url rendering a slightly different page based on a configuration header for example. We wouldn't be able to distinguish these two different test reports in the assertion-results.json.

Our guidance here has been to append a meaningless query param to the URL, i.e. `/?configuration1`.

The rest of your suggestion sounds like it might have significant overlap with https://github.com/GoogleChrome/lighthouse-ci/issues/343 and #349? I think we just need to iron out what use cases you're trying to solve by have it apply at the assertion level and not just the server level.

**Comment by metalix2** [comment]
Hey @patrickhulce,

Welcome back from your time off.

Ahh I totally missed this previous issue. 🤦  
#343 is pretty much what I had in mind. I tried to simplify my problem statement. But it is the assertion layer we do want the labels.

Our current scenario is I've got some test suites running in Cypress which will collect and assert per suite. The Only thing is that these test suites all read from the same folder and I'd like to persist the reports for a final upload later on.

The last suite will assert and the assertion_results.json will contain results for all the reports generated from all the tests.
We currently have a separate task where we read the assertion_results.json and pull out the performance scores. But we can't match a url to a suite. We were trying to find a clean way to mark a run to a given suite.

I think your query param solution may help us in the mean time though.

Happy to close this in the mean time.

**Comment by patrickhulce** [comment]
Thanks @metalix2! :)

I'll go ahead and merge this into #343 with some of the notes here. I had been thinking applying at the server layer would already have it's limitations so I'm happy to expand the scope of that issue to encompass some sort of labeling that would help with assertion/collection as well.
