### ISSUE TITLE
Unable to use patrickhulce/lhci-client in tekton pipelines

### ISSUE THREAD

**Issue by cameronbraid** [GoogleChrome/lighthouse-ci#590]
Not sure if this is a bug report, feature request, or configuration error, or even if this is the right place to post this

I'm trying to use the `patrickhulce/lhci-client` image in tekton pipelines (as part of a jenkins x 3 build), and it fails with permission denied :

```
2021/04/26 03:35:18 warning: unsuccessful cred copy: ".docker" from "/tekton/creds" to "/tekton/home": unable to open destination: open /tekton/home/.docker/config.json: permission denied
2021/04/26 03:35:18 warning: unsuccessful cred copy: ".gitconfig" from "/tekton/creds" to "/tekton/home": unable to open destination: open /tekton/home/.gitconfig: permission denied
2021/04/26 03:35:18 warning: unsuccessful cred copy: ".git-credentials" from "/tekton/creds" to "/tekton/home": unable to open destination: open /tekton/home/.git-credentials: permission denied
/tekton/scripts/script-12-qs2cv: line 2: .jx/variables.sh: Permission denied
+ lhci autorun
❌  .lighthouseci/ directory not writable
    ERROR: EACCES: permission denied, mkdir '/workspace/source/.lighthouseci'
⚠️   Configuration file not found
✅  Chrome installation found
Healthcheck failed!
```
As a workaround I got it working with 

```
securityContext:
  runAsUser: 0
```

However I would like to run it as non root.

Any pointers on how to make this work ?

**Comment by patrickhulce** [comment]
Thanks for filing @cameronbraid! This sounds like a tekton configuration issue (possibly related https://github.com/tektoncd/pipeline/issues/1872?) `/workspace/source/` is definitely not a Lighthouse CI thing. Our dockerfile is [supposed to use `/home/lhci/reports`](https://github.com/GoogleChrome/lighthouse-ci/blob/c31cea34e1fd883879b545458c6a9fff27d2af48/docs/recipes/docker-client/Dockerfile#L24) which the non-root user definitely owns.

We're not familiar enough with tekton to be able to help out here, but please do let us know here if you figure out the issue though to help future tekton users (and in case there's anything LHCI can do to make it a little more seamless).
