### ISSUE TITLE
Puppeteer?

### ISSUE THREAD

**Issue by elsassph** [GoogleChrome/lighthouse-ci#60]
The CLI apparently runs Chrome headless (and headfull optionally), but could it run with Puppeteer?

**Comment by patrickhulce** [comment]
Thanks for filing @elsassph! 

Mind explaining your use case a bit? :) The `collect` command of Lighthouse CI supports the same launch methods that the standard Lighthouse CLI supports, and I'm not sure what additional value using the puppeteer launcher instead would offer.

Is the goal to run a puppeteer script on the Chrome profile before running Lighthouse?

**Comment by elsassph** [comment]
The goal is to run CI without pre-installing Chrome on the agent, as with https://github.com/femtopixel/google-lighthouse-puppeteer

**Comment by patrickhulce** [comment]
Oh gotcha! Yes, is the `CHROME_PATH` variable not being respected? If you set `CHROME_PATH=/path/to/your/chromium` it should use your puppeteer chromium without the need to install it in the environment.

**Comment by thasmo** [comment]
@patrickhulce I'm not too much into headless/puppeteer etc. but when running `lhci` in a docker container, would it be possible for `lhci` to use a **remote** headless chrome (maybe via puppeteer)?

**Comment by patrickhulce** [comment]
> would it be possible for lhci to use a remote headless chrome (maybe via puppeteer)

Yes, it *should* be but fairly untested. Have you tried something like the below?

```json
{
  "ci": {
    "collect": {"settings": {"hostname": "my-remote-hostname.com", "port": 3009}}
  }
}

**Comment by patrickhulce** [comment]
@elsassph going to mark this as closed, but if you run into a concrete, reproducable issue feel free to chime back in :)
