### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by LiangChen0323** [GoogleChrome/lighthouse-ci#604]
Hi

The CI server(TeamCity) that I am using is behind a proxy. When I run `%lhci% collect --url="https://xxx/" `  
I got the below error message:
```
Running Lighthouse 3 time(s) on https://xxx/
  events.js:292
        throw er; // Unhandled 'error' event
        ^
  Error: spawn node ENOENT
      at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
      at onErrorNT (internal/child_process.js:469:16)
      at processTicksAndRejections (internal/process/task_queues.js:84:21)
  Emitted 'error' event on ChildProcess instance at:
      at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
      at onErrorNT (internal/child_process.js:469:16)
      at processTicksAndRejections (internal/process/task_queues.js:84:21) {
    errno: 'ENOENT',
    code: 'ENOENT',
    syscall: 'spawn node',
    path: 'node',
    spawnargs: [
      'D:\\storage\\TOOLs\\Node\\12.18.2\\node_modules\\@lhci\\cli\\node_modules\\lighthouse\\lighthouse-cli\\index.js',
      'https://staging-web.ccleaner.com/',
      '--output',
      'json',
      '--output-path',
      'stdout',
      '--cli-flags-path',
      'D:\\work\\d861189cd355c9e2\\.lighthouseci\\flags-33da5e9f-3beb-41da-86c0-a859580f8d85.json'
    ]
  }
```
I also have environment variables for proxy: `HTTP_PROXY, HTTP_PROXY_HOST and HTTP_PROXY_PORT`
Any idea what the error really is about?

**Comment by LiangChen0323** [comment]
> Have the node_modules folders become corrupted @LiangChen0323? That error means that the file LHCI is trying to run is missing. As a first step, I'd try to reinstall LHCI after clearing away `node_modules`.

Hi @patrickhulce, 

The build agent starts clean every time. 
So I have to install the node package every time: 
`npm install -g @lhci/cli@0.7.2 --registry=xxx`

**Comment by LiangChen0323** [comment]
@patrickhulce 

`lhci healthcheck ` command worked:
```
  .lighthouseci/ directory writable
  Configuration file not found
  Chrome installation found
  Healthcheck passed!
```

**Comment by patrickhulce** [comment]
@LiangChen0323 healthcheck does not attempt to run Lighthouse itself (though after this, we'll probably add it to the list)

> D:\\storage\\TOOLs\\Node\\12.18.2\\node_modules\\@lhci\\cli\\node_modules\\lighthouse\\lighthouse-cli\\index.js is definitely a file that exists after you've finished installation?

Can you confirm this?

**Comment by LiangChen0323** [comment]
@patrickhulce 
yes, I can confirm that the file is exist:
```
  Directory of D:\storage\TOOLs\Node\12.18.2\node_modules\@lhci\cli\node_modules\lighthouse\lighthouse-cli
  05/10/2021  06:54 PM    <DIR>          .
  05/10/2021  06:54 PM    <DIR>          ..
  10/26/1985  10:15 AM             4,635 bin.js
  10/26/1985  10:15 AM            20,017 cli-flags.js
  05/10/2021  06:54 PM    <DIR>          commands
  10/26/1985  10:15 AM               740 index.js
  10/26/1985  10:15 AM             2,611 printer.js
  10/26/1985  10:15 AM             9,473 run.js
  10/26/1985  10:15 AM             2,789 sentry-prompt.js
  05/10/2021  06:54 PM    <DIR>          test
```

**Comment by patrickhulce** [comment]
oh! It's `node` that does not exist! Is node not in the PATH of this build?
