### ISSUE TITLE
Passes Support - for collecting Traces

### ISSUE THREAD

**Issue by metalix2** [GoogleChrome/lighthouse-ci#605]
**Is your feature request related to a problem? Please describe.**
It would be helpful if we collect traces along with the reports. I've not quite thought ahead on storing these but it would be pretty handy. We tend to use these already and would be good to keep the same functionality. 

**Describe the solution you'd like**
Pass the [Passes](https://github.com/GoogleChrome/lighthouse/blob/master/docs/configuration.md#passes-object ) object to the lighthouse runner - https://github.com/GoogleChrome/lighthouse-ci/blob/main/packages/cli/src/collect/collect.js#L80.

**Describe alternatives you've considered**
I don't think there are any alternatives.

**Comment by patrickhulce** [comment]
Thanks for filing @metalix2! Agreed trace collection would be awesome :) (see https://github.com/GoogleChrome/lighthouse-ci/issues/112), but I'm a little unclear how the passes object would help with this?

We can already collect the trace of page load without modifying passes, just by passing the `--save-assets` flag to Lighthouse. The challenge is storage.

**Comment by metalix2** [comment]
Thanks for the quick reply @patrickhulce,
My understanding of lighthouse and traces was that you would set up a `passes` config to record the trace. This would then be available in the output under the `artifacts` index.
```
{
    "lhr": {},
    "artifacts": {},
    "report": "{}"
  },
```

I wasn't aware of the --save-assets flag 😮  does this get passed into `settings` ?

**Comment by patrickhulce** [comment]
> I wasn't aware of the --save-assets flag 😮 does this get passed into settings ?

Yes you can. `lhci collect -n=1 --settings.saveAssets --url=https://example.com` will dump the trace and devtools log in the current working directory. If you just want to process them yourself, you're done :)

The challenge with LHCI is organizing these traces and storing them with `upload` (tracked by #112)

**Comment by metalix2** [comment]
Ohh I see.. that is pretty handy. 👌 

Couldn't the naming of the trace file be the same as the report but instead of `lhr-timestamp.json` be `trace-timestamp.json` 

Happy to continue the conversation in that issue it doesn't seem to be much activity there 😅

I suppose my original question has been answered 🎉

**Comment by patrickhulce** [comment]
> Couldn't the naming of the trace file be the same as the report but instead of lhr-timestamp.json be trace-timestamp.json

For sure, but organization in the `.lighthouseci` folder isn't the concern ;) Can pickup discussion in #112, but the short story is "there's complexity here and no one is planning on working on it soon, but we'd like to if we had more time"
