### ISSUE TITLE
UI crashes and hangs when comparing runs with less LH audits

### ISSUE THREAD

**Issue by GabDug** [GoogleChrome/lighthouse-ci#607]
**Describe the bug**
When using the LHCI server:
When comparing two runs, with different audit settings, the UI may break and load indefinitely, and the page never loads.

This happens when the base run has fewer categories than the compared run, and seems related to the PWA audits.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a run with only the performance audit category.
2. Create a run with all audit categories (performance, PWA, SEO, accessibility...)
3. Go to one of these pages:
    A. Go to the latest run (with all audits), eg from the link given in the `lhci autorun` command (`http://lhci-server:9001/app/projects/perf-beacon-dev/compare/89d4cded-0829-4f1d-9a45-bacc672a2e65`).
    B. Compare runs, with a base run with performance audit only and a compared run with all audits, it crashes the webpage. (`http://lhci-server:9001/app/projects/perf-beacon-dev/compare/89d4cded0829?baseBuild=1c2a5813-b31f-4c17-9d7e-e1231ce291f2)`

**Expected behavior**
The page should load normally. 

It works fine when comparing a base run with complete audit, compared to a run with performance audit only.

Testing on `http://lhci-server:9001/app/projects/perf-beacon-dev/compare/1c2a5813b31f?baseBuild=89d4cded-0829-4f1d-9a45-bacc672a2e65`
![image](https://user-images.githubusercontent.com/1116720/118259956-0ff7ab80-b4b2-11eb-8c8c-c63f3258dd70.png)

**Logs/Screenshots**

Testing on:
- The URL given by LHCI upload: http://lhci-server:9001/app/projects/perf-beacon-dev/compare/89d4cded-0829-4f1d-9a45-bacc672a2e65
- Comparison page: http://lhci-server:9001/app/projects/perf-beacon-dev/compare/89d4cded0829?baseBuild=1c2a5813-b31f-4c17-9d7e-e1231ce291f2

Browser console error
```
pwa-gauge.jsx:92 Uncaught (in promise) TypeError: Cannot read property 'auditRefs' of undefined
    at g (pwa-gauge.jsx:92)
    at y.i [as constructor] (lhr-comparison-scores.jsx:52)
    at y.L [as render] (index.js:337)
    at U (index.js:119)
    at children.js:85
    at C (children.js:194)
    at C (children.js:190)
    at b (children.js:52)
    at D (index.js:261)
    at U (index.js:152)
```

Screenshot
![image](https://user-images.githubusercontent.com/1116720/118259223-310bcc80-b4b1-11eb-936b-c2dfbb9c2594.png)

**Environment:**
 - LHCI (runner and server): 0.7.2
 - OS: Mac OS Big Sur
 - Browser: Edge 90, Chrome 90, Safari

**Additional context**

If you want more context, or if my issue was unclear, I'll be happy to help!

**Comment by patrickhulce** [comment]
Thanks for filing @GabDug! LHCI doesn't officially support comparisons of significantly altered configurations, but this is an egregious issue we can definitely fix 👍

**Comment by GabDug** [comment]
Thanks for your quick response!
