### ISSUE TITLE
Generate multiple urls

### ISSUE THREAD

**Issue by boxadesign** [GoogleChrome/lighthouse-ci#610]
Hi I want to run lighthouse ci on all pages in a static site generator. The below doesn't work. I need to wait for all of the page paths to be returned as an array (`urls`) and then passed in as the value to `url` in the lighthouserc config. When I run `lhci autorun` from the command line it's not picking up the `ci: {}` config.

```
const getPages = require('./lighthouse');

module.exports = (async () => {
  const urls = await getPages();
  const obj = {
    ci: {
      collect: {
        url: urls,
        numberOfRuns: 1,
      },
      preset: 'lighthouse:no-pwa',
      assertions: {
        'categories:accessibility': ['warn', { minScore: 0.9 }],
      },
      upload: {
        target: 'temporary-public-storage',
      },
    },
  };
  return obj;
})().catch(err => {
  console.error(err);
});
```

**Comment by patrickhulce** [comment]
Thanks for filing @boxadesign!

The `.lighthouserc.js` config file cannot return a promise; it *must* return the configuration object. I'd suggest doing whatever async work you'd like *before* you run `lhci autorun` and store the results in a file or script of some sort. This is actually what LHCI does to run on itself.

https://github.com/GoogleChrome/lighthouse-ci/blob/ab9f5c3f6c3704f67cf94ef749d9c28f1652f9a0/scripts/ci-dogfood.sh#L16-L18
