### ISSUE TITLE
Unclear debug message for building new vs old hashes

### ISSUE THREAD

**Issue by ianjmacintosh** [GoogleChrome/lighthouse-ci#612]
This is just a tiny copy tweak. I'm not sure how small is too small to be genuinely helpful, but I was a little confused at this message while getting started with my first Lighthouse CI server:

```
⚠️   LHCI server non-unique build for this hash
```

The other messages follow a nice terse `<noun> <adjective>` format (`✅  LHCI server API-compatible` or `✅  LHCI server token valid`), but my best suggestion is:
```
LHCI server already has a build for this commit hash
```

And for success:
```
LHCI server can make the first build for this commit hash
```

Thoughts?

**Comment by patrickhulce** [comment]
Thanks for filing @ianjmacintosh!

> LHCI server already has a build for this commit hash

SGTM 👍  

> LHCI server can make the first build for this commit hash

How about `LHCI server can accept a build for this commit hash`? "the first" feels rather specific to the conditions the user doesn't really care about which was what was wrong with the `unique` focus of the message you brought up in the first place :)
