### ISSUE TITLE
Node.js 16 support - upgrade lighthouse to v7.5.0

### ISSUE THREAD

**Issue by Hongbo-Miao** [GoogleChrome/lighthouse-ci#616]
It would be great to upgrade lighthouse to v7.5.0.
Because recent lighthouse 7.5.0 has this https://github.com/GoogleChrome/lighthouse-ci/issues/596 fixed to allow to using Node.js 16
Thanks!

**Comment by patrickhulce** [comment]
Thanks for filing!

As mentioned in https://github.com/GoogleChrome/lighthouse-ci/issues/596#issuecomment-832006808 there is nothing stopping node 16 support aside from just reinstalling/updating package lock deps. Given that Lighthouse version 8 is being released in 2 weeks we'll likely skip 7.5.0.

**Comment by Hongbo-Miao** [comment]
Thanks @patrickhulce ! You are right, reinstalling package-lock.json helps.
