### ISSUE TITLE
Javascript error on LHCI Server when selecting an audit node to compare

### ISSUE THREAD

**Issue by dkarzon** [GoogleChrome/lighthouse-ci#618]
**Describe the bug**
When comparing 2 runs clicking on an audit node throws a javascript error: `TypeError: Cannot read property 'snippet' of undefined` and does not open the sidebar for detailed comparison.

**To Reproduce**
1. Open a project and click on the latest build from the builds list to compare it to the previous.
2. Scroll down and click on 1 of the audit nodes (ie. "Total Blocking Time" under the Metrics header. Though the error happens when clicking on any)
3. See error in console

**Expected behavior**
The detailed view sidebar pops out to show more info on the selected item.

**Logs/Screenshots**
![image](https://user-images.githubusercontent.com/214449/120413703-25b70d00-c39c-11eb-8d28-af38d95a095e.png)

**Environment (Server):**
 - OS: AWS Fargate (docker)
 - LHCI Server Version: 0.7.2
 - Data storage: PostgreSQL (AWS RDS)

**Environment (Runner):**
 - OS: Bitbucket Pipelines (Image: node:12.17-alpine3.11)
 - LHCI CLI Version: 0.7.2

**Environment (Client):**
 - OS: Windows 10
 - Browser1: Chrome v90.0.4430.212
 - Browser2: Edge v91.0.864.3

**Additional context**
This error only happens for 1 of the projects I have setup on this server (all are run from the same bitbucket pipeline instead all with the same versions). Attaching Lighthouse report JSON to recreate the issue.

Link to lhr json (2021-06-01): https://drive.google.com/file/d/1deL6yTsaQvgxtFLQpLbIXlAEUemvydxe/view?usp=sharing
Link to lhr json (2021-05-31): https://drive.google.com/file/d/1m28T_qLrvucocqTdW-zNSrHqcSIVS15D/view?usp=sharing

**Comment by patrickhulce** [comment]
Thanks for filing and providing LHRs @dkarzon! I can reproduce and know what the problem is, we'll try to get the fix out in the 0.8.0 release this week 👍

**Comment by dkarzon** [comment]
@patrickhulce Awesome thanks!

**Comment by dkarzon** [comment]
@patrickhulce I have deployed v0.8.0 and can confirm this is now fixed, thanks 👍
