### ISSUE TITLE
`npm install -g @lhci/cli@0.3.x` fails (please publish a non-preview 0.3.x release)

### ISSUE THREAD

**Issue by mathiasbynens** [GoogleChrome/lighthouse-ci#62]
`npm install -g @lhci/cli@0.3.x` currently fails, because no non-preview 0.3.x release has been `npm publish`ed yet:

```
$ npm install -g @lhci/cli@0.3.x
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @lhci/cli@0.3.x
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
```

Note that this exact command occurs in the README and in the docs. Let’s release v0.3.0!

**Comment by mathiasbynens** [comment]
To anyone else hitting this, here’s the workaround:

```
npm install -g @lhci/cli@0.3.0-alpha.0
```

**Comment by patrickhulce** [comment]
Thanks @mathiasbynens I was interrupted in the middle of publishing 0.3.0 earlier today so the docs change leaked out early 😬 , sorry for the inconvenience it should be live now! :)
