### ISSUE TITLE
Latest `@lhci/cli@0.8.0` throw a CSP-XSS failure

### ISSUE THREAD

**Issue by xavierfoucrier** [GoogleChrome/lighthouse-ci#622]
Hi GoogleChrome team!

Since I updated to `@lhci/cli@0.8.0` I got **an error in the terminal about `csp-xss` failure**:

![Capture](https://user-images.githubusercontent.com/2471223/120798339-80d43580-c53d-11eb-8516-cb075ed465e8.JPG)

The fact is that I got nothing about CSP-XSS in my document, so I don't understand the point.

I saw that you recently upgrade to `lightouse@8` and set this assert to `off` by default here: https://github.com/GoogleChrome/lighthouse-ci/commit/72107f3bf462ab60596f576967ff1a5e0aad622b#diff-6e9b5aaa264a9077559df91259f612a41c7cd6ad9f0da45408b236cf108e7dab.

> Note that it's working without issues when setting it to `off` explicitly in my assert configuration.

**Comment by patrickhulce** [comment]
Thanks for filing!

> The fact is that I got nothing about CSP-XSS in my document, so I don't understand the point.

The point of the audit is recommending you add one :)

> Note that it's working without issues when setting it to off explicitly in my assert configuration.

That's fine and working expected, if you don't care about passing the audit, continue to do so.

> I saw that you recently upgrade to lightouse@8 and set this assert to off by default here

It's not off by default, we turned the assertion off on our own usage of LHCI, just like you did.

**Comment by xavierfoucrier** [comment]
Hoooooo, ok so I just read `'csp-xss': 'off'` and though that it was set off by default and just don't understand why it wasn't off! Fine, well I will implement in order to pass the audit. Thanks for the fast answer as usual @patrickhulce! Have a nice day and weekend :rocket:
