### ISSUE TITLE
@lhci/cli@0.8.x setting locale doesn't work

### ISSUE THREAD

**Issue by 7inspire** [GoogleChrome/lighthouse-ci#639]
**Describe the bug**
@lhci/cli@0.8.x setting locale doesn't work, but @lhci/cli@0.7.x work

**To Reproduce**
module.exports = {
  ci: {
    collect: {
      numberOfRuns: 1,
      staticDistDir: './dist',
      settings: {
        chromeFlags: "--disable-gpu --no-sandbox",
        onlyCategories: ['performance'],
        locale: 'zh',
     }
   }
  }
}

setting locale: 'zh', but it doesn't work.
after downgrade @lhci/cli to version 0.7, it works

**Expected behavior**
setting locale: 'zh', it works

**Logs/Screenshots**
If applicable, add LHCI logs or screenshots to help explain your problem.

**Environment (please complete the following information):**

**Additional context**

**Comment by patrickhulce** [comment]
Thanks for filing @7inspire! This is a known breaking change. Please see https://github.com/GoogleChrome/lighthouse#how-do-i-get-localized-lighthouse-results-via-the-cli
