### ISSUE TITLE
Invalid value: Argument 'screenEmulation' must be an object, specified per-property 

### ISSUE THREAD

**Issue by badsyntax** [GoogleChrome/lighthouse-ci#640]
**Describe the bug**

I'm following [the docs](https://github.com/GoogleChrome/lighthouse-ci/blob/main/docs/getting-started.md) to get started on a basic react-app but i'm presented with the following error:

```console
❯ $(npm bin)/lhci autorun
✅  .lighthouseci/ directory writable
✅  Configuration file found
✅  Chrome installation found
Healthcheck passed!

Started a web server on port 49533...
Running Lighthouse 3 time(s) on http://localhost:49533/index.html
Run #1...failed!
Error: Lighthouse failed with exit code 1
    at ChildProcess.<anonymous> (/Users/richardwillis/Projects/***/***/node_modules/@lhci/cli/src/collect/node-runner.js:120:21)
    at ChildProcess.emit (node:events:365:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
Invalid value: Argument 'screenEmulation' must be an object, specified per-property ('screenEmulation.width', 'screenEmulation.deviceScaleFactor', etc)

Specify --help for available options
```

**To Reproduce**

1. Generate a new react app using create-react-app

2. Save the following in `<projectRoot>/lighthouserc.json`

```json
{
  "ci": {
    "collect": {
      "staticDistDir": "./build"
    },
    "upload": {
      "target": "temporary-public-storage"
    }
  }
}

```

3. `npm i @lhci/cli --save-dev`

4. `npm run build`

5. `$(npm bin)/lhci autorun`

**Expected behavior**

I expect lighthouse to run and not error with the error above.

**Logs/Screenshots**

See above for error log.

**Environment (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: lhci/cli@0.8.0

**Additional context**

- I'm using an Apple M1
- I'm using Node 16.1.0

**Comment by badsyntax** [comment]
The bug is related to installing lhci locally. When I install it globally it works.

Why is there a reliance on installing the library globally? Seems silly. I'd like to pin the version in my project package.json so every other developer running lighthouse on this project will do so using the same version.

**Comment by patrickhulce** [comment]
Thanks for filing @badsyntax! I'm not able to reproduce this behavior in a fresh container with the following test script.

```bash
apt update
apt upgrade
apt install -y chromium
npx create-react-app foobar
cd foobar
cat >> lighthouserc.json <<EOF
{
  "ci": {
    "collect": {
      "staticDistDir": "./build"
    },
    "upload": {
      "target": "temporary-public-storage"
    }
  }
}
EOF
npm i @lhci/cli --save-dev
npm run build
./node_modules/.bin/lhci autorun --collect.settings.chromeFlags='--no-sandbox'
```

There shouldn't be any dependency on global installation. Your error sounds like there was another prior lighthouse version somehow installed locally that LHCI was accidentally using somehow?

**Comment by badsyntax** [comment]
@patrickhulce many thanks, yes i think that's it:

```console
❯ npm ls lighthouse
***@0.1.0 /Users/richardwillis/Projects/***/***
├─┬ @lhci/cli@0.8.0
│ ├─┬ @lhci/utils@0.8.0
│ │ └── lighthouse@8.0.0
│ └── lighthouse@8.0.0
└─┬ playwright-lighthouse@2.0.2
  └── lighthouse@7.5.0
```

Very sorry for the noise, I should have tested this on a clean react-project :( I'm sorry.  Will close...
