### ISSUE TITLE
Some if statements in Getting Started docs are a bit confusing

### ISSUE THREAD

**Issue by mflodin** [GoogleChrome/lighthouse-ci#65]
In a few places in the Getting Started docs, there are some checks for Travis Node version, but the text echoed doesn't make any sense. I guess it's a copy/paste error? 

Also ~~condititions~~ => conditions

```
# example if only running lighthouse on node 10
if [[ "$TRAVIS_NODE_VERSION" != "10" ]]; then
  echo "Only run Lighthouse CI once per build, condititions did not match.";
  exit 0;
fi
```
Found at https://github.com/GoogleChrome/lighthouse-ci/blob/master/docs/getting-started.md#complete-setup
and https://github.com/GoogleChrome/lighthouse-ci/blob/master/docs/getting-started.md#create-a-run-lhci-script

**Comment by patrickhulce** [comment]
Thanks very much for the feedback @mflodin! The text is correct (aside from the conditions typo 😉), but the docs were restructured to move the note on matrix builds (which this condition is meant for) farther down which indeed makes this very confusing. We'll fix :)
