### ISSUE TITLE
Add option to configure migrations table name

### ISSUE THREAD

**Issue by tim-yao** [GoogleChrome/lighthouse-ci#652]
Currently LHCI server will create a table named `SequelizeMeta` in the db. However, our server db only support lowercase table name. Which cause a problem to use it.

According to the docs from `sequelize` https://sequelize.org/v4/manual/tutorial/migrations.html#migration-storage, I should able to use a different table name by below config:
```
    // Use a different table name. Default: SequelizeMeta
    "migrationStorageTableName": "sequelize_meta"
```
See another suggestion from https://stackoverflow.com/a/56692455/1212791

I see LHCI support passing options to `sequelize` in docs configuration:
https://github.com/GoogleChrome/lighthouse-ci/blob/main/docs/configuration.md#storagesequelizeoptions

I tried below in my server, but it doesn't change anything, the db table created is still `SequelizeMeta`. If anyone can tell what I suppose to do, that will be great! Thanks!
```
createServer({
  port: 3000,
  storage: {
    storageMethod: 'sql',
    sqlDialect: 'mysql',
    sqlConnectionUrl: dbUrl,
    sequelizeOptions: {
      migrationStorage: 'sequelize',
      migrationStorageTableName: 'sequelize_meta'
    }
  },
 ...
```

**Comment by patrickhulce** [comment]
Thanks for filing @tim-yao! LHCI initializes the migration runner separately so sequelizeOptions for migrations won't take effect.

https://github.com/GoogleChrome/lighthouse-ci/blob/31e731a338ee50d241ea9ae40400748bd3901c4b/packages/server/src/api/storage/sql/sql.js#L136-L144

`storageOptions: {tableName: 'sequelize_meta'}` is what you'd need here. PR welcome for a `sqlMigrationOptions: {tableName?: string}` option to be passed through :)

**Comment by tim-yao** [comment]
Thanks @patrickhulce! I patched the `sql.js` to add `storageOptions: {tableName: 'sequelize_meta'}` and it works. I will have a look at how to add the option in server and submit a PR if I can make it.
