### ISSUE TITLE
helthCheck of LHCI server reachable might be incorrect

### ISSUE THREAD

**Issue by Limsanity** [GoogleChrome/lighthouse-ci#676]
**Describe the bug**

This bug exist in `@lhci/cli`.

helthCheck of `LHCI server reachable` might be incorrect.

[the code](https://github.com/GoogleChrome/lighthouse-ci/blob/72107f3bf4/packages/cli/src/healthcheck/healthcheck.js#L101) only check the the lenth of response, [getVersion](https://github.com/GoogleChrome/lighthouse-ci/blob/72107f3bf462ab60596f576967ff1a5e0aad622b/packages/utils/src/api-client.js#L165)  didn't not check the response status. If the lighthouse server is protected by firewall, response status may be 403 so it is unreachable actually. 

**To Reproduce**

1. try to response 403 status in `/version` path
2. helthCheck of `LHCI server reachable` still pass

**Expected behavior**

`LHCI server reachable` only pass when the `/version` response status is 200.

**Logs/Screenshots**

**Environment (please complete the following information):**

**Additional context**

**Comment by patrickhulce** [comment]
Thanks for filing @Limsanity!
