### ISSUE TITLE
Github action?

### ISSUE THREAD

**Issue by carlesnunez** [GoogleChrome/lighthouse-ci#68]
Hello, first of all congratulations for the amazing work, this looks promising.

I would like to know the next if you considering the possibility of create a github action for this?

Does it make sense?

Thank you

**Comment by alekseykulikov** [comment]
Hey @carlesnunez 
It does make great sense, and the Github Action is already implemented: https://github.com/treosh/lighthouse-ci-action

**Comment by denar90** [comment]
@patrickhulce is it an option to mention Github Action in docs?

**Comment by patrickhulce** [comment]
Yeah this makes sense to live in the docs! Maybe a good time to start the related projects section lighthouse ci edition :)
