### ISSUE TITLE
Missing documentation on running detailed assertions via the CLI

### ISSUE THREAD

**Issue by abiodunt** [GoogleChrome/lighthouse-ci#683]
I wasn't able to find any documentation on how to run detailed assertions via the CLI. For example, I want to run the below assertion via the CLI.

```
...
      assert: {
        assertions: {
           'speed-index': ['warn', { minScore: 0.5 }]
        },
...
```

`lhci autorun --assert.assertions.speed-index=warn` will return an assertion for the speed index audit and correctly `warn`, however, the `minScore` defaults to 0.9. How would you specify a `minScore` or `maxNumericValue` via the CLI along with `warn` or `error`?

I think the documentation could really benefit from this.

**Comment by patrickhulce** [comment]
Thanks for filing @abiodunt! 

> How would you specify a minScore or maxNumericValue via the CLI along with warn or error?

If the assertion is already defined, you might be able override it with `assert.assertions.speed-index.1.minScore=0.7` but this would be strongly discouraged. In general, the CLI flags aim to be flexible but not exhaustive. Config is very strongly encouraged for this use case, and I can't see us devoting effort for 100% coverage of CLI flags.

**Comment by abiodunt** [comment]
Thanks @patrickhulce, `assert.assertions.speed-index.1.minScore=0.7` doesn't work. It returns `TypeError: normalizeAssertion is not a function or its return value is not iterable`. Any other ideas?

Also, I need it for Jenkins pipelines, in order to specify which assertions I want at the time of build. If i'm limited to the config file, i'll need to push the changes I require each time before the build.

**Comment by patrickhulce** [comment]
> It returns TypeError: normalizeAssertion is not a function or its return value is not iterable. Any other ideas?

See **If the assertion is already defined**

Was this assertion already defined in your config file? This error is expected behavior if you have not already set this assertion in your config file.

> If i'm limited to the config file, i'll need to push the changes I require each time before the build.

Or output a new config file at build time.

> in order to specify which assertions I want at the time of build. 

Why do you want to do that? Perhaps there's a better way we can find :)
