### ISSUE TITLE
lhci collect hangs when puppeteer script hangs

### ISSUE THREAD

**Issue by dennis3001** [GoogleChrome/lighthouse-ci#685]
When running lhci collect command it hangs after the first URL.
lhci collect --url https://abc --url https://xyz --logLevel verbose

The cli console just displays the following line and then hangs:
Run #1...done.

 - OS: Windows, Linux (Ubuntu)
 - Chrome

It works fine when the command is executed for each url separately

**Comment by patrickhulce** [comment]
Thanks for filing @dennis3001! I'm not able to reproduce this behavior though. Can you share any additional information about your environment or config that might help?

(Aside: `--logLevel verbose` has no effect on `collect`, it's only a server argument)

**Comment by dennis3001** [comment]
Thanks for quick response.
While creating the minimal reproducible config I realized that it happens due to all scans running in same browser.
So my puppeteer login script wasn't working the 2nd time because it was waiting for login page to load.

**Comment by patrickhulce** [comment]
Aha! Happy to add any docs/error messages you think would be helpful here, but you're right the same browser is working as intended 👍

**Comment by dennis3001** [comment]
Nah, I guess I should read the existing docs better, thanks @patrickhulce !

**Comment by mohitk05** [comment]
Hello @dennis3001, can you add a bit about your solution here? You mentioned that the since all the runs were happening in the same browser, the login script waited for the login page to load. Does this mean that it waited for the login page to load from the first run? What was the change that worked for you? 

I'm facing a similar issue, but cannot seem to find the reason. Thanks!

**Comment by kevinprakasa** [comment]
@mohitk05 in my case, I store the authentication in the cookie. When it tries to load the login page for the second time and the session has been authenticated, skip the login flow and do `page.close()` afterwards. 

I could detect if the session has been authenticated, by looking at the content of the cookies from this method [`page.cookies()`](https://github.com/puppeteer/puppeteer/blob/v2.0.0/docs/api.md#pagecookiesurls)
