### ISSUE TITLE
Overrides for a specific URL

### ISSUE THREAD

**Issue by amannn** [GoogleChrome/lighthouse-ci#690]
**Is your feature request related to a problem? Please describe.**

I'm using `lighthouse-ci` to track performance scores for an app that I'm building. Generally most pages are pretty fast, but e.g. pages behind a login, where an authentication token needs to be resolved first, tend to be a bit slower in regards to LCP.

I'd like to keep my performance threshold high to make sure the public pages of my app can reach the high threshold, while adding some exceptions for slower URLs where a lower performance score is acceptable.

**Describe the solution you'd like**

Overrides, possibly [similar to how ESLint does it](https://eslint.org/docs/user-guide/configuring/configuration-files#how-do-overrides-work), would work well for me.

**Describe alternatives you've considered**

Using a separate config for authenticated- and non-authenticated pages.

**Comment by patrickhulce** [comment]
This is exactly what the [`assertMatrix` property](https://github.com/GoogleChrome/lighthouse-ci/blob/main/docs/configuration.md#assertmatrix) is for. Is there something in particular you're trying to accomplish that can't be done with `assertMatrix`?

**Comment by amannn** [comment]
Thank you for your quick reply! I must have somehow overlooked that option – it definitely does what I'm looking for.
