### ISSUE TITLE
Upload failed with `Error: Unexpected status code 413`

### ISSUE THREAD

**Issue by bradfrosty** [GoogleChrome/lighthouse-ci#709]
**Describe the bug**
During some uploads of lighthouse-ci reports from a large application, I am seeing an unhandled error: 

```
Error: Unexpected status code 413
```

**To Reproduce**
1. Run `lhci autorun` on a URL loading a large SPA (unsure of the minimum size, but happy to provide numbers if needed)

I am uploading to a self-hosted lighthouse-ci server through the docker image. Most runs are fine, but this occasionally happens.

**Expected behavior**
I would expect the upload to finish regardless of report size.

**Logs/Screenshots**

```sh
+ npx lhci autorun
✅  .lighthouseci/ directory writable
✅  Configuration file found
✅  Chrome installation found
⚠️   GitHub token not set
⚠️   Ancestor hash not determinable
✅  LHCI server reachable
✅  LHCI server API-compatible
✅  LHCI server token valid
✅  LHCI server can accept a build for this commit hash
Healthcheck passed!
Started a web server with "npm run start:lhci"...
Running Lighthouse 3 time(s) on http://localhost:3080/
Run #1...done.
Run #2...done.
Run #3...done.
Running Lighthouse 3 time(s) on http://localhost:3080/config/
Run #1...done.
Run #2...done.
Run #3...done.
Done running Lighthouse!

Saving CI project <project-name> (c829f69a-11bd-4328-a7f4-360431321426)
Saving CI build (981b06b0-dffb-4bdb-a0da-8a529f1e6294)
Saved LHR to https://lighthouse.internal (691c9f4f-1b33-491b-9462-875ce93f9ab9)
Saved LHR to https://lighthouse.internal (c7252095-a9b7-4023-8462-93d371f48ab4)
Saved LHR to https://lighthouse.internal (7e4edf9a-a251-4428-ae2a-67346afa4869)

Error: Unexpected status code 413
  <html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx</center>
</body>
</html>

    at ApiClient._convertFetchResponseToReturnValue (/node_modules/@lhci/utils/src/api-client.js:79:21)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async runLHCITarget (/node_modules/@lhci/cli/src/upload/upload.js:438:17)
    at async Object.runCommand (/node_modules/@lhci/cli/src/upload/upload.js:592:16)
    at async run (/node_modules/@lhci/cli/src/cli.js:109:7)WARNING: upload command failed.

Done running autorun.
```

**Environment (please complete the following information):**
 - OS: Linux (cypress-browsers docker image)
 - Browser: Chrome
 - Version: 94 
 - lighthouse-ci version: 0.8.2

**Additional context**

I believe I can fix this from my end in a couple ways:
- Reduce number of audits
- Increase default bodyParser limit through custom middleware

However, given that `@lhci/server` largely owns the express server I wonder if it would make sense for Lighthouse to increase the body parser limit to a higher default, and mention this in the [server docs](https://github.com/GoogleChrome/lighthouse-ci/blob/main/docs/server.md#custom-middleware) or [troubleshooting](https://github.com/GoogleChrome/lighthouse-ci/blob/main/docs/troubleshooting.md).

**Comment by bradfrosty** [comment]
Ended up discovering the reason, commenting for others in case they run into a similar issue. 

Our internal LHCI server is deployed with Kubernetes and uses the nginx controller for ingress. By default, the maximum upload size over nginx is 1MB, and for any URLs that create a report over 1MB this would immediately fail! 

This started to happen after consumers of the internal server changed their LHCI upload target to a domain with DNS configured to route through the kube ingress resource. Previously they just hit the service URL directly.

**Comment by AlexanderChapurin** [comment]
H all! I have faced same issue some time ago. The LH audits took too much time due to the web page was complex, had a huge number of resources, so the size of the  report was too large for the server to handle. Not sure it is the best option, but as a workaround the limit size of the report can temporary changed  to allow LH server to handle the output.

In my case I am using docker container with LHCI and a docker volume for sqlite. So there was a config file was - index.js, located somewhere deep inside docker's overlay2 folder and it had this limitation.
