### ISSUE TITLE
PSI mode on Authenticated Pages

### ISSUE THREAD

**Issue by prarabdhb** [GoogleChrome/lighthouse-ci#722]
**Describe the bug**
We have a set of URLs that we want to get Lighthouse scores for. Some of the URLs require authentication as well. For this, we have written a puppeteer script, which logs in the user on those URLs. 
The issue is, when we try to run lighthouse-ci, using PSI, the authenticated pages don't say logged in, and we are redirected to our login page. 

Is it possible to run, lighthouse-ci using PSI, on authenticated pages?

**To Reproduce**
Run lighthouse-ci with PSI on authenticated pages, it will run on it, as if the page was never authenticated.

**Expected behavior**
The tests should run on authenticate pages

**Environment (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 91

**Comment by poteirard** [comment]
You can find a related discussion here: https://github.com/GoogleChrome/lighthouse-ci/discussions/693
