### ISSUE TITLE
Wondering if collect: url is able to read in variables or functions?

### ISSUE THREAD

**Issue by Weilinnn** [GoogleChrome/lighthouse-ci#723]
At the moment, my code is reading 
<pre><code>
module.exports = {
  ci: {
    collect: {
      url: ['http://localhost:4200/dashboard',],
      startServerCommand: 'npm start',
      settings: {
        configPath: './lighthouse/custom-config.js',
      }
    },
    upload: {
      target: 'temporary-public-storage',
    },
  },
}
</code></pre>

Wondering if the url can be reading from a variable or a function?
<pre><code>
module.exports = {
  ci: {
    collect: {
      url: () => {
        fs = require('fs');
        const {
          url
        } = require('inspector');
        var parser = require('xml2json');
        var loc = [];
        fs.readFile('./sitemap.xml', function (err, data) {
          var json = parser.toJson(data);
          json = JSON.parse(json);
          var sitemap = json.sitemapindex.sitemap;
          for (i = 0; i < sitemap.length; i++) {
            loc.push(sitemap[i].loc);
          }
        });
        return loc;
      },
      startServerCommand: 'npm start',
      settings: {
        configPath: './lighthouse/custom-config.js',
      }
    },
    upload: {
      target: 'temporary-public-storage',
    },
  },
}
</code></pre>

**Comment by poteirard** [comment]
I haven't tried it but provably you can do something like this:

```js
const fs = require('fs');
const { url } = require('inspector');
var parser = require('xml2json');
var urls = [];

fs.readFile('./sitemap.xml', function (err, data) {
  var json = parser.toJson(data);
  json = JSON.parse(json);
  var sitemap = json.sitemapindex.sitemap;
  for (i = 0; i < sitemap.length; i++) {
    urls.push(sitemap[i].loc);
  }
});

module.exports = {
  ci: {
    collect: {
      url: urls,
      startServerCommand: 'npm start',
      settings: {
        configPath: './lighthouse/custom-config.js',
      }
    },
    upload: {
      target: 'temporary-public-storage',
    },
  },
}
```

**Comment by Weilinnn** [comment]
Thanks, but i tried doing that before but module.exports will run first before the function. hence the urls is always [].

**Comment by dineshtrivedi** [comment]
I don't know if you found a solution for this @Weilinnn, but below you can find a variation of what I did on my side, but using your configuration mentioned above.

```javascript
const fs = require('fs');
const parser = require('xml2json');
const urls = []

function moduleExport() {
  const data = fs.readFileSync('./sitemap.xml')
  const json = JSON.parse(parser.toJson(data));
  const sitemap = json.sitemapindex.sitemap;
  for (i = 0; i < sitemap.length; i++) {
    urls.push(sitemap[i].loc);
  }

  return {
    ci: {
      collect: {
        url: urls,
        startServerCommand: 'npm start',
        settings: {
          configPath: './lighthouse/custom-config.js',
        }
      },
      upload: {
        target: 'temporary-public-storage',
      },
    },
  }
}

module.exports = moduleExport();
```

If you are happy with the above or do not need the answer any longer, maybe you can close the issue :)
