### ISSUE TITLE
Document how to setup free CI server

### ISSUE THREAD

**Issue by HugoGresse** [GoogleChrome/lighthouse-ci#74]
Hi,

I've setup a [base PR](https://github.com/HugoGresse/open-feedback/pull/217) with Lighthouse CI on GitHub Action.  [Result](https://storage.googleapis.com/lighthouse-infrastructure.appspot.com/reports/1573724026011-28121.report.html).

But I'm laking some features: 
1. The diff against master branch. 
I though it was built-in and I'll be able to compare by current PR to the master branch for eg. (from [this repo screenshots](https://user-images.githubusercontent.com/39191/68522269-7917b680-025e-11ea-8d96-2774c0a0b04c.png))
My bet is that I can have this diff only with the Lighthouse Server behind. Do you think we could have a free-budget style for Lighthouse Server on OSS projects? 
2. Having a budget setup. I've setup the lighthouserc.json as follow: 
```
{
    "ci": {
        "budgetsFile": "./lighthouse/budget.json",
        "collect": {
            "staticDistDir": "./build"
        },
        "upload": {
            "target": "temporary-public-storage"
        }
    }
}
```
but so far nothing change. 

I'm having difficulties following the documentation overall. There a lot of option but it lack of full example like the cli doc but for the lighthouserc.json.

**Comment by patrickhulce** [comment]
Thanks for filing @HugoGresse!

> My bet is that I can have this diff only with the Lighthouse Server behind.

Correct the historical reports and diffing are available only on the CI server.

> Do you think we could have a free-budget style for Lighthouse Server on OSS projects?

It's on our roadmap, but a large scale service is understandably a much larger effort than a service supporting a single organization. 

> Having a budget setup. I've setup the lighthouserc.json as follow:

Very close!

```json
{
  "ci": {
    "assert": {
        "budgetsFile": "./lighthouse/budget.json"
    },
    "collect": ...
  }
}
```

> I'm having difficulties following the documentation overall. There a lot of option but it lack of full example like the cli doc but for the lighthouserc.json.

We'll work on setting up richer examples of complete config files 👍

**Comment by patrickhulce** [comment]
Oh, if you're just looking for a free hosting setup, Heroku's free plan fits the use case quite well since they come with free persistent postgresql databases. That's actually what we used for our canary testing environment to ensure it would work for folks on free-quality hardware :)

The idea of a free container through GCP is an interesting one, but not sure we'll be able to pull that off internally. We'll keep you posted. 

If you don't mind, I'll convert this issue to writing up a guide on how to get this hosted on Heroku's free tier.

**Comment by HugoGresse** [comment]
that's perfect 👌
Thanks for the help. Waiting for a heroku guide then :D
