### ISSUE TITLE
Lighthouse CI in github action fails to run with error: ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by tal-rofe** [GoogleChrome/lighthouse-ci#770]
**Describe the bug**
I run Lighthouse CI in my github action and it fails with an error.
I used the same configuration in my local environment and it worked fine.

**To Reproduce**
1. Use the following Lighthouse configuration file:
```
module.exports = {
	ci: {
		collect: {
			numberOfRuns: 3,
			startServerCommand: 'yarn run start',
			url: ['http://localhost'],
		},
		assert: {
			preset: 'lighthouse:recommended',
		},
		upload: {
			target: 'temporary-public-storage',
		},
	},
};
```
2. Insert a Lighthouse package.json script to run: `"lighthouse": "lhci autorun"`

3. Insert a Lighthouse step in Github action file:
```
name: Snippet

on:
  pull_request:
    branches: [ main ]

jobs:
  test_pull_request:
    name: Testing & Checking the code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Installing dependencies
        run: yarn install --immutable --immutable-cache --check-cache

      - name: Check build command
        run: yarn run build

      - name: Lighthouse Benchmark
        run: yarn run lighthouse

```

Run it in GH and watch it failing (at-least for me..)

**Expected behavior**
Run without any issue

**Logs/Screenshots**
```
Error: Lighthouse failed with exit code 1
    at ChildProcess.<anonymous> (/home/runner/work/landing-page/landing-page/node_modules/@lhci/cli/src/collect/node-runner.js:120:21)
    at ChildProcess.emit (events.js:400:28)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
```

```
Thu, 03 Mar 2022 21:34:47 GMT LH:ChromeLauncher Killing Chrome instance 2161
Runtime error encountered: Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests. (Details: net::ERR_CONNECTION_REFUSED)
error Command failed with exit code 1.
```

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome
 - Version: Unknown

**Additional context**

**Comment by AshNaz87** [comment]
What version of lhci are you using?

**Comment by tal-rofe** [comment]
@AshNaz87  0.9.0

**Comment by AshNaz87** [comment]
My 2 cents:

- Check that the Node version your app is using is compatible with your version of `lhci`
- Don't think the following is needed in your config file: 
    ```js
    collect: {
      numberOfRuns: 3,
      startServerCommand: 'yarn run start',
      url: ['http://localhost'],
    },
    ```
- Does `lhci autorun` work locally?

**Comment by tal-rofe** [comment]
@AshNaz87 
3. Yes,` lhci autorun` runs successfully locally.
2. Why don't I need it? I need to tell the url and the server script
1. Node version is 14. You think it might be a problem?

**Comment by AshNaz87** [comment]
@tal-rofe 
Re 2. I suspect in your case, I don't think it's necessary

I had issues with my Node versions being incompatible. The repo I was working on runs on Node v12 and lhci v 0.9.0 doesn't support it, so had to downgrade to v 0.8.0

Also, is `yarn run lighthouse` equivalent to `lhci autorun`?

**Comment by tal-rofe** [comment]
@AshNaz87 
Yes, yarn run lighthouse is equiv to lhci autorun

My Node version is 14 in the github action. Do you reckon on using 0.8.0 v for LHCI?

**Comment by AshNaz87** [comment]
@tal-rofe if your repo runs on Node version 12 then yes. Won't harm if you give it a go though

**Comment by tal-rofe** [comment]
@AshNaz87 
Could you please clarify why my "collect" configurations are redundant?
I'm not running a static web application so obviously I need to guide lhci to run a server and the server script.
Also why would I want it to run 3 times?

**Anyway, I downgraded lhci version to 0.8.0 but the error is the same.**

**Comment by AshNaz87** [comment]
Running lhci 3 times is the default. I believe lhci attempts to run your application and it doesn't appear that you have a custom server

**Comment by tal-rofe** [comment]
@AshNaz87 

I do have a custom server. That's why I needed it. Anyway- this works fine.
But yet, I have the issue only in the github action been running.

Really strange because I just followed known guides. Nothing special in my configuration

**Comment by tal-rofe** [comment]
@AshNaz87 

So the problem occurred because the server ran on port "80" in the Github Action machine.
Apparently port "80" is protected to root permissions, so either run "sudo yarn run start" or open the server with other port. Something like "8080". I took the second option.
