### ISSUE TITLE
Hash router being removed on audit

### ISSUE THREAD

**Issue by evelynvieira** [GoogleChrome/lighthouse-ci#797]
Hi everyone. 
Recently we configured the lighthouse-ci and everything was working fine. But we have some hash routers and we are going through some problems.  
When we run these hash urls, the hash is removed by audits so in the output, the finalUrl is not considering what is to the right of the hash.

**Example:** 

Requested URL: `http://example.com/#/some/path`
Final URL: `http://example.com/`

It does not matter if I am running 10 URLS with different hashes, always will be report as a single origin url in the end of audit.

I tried to run with local Chrome Canary following this similar [issue](https://github.com/GoogleChrome/lighthouse/issues/2313) but unsuccessfully. 

I am using Puppeteer to authenticated private pages as it says in the documentation.

Here is my .lighthouserc.js: 
``` js 
const local = {
    upload: {
        target: "filesystem",
        outputDir: ".lighthouseci"
    },
    collect: {
        startServerCommand: "yarn start",
        startServerReadyPattern: "compiled successfully",
        url: urls,
        numberOfRuns: 1,
        puppeteerScript: './.lighthouse/auth.js',
        puppeteerLaunchOptions: {
            args: ["--no-sandbox"],
            disableStorageReset: true,
            defaultViewport: {
                width: 1280,
                height: 720
            }
        }
    },
    assert: {
        preset: "lighthouse:recommended",
        assertions: {
            "categories:performance": ["warn", { "minScore": 0.9 }],
            "categories:accessibility": ["error", { "minScore": 0.7 }],
            "categories:seo": ["error", { "minScore": 0.7 }]
          }
    }
}
```

Versions:

```json
  "@lhci/cli": "^0.9.0",
  "puppeteer": "^14.1.0",
  "sqlite3": "^5.0.2"
```

Thanks for any help :D

**Comment by connorjclark** [comment]
This is captured in an ongoing Lighthouse issue: https://github.com/GoogleChrome/lighthouse/issues/13706

I'd expect it to be resolved for LH 10.0.
