### ISSUE TITLE
Please release 0.9.1

### ISSUE THREAD

**Issue by metalix2** [GoogleChrome/lighthouse-ci#798]
**Is your feature request related to a problem? Please describe.**
Still running a node12 instance from the recipe docker-server It's been 4 months since the previous release.
Could we get a patch release soon? 🙏 

**Describe the solution you'd like**
Release 0.9.1

**Describe alternatives you've considered**
Forking is out of the question

**Additional context**
#775 can be closed once this has been released

**Comment by Divlo** [comment]
It seems like this repository is not maintained anymore... :frowning:
PRs are not reviewed anymore, `npm` vulnerabilities stay unfixed (https://github.com/GoogleChrome/lighthouse-ci/issues/807).
Is there any way, we (users) can help to improve and move things forward? @patrickhulce, @paulirish, @connorjclark

**Comment by metalix2** [comment]
Hey just wanted to follow up  to see if a release was planned any time soon?
@connorjclark
