### ISSUE TITLE
`got` has security vulnerability

### ISSUE THREAD

**Issue by akaustav** [GoogleChrome/lighthouse-ci#807]
The `got@9.6.0` package (that has been indirectly referenced in this repository) contains a "Moderate" security vulnerability - see https://github.com/advisories/GHSA-pfrx-2q88-qq97.
The vulnerability has been fixed in a later version i.e. `got@11.8.5` (or higher).

Here is the output of the `npm why` command ran on a repo containing the `@lhci/cli@0.9.0` - that shows the dependency tree of how the `got` package is being imported into this package:

```
$ npm why got
got@9.6.0
node_modules/got
  got@"^9.6.0" from package-json@6.5.0
  node_modules/package-json
    package-json@"^6.3.0" from latest-version@5.1.0
    node_modules/latest-version
      latest-version@"^5.0.0" from update-notifier@3.0.1
      node_modules/update-notifier
        update-notifier@"^3.0.1" from @lhci/cli@0.9.0
        node_modules/@lhci/cli
          @lhci/cli@"^0.9.0" from the root project
```

Consider upgrading the `update-notifier` package to 6.0.2 or the latest version.
Or as per issue https://github.com/GoogleChrome/lighthouse/issues/13453 consider merging PR #756 where the `update-notifier` package is being removed.

**Comment by jamesarosen** [comment]
#756 has been merged. Oddly, [npm](https://www.npmjs.com/package/@lhci/cli) has `@lhci/cli@0.9.0`, but [the latest in this repo](https://github.com/GoogleChrome/lighthouse-ci/blob/fbd446559c18d09ca8598a7c5c72608604320194/packages/cli/package.json#L3) is `0.1.0` and the last time that line was changed was [3 years ago](https://github.com/GoogleChrome/lighthouse-ci/blame/fbd446559c18d09ca8598a7c5c72608604320194/packages/cli/package.json). I don't think this repo is where the package is getting published from despite the `repository` URL in the `package.json`.

**Comment by akaustav** [comment]
> #756 has been merged.

@jamesarosen - Thank you for merging the PR. I will wait for the next release into the `npm` registry before marking this issue as "Closed".

> Oddly, [npm](https://www.npmjs.com/package/@lhci/cli) has `@lhci/cli@0.9.0`, but [the latest in this repo](https://github.com/GoogleChrome/lighthouse-ci/blob/fbd446559c18d09ca8598a7c5c72608604320194/packages/cli/package.json#L3) is `0.1.0` and the last time that line was changed was [3 years ago](https://github.com/GoogleChrome/lighthouse-ci/blame/fbd446559c18d09ca8598a7c5c72608604320194/packages/cli/package.json). I don't think this repo is where the package is getting published from despite the `repository` URL in the `package.json`.

@jamesarosen - I am not a contributor on this repository - so I am not entirely familiar with the release process for this repository. Normally, I would agree with you. However, I noticed that the release process has been creating [tags](https://github.com/GoogleChrome/lighthouse-ci/tags) in this repository corresponding to the versions being published into the `npm` registry. This repository contains an `npm` workspace - that houses 4 projects / packages - see [this folder](https://github.com/GoogleChrome/lighthouse-ci/tree/main/packages). I am guessing that the release process is missing the step to increment the version numbers within each of the 4 `package.json` files (before the `npm publish` step). For example:

The GitHub tag [v0.9.0](https://github.com/GoogleChrome/lighthouse-ci/releases/tag/v0.9.0) appears to be published as the following `npm` packages:
1. [@lhci/cli@0.9.0](https://www.npmjs.com/package/@lhci/cli/v/0.9.0)
2. [@lhci/server@0.9.0](https://www.npmjs.com/package/@lhci/server/v/0.9.0)
3. [@lhci/utils@0.9.0](https://www.npmjs.com/package/@lhci/utils/v/0.9.0)
4. [@lhci/viewer@0.9.0](https://www.npmjs.com/package/@lhci/viewer/v/0.9.0)

**Comment by ttristan** [comment]
I hope this gets a release soon. lhci/cli is the only package in our large project that has any vulnerabilities - always disappointing to see the orange npm message popping up that something might be wrong.

<img width="462" alt="Screenshot 2022-09-05 at 23 32 31" src="https://user-images.githubusercontent.com/24268434/188514136-afdddd56-bd6c-44f8-99e0-8c41d27f44b3.png">

without @lhci/cli installed:

<img width="476" alt="Screenshot 2022-09-05 at 23 30 09" src="https://user-images.githubusercontent.com/24268434/188514091-26b3ec3c-c777-421a-aab4-0b43cd93f8a1.png">

**Comment by aalvarezwindey-peya** [comment]
Hello,

Any update on this?

**Comment by connorjclark** [comment]
0.10.0 is now available.
