### ISSUE TITLE
Configurable base branch

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/lighthouse-ci#82]
Currently `master` is hardcoded in a number of places, making this fully configurable requires changes in a couple places

- upload configurable ancestor branch
- project model property for configurable base branch
- loading project model in multiple components to use the configured branch

**Comment by lilittad** [comment]
Hey @patrickhulce. First of all thanks for this awesome repo.

Right now I am trying to integrate lighthouse-ci in our CI/CD and I need to have configurable base branch.

Could you specify how you see that? From where it should be configurable ? 
Options I see right now are
1. Define base branch during running `lhci wizard` command. 
2. Define merge request's target branch as a base branch.

Thanks in advance.

**Comment by patrickhulce** [comment]
@lilittad configurable base branch isn't supported yet, this issue is tracking the work necessary to support it.

It would be configured during `lhci wizard` and/or a project management UI that #86 would add.
