### ISSUE TITLE
Server auth / user management

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/lighthouse-ci#85]
Server is currently unauthenticated, adding auth paves the way for UI and API calls that mutate and/or delete data

- [x] add project-specific admin tokens (631ab018c9938dca7fd52e45db9402a8dd979797)
- [x] delete projects route protected by admin token (0be8bdca705bbb9fd7236e506bdc0a318c21347b)
- [x] add admin token UI (#245)
- [x] add project deletion UI (#245)
- [ ] add basic auth to server
- [ ] add basic auth to ApiClient and wizard/upload options

**Comment by patrickhulce** [comment]
Current plan here:

- Introduce a second "admin" token that is created at project creation, the admin token should never be exposed publicly in contrast to the current project token
- Require this admin token whenever data is going to be edited or deleted
- Add UI on the server side to enter your admin token that will be saved to localStorage and used for project administrative functions

Punt any more advanced multi-user management features.

**Comment by KartoffelToby** [comment]
@patrickhulce The current plan sound's good.

I have some proposals too:

- User Auth for the hole UI/API. If i'm right at this time it's only possible with htaccess or comparable
- admin Token for Add Projects via API/UI

**Comment by patrickhulce** [comment]
Thanks for the feedback @KartoffelToby!

> User Auth for the hole UI/API. If i'm right at this time it's only possible with htaccess or comparable

Good suggestion 👍 we plan to accomplish this with `Basic` auth (updated the todo list with this)

> admin Token for Add Projects via API/UI

Creating a new project has the same API-level permissions in our two-tiered model as other current requests i.e. no data is lost or destroyed. In this model, you can either allow untrusted users to create data or you don't. If you want to protect against untrusted users creating data then the server would need to use the Basic auth solution. Project creation UI itself is covered by #86.

**Comment by patrickhulce** [comment]
leaving open for basic auth story

**Comment by gulfaraz** [comment]
@patrickhulce Is it possible to set the [basicAuth](https://github.com/GoogleChrome/lighthouse-ci/blob/main/docs/configuration.md#basic-auth-server) settings via env variables in the docker-compose file?

I see that the [docker server image](https://github.com/GoogleChrome/lighthouse-ci/tree/main/docs/recipes/docker-server) uses [`lighthouserc.json`](https://github.com/GoogleChrome/lighthouse-ci/blob/main/docs/recipes/docker-server/lighthouserc.json) which [does not have notion of environment variables](https://stackoverflow.com/a/36962638/1753041).

If [`lighthouserc.js`](https://github.com/GoogleChrome/lighthouse-ci/blob/main/docs/configuration.md#configuration-file) was used instead, then it allows us to inject env vars via the docker-compose file.

Please let me know if I'm missing a recommended approach to do setup `basicAuth` in the [docker-compose](https://github.com/GoogleChrome/lighthouse-ci/tree/main/docs/recipes/docker-server#docker-compose) config.

**Comment by patrickhulce** [comment]
You can still override anything set in the config with `LHCI_*` environment variables regardless of the type of config used (see [docs](https://github.com/GoogleChrome/lighthouse-ci/blob/main/docs/configuration.md#environment-variables)). You're also free to tweak the dockerfile on your own to use `lighthouserc.js` if you prefer. It's just an example ;)

**Comment by gulfaraz** [comment]
@patrickhulce I used the env vars approach. It works exactly as I hoped. Thank you!

**Comment by Woitekku** [comment]
@patrickhulce @gulfaraz how this supposed to work?
`root:/usr/src/lhci# env | grep LHCI
LHCI_BASICAUTH__PASSWORD=XXXXXXXX lhci server
LHCI_BASICAUTH__USERNAME=YYYYYYYYY lhci server

root:/usr/src/lhci# ps -ef | grep lhci
root        37     8  0 09:28 ?        00:00:00 sh -c lhci server --config=./lighthouserc.json
root        38    37  0 09:28 ?        00:00:01 node /usr/src/lhci/node_modules/.bin/lhci server --config=./lighthouserc.json
root       403    76  0 09:39 pts/0    00:00:00 grep lhci
`

For unknown reason I cannot pass basic auth config via ENV VARS, what am I missing?

**Comment by patrickhulce** [comment]
@Woitekku did you try `LHCI_BASIC_AUTH__PASSWORD`? The option is `basicAuth` not `basicauth` so there should be an underscore in there somewhere.

**Comment by Djiit** [comment]
Hey, having the same issue here.

I guess a working example these passed as env var would help a lot: 
- basicAuth.username
- basicAuth.password
- upload.extraHeaders

Thanks 🙏
