### ISSUE TITLE
"Unable to connect to Chrome" caused by node 18

### ISSUE THREAD

**Issue by Hahlh** [GoogleChrome/lighthouse-ci#862]
**Describe the bug**
On usage with node 18, it isn't possible to run `lhci` neither in Github Actions nor locally. A switch with `nvm` to use node 16 resolved the issue and allows the runs to complete successfully.   

I was unsure what additional information to provide and opened this issue mostly to document this workaround for other people running into the same issue. 

As Github Actions workflow examples described in the docs explicitly use node 16, I suppose that this is a known behavior. If that is indeed the case, throwing an error that let's the user know about this limitation might be a good approach.

**Comment by bfeister** [comment]
Seeing the same thing on our end

**Comment by dsriram3194** [comment]
I was able to fix this by updating the following dependencies

"@lhci/cli": "0.12.0",
"yargs": "17.7.2",
