### ISSUE TITLE
Github token should not be a warning if repo does not have a github remote

### ISSUE THREAD

**Issue by calvinf** [GoogleChrome/lighthouse-ci#88]
When running `lhci`, it's showing a warning:

> ⚠️   Github token set

A GitHub token is not required to run my code locally and upload to `temporary-public-storage`.  I'm not using a GH action.

Config seems to come from here:

https://github.com/GoogleChrome/lighthouse-ci/blob/c588086e3899b5714e9d7d735381b1143bd12bc2/packages/cli/src/healthcheck/healthcheck.js#L55-L60

I'm not sure the right way to set it up related to people using it through GH action, but I know it shouldn't be set to run for everybody running the upload task.

**Comment by patrickhulce** [comment]
Thanks for filing @calvinf! This is WAI, that's why it's a warning and not an error. The GitHub token has no relationship to GitHub Actions and is for use with any GitHub status check. It's highly encouraged to use a status check to get links to the output of LHCI and there's really not a way to know you don't care about status checks vs. just misconfiguring status checks.

In a future world in which we can detect that you're not hosting your code on GH at all, then it makes sense to hide this check in that case. Otherwise we'd like to preserve it as a warning.

**Comment by calvinf** [comment]
In the case of locally run web apps, checking Git config makes sense.  

For external web apps under test (i.e., LHCI run from node.js via @lhci/cli, but web app running via code stored in a different package/repo and maybe not available directly at all), you wouldn't have any way to check locally to determine whether a GitHub status check is needed.

It seems to me there needs to be a config for enabling a status check or some extensible way to provide "hooks" (you don't want separate configs for each possible code host / CI service).

**Comment by patrickhulce** [comment]
> you wouldn't have any way to check locally to determine whether a GitHub status check is needed

In the case where there's no local git repo at all, then the status check already doesn't make any sense (nor would any of the CI diffing logic work properly), so that seems like a good rule to avoid listing it in the status check 👍

**Comment by patrickhulce** [comment]
> It seems to me there needs to be a config for enabling a status check or some extensible way to provide "hooks" (you don't want separate configs for each possible code host / CI service).

I'm not totally sure what you mean by this. It can already be configured using the `lighthouserc.json` and/or a single environment variable.

**Comment by calvinf** [comment]
`githubToken` is for "GitHub Status Checks", right?  As it's a GitHub-specific concept, it won't be relevant to all users (i.e., not to users whose source is not stored on GitHub).  It's configurable, but only for GitHub users.  If this will in the future support status checks for other providers (BitBucket, GitLab) it could be made more generic, but I'm also not sure whether they use the same format for reporting success/failure of status checks (I haven't researched that before).

**Comment by patrickhulce** [comment]
> As it's a GitHub-specific concept, it won't be relevant to all users (i.e., not to users whose source is not stored on GitHub)

Totally 👍 that's why we're going to check to see if the code is stored on github before showing this warning.

> it could be made more generic

I think our approach here will just be adding new options for other providers ala `bitbucketToken`, `gitlabToken`, etc if necessary. We haven't researched those either yet.
