### ISSUE TITLE
Chrome v111 with lhci/cli@v0.11.0: Cannot create new tab, and no tabs already open

### ISSUE THREAD

**Issue by elichad** [GoogleChrome/lighthouse-ci#886]
Documented in #https://github.com/GoogleChrome/lighthouse/issues/14885 . Sounds like upgrading the Lighthouse version should resolve it.

**Comment by OllysCoding** [comment]
Any update on this? we're experiencing this issue as well.

**Comment by ThomasLarge** [comment]
I am seeing this too, it would be great to understand whats happening here

**Comment by ThomasLarge** [comment]
> As a temporary workaround for GitHub actions I've used https://github.com/browser-actions/setup-chrome to install a version of chrome without this issue, then set a `CHROME_PATH` env var to the downloaded version.
> 
> Looks like #890 will fix this issue?

@jb-0 I tried this but still had the same issue, what version of chrome are you using?

**Comment by ThomasLarge** [comment]
Got it working with `999338`
