### ISSUE TITLE
Lighthouse Server UI starts to break when URL is not accessed from root URL

### ISSUE THREAD

**Issue by Taewan-P** [GoogleChrome/lighthouse-ci#893]
**Describe the bug**
Lighthouse Server UI starts to break when URL is not accessed from root URL.

**To Reproduce**
1. Access custom server
2. Browse a little
3. Access to a direct url ex) https://<server_url>/app/projects/<projectname>/compare/4a4f6dd4-4d67-4672-a93a-dd14a73b0604
4. From the site accessed from step 3, all html should break wherever you click or go.

**Expected behavior**

UI should not break at all circumstances

**Logs/Screenshots**
If applicable, add LHCI logs or screenshots to help explain your problem.
<img width="1238" alt="image" src="https://user-images.githubusercontent.com/27392567/228835528-f1dafd70-fe67-4f38-ae19-5fd1fd8e6f4a.png">
<img width="1235" alt="image" src="https://user-images.githubusercontent.com/27392567/228836910-28244b59-faf5-40fb-86c0-dd24d0a937b0.png">

**However, when accessing to other pages after the ui is broken, there is a browser console error like this:**
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/27392567/228836755-b160cfa7-631d-46ad-a517-6e8ae09e7c1c.png">

Server log shows all 200 in resources

**Environment (please complete the following information):**
 - OS: [e.g. iOS] macOS
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] LHCI Server v0.11

**Additional context**

**Comment by Taewan-P** [comment]
+ How to fix not to break (temporary solution)
- From the broken page, just go to the root of the lighthouse server, where all projects are shown.

**Comment by sandrodesouza** [comment]
Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@lhci/server/dist/index.html b/node_modules/@lhci/server/dist/index.html
index 960e15e..6bffd00 100644
--- a/node_modules/@lhci/server/dist/index.html
+++ b/node_modules/@lhci/server/dist/index.html
@@ -21,7 +21,7 @@
                 l.href = url;
                 document.head.appendChild(l);
             }
-            loadStyle('chunks/entry-WKRDB3RZ.css');
+            loadStyle('/app/chunks/entry-WKRDB3RZ.css');
         }());
     </script>
 </head>
```

**Comment by Taewan-P** [comment]
Thank you for the information! 👍
