### ISSUE TITLE
Support of # URLs for upload multiple results.

### ISSUE THREAD

**Issue by MarkusBordihn** [GoogleChrome/lighthouse-ci#896]
**Describe the bug**
Even if I provide several # URLs and lhci is testing separat them, I only get a single result URL uploaded to the temporary public storage with one of these # URLs.

**To Reproduce**
1. Create a config which use several # urls as test urls like:
```
module.exports = {
  ci: {
    collect: {
      startServerCommand: 'npm run start:lighthouse',
      startServerReadyTimeout: 25000,
      url: [
        'http://localhost:8080',
        'http://localhost:8080/#/desktop',
        'http://localhost:8080/#/game_editor',
      ],
    },
    upload: {
      target: 'temporary-public-storage',
    },
  },
};
```
2. Run the lighthouse-ci over `lhci autorun`
3. The corresponding report will only contain the url http://localhost:8080 with the result of http://localhost:8080/#/desktop.

**Expected behavior**
I would expect that for each URL a separated report is generated regardless if they are full URLs or # URLs.

**Logs/Screenshots**
```
Running Lighthouse 3 time(s) on http://localhost:8080
Run #1...done.
Run #2...done.
Run #3...done.
Running Lighthouse 3 time(s) on http://localhost:8080/#/desktop
Run #1...done.
Run #2...done.
Run #3...done.
Running Lighthouse 3 time(s) on http://localhost:8080/#/game_editor
Run #1...done.
Run #2...done.
Run #3...done.
Done running Lighthouse!

Uploading median LHR of http://localhost:8080/...success!
Open the report at https://storage.googleapis.com/lighthouse-infrastructure.appspot.com/reports/1681000128500-47104.report.html
No GitHub token set, skipping GitHub status check.

Done running autorun.
```

**Environment (please complete the following information):**
 - OS: Windows, GitHub Actions
 - Browser: Not relevant
 - Version: "@lhci/cli": "^0.11.0",

**Additional context**

**Comment by chaimabg** [comment]
@MarkusBordihn, I have the same problem (#887 ) and probably it will be solved once they upgrade Lighthouse version used by Lighthouse CI.

**Comment by adamraine** [comment]
Merging into https://github.com/GoogleChrome/lighthouse-ci/issues/887
