### ISSUE TITLE
Using finalDisplayedUrl instead of finalUrl when uploading reports ( for @lhci/cli@0.12.0)

### ISSUE THREAD

**Issue by chaimabg** [GoogleChrome/lighthouse-ci#900]
**Is your feature request related to a problem? Please describe.**
There is a problem with the displayed url (for # URLs) after creating the reports, encountered when running Lighthouse CI for # URLs (Issues related to the same problem : #896 and #887 ) 
The problem affects how reports are generated and displayed on lighthouse server.
 We are expecting a separated report for each URL, generated regardless if they are full URLs or # URLs.

**Describe the solution you'd like**
The requested solution: using **finalDisplayedUrl** instead of **finalUrl** for Lighthouse CI version 0.12.0, when uploading reports (requested changes in [upload.js](https://github.com/GoogleChrome/lighthouse-ci/blob/9d710c1960c7b9c27b2fb09857fb0353ef275373/packages/cli/src/upload/upload.js))

**Comment by adamraine** [comment]
Merging into https://github.com/GoogleChrome/lighthouse-ci/issues/887
