### ISSUE TITLE
Bug localStorage in Lighthouse Report Diff Tool

### ISSUE THREAD

**Issue by torresgol10** [GoogleChrome/lighthouse-ci#935]
The bug is on the web: https://googlechrome.github.io/lighthouse-ci/difftool/

If you upload a large file, for example 1.4MB, the application stays with the fixed animation, in the console, it gives a failure, which says that the maximum size has been accessed in the localStorage.

Browser, Chrome Desktop latest version.
 
I was looking at the code and I can make a PR, adding a try catch in the part where the failure occurs, so you can catch the error, but the application will continue to run.

Thanks.

**Comment by paulirish** [comment]
Nice! yeah a PR would be great. :)

**Comment by paulirish** [comment]
fixed by  #938
